### DISCUSSION TITLE
Beautiful subscriptions, with filter exclude.

### DISCUSSION THREAD

**Discussion by psyciknz** [jmbannon/ytdl-sub#1046] [Configs]
I've made a filter exclude for a channel:
```
show_excludes:
    filter_exclude:
      - >-
        { %contains( %lower(title), 'weekly submissions' ) }
```

And I apply in of the following subscription:
```
tv_show | only_recent_videos | show_excludes:
  = Cars:
    "Dashcam_Owners_Australia": "https://www.youtube.com/channel/UCvfqpaehdaqtkXPNhvJRyGA"
```
Now that I've done that, I am thinking I might want to do it to others, but having a dedicated filter doesn't see all that efficient.

Is there a method that I could go:
```
show_excludes:
    filter_exclude:
      - >-
        { %contains( %lower(title), 'my-text+variable' ) }
```
with
```
tv_show | only_recent_videos | show_excludes:
  = Cars:
    "Dashcam_Owners_Australia": "https://www.youtube.com/channel/UCvfqpaehdaqtkXPNhvJRyGA" my-text-vaariable="weekly submissions"
```

Basically setting a 3rd variable on a beatified subscription.

**Comment by psyciknz** [comment]
So i think I've worked it out.

In my config I have the following preset:
```
show_excludes_variable:
    filter_exclude:
      - >-
        { %contains( %lower(title), exclude_title ) }
```

Then in my subscription is changes slightly to :
```
tv_show | only_recent_videos | show_excludes_variable:
  = Cars:
    "~Dashcam_Owners_Australia":
      url: "https://www.youtube.com/channel/UCvfqpaehdaqtkXPNhvJRyGA"
      exclude_title: "weekly submissions"
```
Which allows the "weekly submissions" to be passed to the config preset as the variable _exclude_title_

**Comment by psyciknz** [comment]
If, for these two entries I wanted to increase the max_downloads

Would this do it?  If max downloads already set as part of another preset?

  ```
# Setting override of exclude_title in subscriptions.yaml will exclude videos of title (dashcam australia)
  show_excludes_variable:
    filter_exclude:
      - >-
        { %contains( %lower(title), exclude_title ) }
    ytdl_options:
      format: "bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"
      max_downloads: 16
```

**Reply by jmbannon** [reply]
It will if you apply `show_excludes_variables` after the other preset

**Comment by psyciknz** [comment]
Ok thanks.

One last question.   I have "exclude_title" as the variable passed in from subscriptions.yaml.   Can I pass in the whole clause?

ie subscriptions of 
```
tv_show | only_recent_videos | show_excludes_variable:
  = Cars:
    "~Dashcam_Owners_Australia":
      url: "https://www.youtube.com/channel/UCvfqpaehdaqtkXPNhvJRyGA"
      clauses:
         -  { %contains( %lower(title), "weekly submissions") }
         -  { %contains( %lower(title), "Other exclusion") }
```

What would the preset look like then?
```
# Setting override of exclude_title in subscriptions.yaml will exclude videos of title (dashcam australia)
show_excludes_variable:
  filter_exclude:
    - >-
      ????????
  ytdl_options:
    max_downloads: 16
```
