### DISCUSSION TITLE
Not seeing latest added videos

### DISCUSSION THREAD

**Discussion by cbrookins** [jmbannon/ytdl-sub#1048] [Q&A] [answered]
I could not find anything related to this, or whether this is expected behavior.  
I am using the  [MLB highlights playlist](https://www.youtube.com/playlist?list=PLL-lmlkrmJamr_QNPS_M8yWiDako963UM) as an example.   ytdl-sub starts at item 10.  Doesnt mention 1-9 in the logs.  I have tried adding the playliststart: 1 option but it makes no difference.  Usually once the items hit 24 hrs old they will show up.

```
[ytdl-sub:downloader] Downloading metadata for 2024 Game Highlights  
[ytdl-sub:downloader] Downloading metadata for D-backs vs. Astros Game Highlights (9/8/24) | MLB Highlights  
[ytdl-sub:downloader] Downloading metadata for Guardians vs. Dodgers Game Highlights (9/8/24) | MLB Highlights  
[ytdl-sub:downloader] Downloading metadata for Giants vs. Padres Game Highlights (9/8/24) | MLB Highlights  
[ytdl-sub:downloader] Downloading metadata for Angels vs. Rangers Game Highlights (9/8/24) | MLB Highlights  
[ytdl-sub:downloader] Downloading metadata for Mariners vs. Cardinals Game Highlights (9/8/24) | MLB Highlights
```

![](https://i.imgur.com/PyM92Nw.png)

config.yaml

```
  shows:
    preset: 
      - "Jellyfin TV Show by Date"
      - "max_1080p"
    nfo_tags:
      nfo_name: "{title_sanitized}.nfo"
      nfo_root: "episodedetails"
      tags:
        title: "{title_sanitized}"
        episode: "{upload_month}{upload_day_padded}"
    output_options:
      output_directory: "{output_directory}"
      file_name: "{title_sanitized}.{ext}"
      thumbnail_name: "{title_sanitized}.{thumbnail_ext}"
      maintain_download_archive: True
      keep_files_before: now
      keep_max_files: 5
    ytdl_options:
      max_downloads: 5
      break_on_existing: True
    date_range:
     before: "now"
     after: "now-1week"
    output_directory_nfo_tags:
        enable: True
    overrides:
      embed_thumbnail: True
      output_directory: "/downloads"
```

subscriptions.yaml
```
mlb:
  preset:
    - "shows"
  overrides:
    output_directory: "/downloads/mlb"
    url: "https://www.youtube.com/playlist?list=PLL-lmlkrmJamr_QNPS_M8yWiDako963UM"
    keep_max_files: 3
  ytdl_options:
    max_downloads: 10
  filter_include:
      - >-
        { %contains( %lower(title), "braves" ) }
```
