### DISCUSSION TITLE
Include YouTube Channel Id/Uploader id in "tv_show_name"

### DISCUSSION THREAD

**Discussion by 0ut1awStar** [jmbannon/ytdl-sub#1118] [Q&A]
I am trying to find a way to add the YouTube channel id/uploader id into the "tv_show_name:" override. 

    tv_show_directory: "/tv_shows"
    episode_file_name: "{release_date_standardized} - {title} [{uid}]"
    tv_show_name: "{subscription_name} [{uploader_id}]"
    
 But when I try adding it, I receive the following error:
` [ytdl-sub] static formatters must contain variables that have no dependency to entry variables`

It it possible to accomplish what I am trying to do?

**Comment by jmbannon** [comment]
Its possible but I highly recommend relying the subscription name because it's 'static', i.e. doesn't rely on parsing metadata to create the root folder.

To change, refer to https://ytdl-sub.readthedocs.io/en/latest/config_reference/prebuilt_presets/tv_show.html

Specifically, you'll want something like:
```
output_options:
  output_directory: "{tv_show_directory}"

overrides:
  episode_file_path: "{tv_show_name_sanitized} [{uploader_id}]/{season_directory_name_sanitized}/{episode_file_name_sanitized}"
```
