### DISCUSSION TITLE
Subtitles aren't converted to srt

### DISCUSSION THREAD

**Discussion by nothing2obvi** [jmbannon/ytdl-sub#1227] [Q&A]
Hello! ytdl-sub is great but I'm having an issue. I'm using the `subtitles` plugin but it won't convert to `srt`.

This is (part of) my preset:
```
subtitles:
      subtitles_type: "srt"
      embed_subtitles: True
      languages:
        - "en"
        - "ko"
        - "ja"
        - "es"
        - "tl"
      allow_auto_generated_subtitles: True
```

I know it's working somewhat because it actually downloads specifically those languages, but they are still `vtt`.

Any help would be greatly appreciated. Thanks!
