### DISCUSSION TITLE
Music Video Separation or Re-Formatting

### DISCUSSION THREAD

**Discussion by suasuasuasuasua** [jmbannon/ytdl-sub#1238] [Q&A]
Is there a way to ignore music videos when downloading an artist's release page? Or force an audio format like mp3? For example, I listen to K-Pop, and they usually have music videos along with the regular music tracks.

Here is what my Navidrome looks like. There are a ton of duplicate albums because of the music videos (I think).

<img width="1366" alt="image" src="https://github.com/user-attachments/assets/9232257a-1e14-45d8-9e8c-5369eb77ac00" />

For reference, here is one of those albums with a single music video.

<img width="1366" alt="image" src="https://github.com/user-attachments/assets/c627cbe2-a07c-437d-bf57-4546aac17ae2" />

---

My simple config:

```yaml
YouTube Releases:
  = K-Pop:
    "Kiss of Life": "https://www.youtube.com/@KISSOFLIFE_official/releases"
```

I'm a noob with yt-dlp and this project, so I appreciate any help. Thank you!
