### DISCUSSION TITLE
Speech normalization: Calm down those high-energy youtubers to avoid jumpscares

### DISCUSSION THREAD

**Discussion by miangraham** [jmbannon/ytdl-sub#1245] [Configs]
There's a self-hosting YT channel whose content I really like, but I've always had a hard time listening to them due to their quieter normal speech followed by huge bursts of volume when they go high-energy and start almost yelling after scene transitions.

I was pleasantly surprised that ytdl-sub's support for post-processing arguments makes this problem really easy to fix automatically by using ffmpeg's normalization filters. Here's my tiny config show-and-tell with the subscription entry that makes my ears much happier:

```yaml
ServeTheHome:
  download: https://www.youtube.com/@ServeTheHomeVideo/videos
  file_convert:
    convert_to: mp4
    convert_with: ffmpeg
    ffmpeg_post_process_args: -vcodec copy -acodec libopus -filter:a speechnorm=e=50:c=50:r=0.001:l=1:p=0.25
```

I'm already using mp4+opus for other downloads, so this just adds a new audio filter, speechnorm, which is documented in detail over here: https://ffmpeg.org/ffmpeg-filters.html#speechnorm

The most important parameter is `p=0.25` which means to limit peaks to 25% volume, turning the loud parts way down. The quieter parts are also amplified so they're audible as well. Expect to need to fiddle with these numbers if you're trying them with a different channel. ffmpeg also has a ton of other filters if speechnorm isn't quite what you need--see the manual link above for some heavy reading and possible inspiration.

With these settings in place, now I can do other work while listening to this channel in the background without jumping in my seat every few minutes. Bliss!
