### DISCUSSION TITLE
Config for Jellyfin and YouTube channel subscriptions

### DISCUSSION THREAD

**Discussion by AlexGustafsson** [jmbannon/ytdl-sub#396] [Configs]
I'm running Jellyfin and ytdl-sub in a couple of Docker containers.
I use https://github.com/ankenyr/jellyfin-youtube-metadata-plugin installed in the Jellyfin container to handle metadata.
The videos are stored in a directory / library specifically for YouTube videos, which is configured to use the metadata plugin.

The below configuration works well for YouTube subscriptions.

## `config.yaml`

```yaml

configuration:
  working_directory: /tmp/ytdl-sub-downloads

presets:
  # Download last week's videos and keep them for two weeks
  only_recent_videos:
    # Download range
    date_range:
      after: "today-{download_range}"
    # Retention
    output_options:
      keep_files_after: "today-{retention}"

    ytdl_options:
      break_on_reject: True

    overrides:
      download_range: "1week"
      retention: "2weeks"

  # Download videos for a YouTube channel
  channel:
    overrides:
       # Required overrides:
       # - channel
       # - url
       # The file name is in the format supported by
       # https://github.com/ankenyr/jellyfin-youtube-metadata-plugin
       file_name: "{channel_sanitized} - {upload_year}{upload_month_padded}{upload_day_padded} - {title_sanitized} [{uid}]"

    download:
      download_strategy: url
      url: "{url}"

    output_options:
      # The /videos directory is shared with a directory in Jellyfin's /media
      output_directory: "/videos"
      # Jellyfin requires one video per directory. Store the video, metadata and subtitles
      # in a directory by the same name as the files
      file_name: "{file_name}/{file_name}.{ext}"
      info_json_name: "{file_name}/{file_name}.{info_json_ext}"
      maintain_download_archive: True

    subtitles:
      languages: en
      allow_auto_generated_subtitles: True
      subtitles_name: "{file_name}/{file_name}.{lang}.{subtitles_ext}"
```

## `subscription.yaml`

```yaml
example:
  preset:
    - only_recent_videos
    - channel

  overrides:
    channel: Example Name
    url: https://www.youtube.com/channel/example-channel-id
```
