### DISCUSSION TITLE
Using `aria2c` with ytdl-sub

### DISCUSSION THREAD

**Discussion by qwerty12** [jmbannon/ytdl-sub#576] [Configs]
Not a full config to share - I'm just using the built-in presets by way of examples\tv_show_config.yaml. Just had to set `ffmpeg_path` and `ffprobe_path` on top (Windows). Oh, I disabled .info.json generation with `info_json_name: ''` - I'm using Jellyfin to watch the downloads, so I don't really have a use for those. I wanted to use `aria2c` for my YT downloads, so after reading the yt-dlp argument-parsing code, here's something to put into a preset:

```yaml
    ytdl_options:
      external_downloader:
        default: "aria2c"
      compat_options:
        - 'no-external-downloader-progress'
      external_downloader_args:
        aria2c:
          - '--show-console-readout=false'
          # - '--console-log-level=error'
          # - '--enable-color=false'
          # - '--quiet=true'
```

`aria2c[.exe]` will need to be in your `$PATH`.

`no-external-downloader-progress` is present to work around a possible bug but I'm not sure if it's even needed - after about 500 or so downloads with aria2c, I didn't hit yt-dlp issue #5931 once. Still, aside from possibly clogging up the YAML file, it won't do any harm. 

`show-console-readout=false` is passed to aria2c to match ytdl-sub's default of not showing download progress. `aria2c` will still print error messages, however. If you desire all aria2c output to be silenced, just uncomment the `quiet` line.

(As an aside, the equivalent of `--force-ipv4` is `source_address: '0.0.0.0'`)

Many thanks for this program, jmbannon, as I took a look at the alternatives and they simply weren't suitable for my needs for various reasons. ytdl-sub does exactly what I need without any bloat.
