### DISCUSSION TITLE
How to follow along with the walk-through when running as a docker container?

### DISCUSSION THREAD

**Discussion by STRAYKR** [jmbannon/ytdl-sub#682] [General]
So I have a docker compose stack running, but I'm a bit of a noob when it comes to running commands in docker containers. 

I've figured out enough to get into the container `docker exec -it bf7722fe7dcd sh` but when I run `ytdl-sub --dry-run --config config.yaml sub subscriptions.yaml` it errors, presumably because my config.yaml is in the Linux home dir, not inside docker?

```
docker exec -it bf7722fe7dcd sh
root@bf7722fe7dcd:/# ytdl-sub --dry-run --config config.yaml sub subscriptions.yaml
[ytdl-sub] The file 'config.yaml' does not exist.
```

Not sure where to go from here?

docker compose section:
```
  ytdl-sub:
    image: ghcr.io/jmbannon/ytdl-sub:latest
    container_name: ytdl-sub
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/mods:universal-cron
    volumes:
      # ensure directories have user permissions
      - ./docker/ytdl-sub:/config
      - ./data/media/tv:/tv_shows  # optional
      - ./data/media/movies:/movies  # optional
      # - <path/to/music_videos>:/music_videos  # optional
      # - <path/to/music>:/music  # optional
    restart: always
```
