### DISCUSSION TITLE
Download Video & Extracted Audio to Separate Folders

### DISCUSSION THREAD

**Discussion by volitanic** [jmbannon/ytdl-sub#786] [Q&A] [answered]
Does anyone have ideas on how I might do this?  I have mapped both folders and tried using the examples, but it keep re-downloading the audio on every run.

I have to be doing something simple wrong, but cannot figure out what.  My goal if for a playlist to download the video to folder X then the extracted audio to folder Y

Thanks!

**Comment by volitanic** [comment, marked as answer]
maintain_download_archive: True

**Comment by Asgoret** [comment]
@volitanic can you please share subscription and config file for this configuration?) Id like do the same, but no clue how to configure that at the moment

**Reply by volitanic** [reply]
Here is how I did it.  Code blocks are being crazy, so you may need to tweak the indenting when you use it.

This is the audio config.
------------------------------
```
sleep:
    download:
      url: "{url}"

      output_options:
      output_directory: "{music_directory}" 
      file_name: "{track_full_path}"
      thumbnail_name: "{album_cover_path}"
      maintain_download_archive: True

    audio_extract:
      codec: "mp3"
      quality: 320

    music_tags:
      artist: "{track_artist}"
      artists: "{track_artist}"
      albumartist: "{track_artist}"
      albumartists: "{track_artist}"
      title: "{track_title}"
      album: "{track_album}"
      track: "{track_number}"
      tracktotal: "{track_total}"
      year: "{track_year}"
      genre: "{track_genre}"

    overrides:
      # Track Overrides
      track_title: "{title}"
      track_album: "Singles"
      track_artist: "{channel}"
      track_number: "1"
      track_number_padded: "01"
      track_total: "1"
      track_year: "{upload_year}"
      track_genre: "Sleep"
      # Directory Overrides
      music_directory: "/sleep"  #change this part if nothing else
      artist_dir: "{track_artist_sanitized}"
      album_dir: "[{track_year}] {track_album_sanitized}"
      track_file_name: "{track_number_padded} - {track_title_sanitized}.{ext}"
      track_full_path: "{artist_dir}/{album_dir}/{track_file_name}"
      album_cover_path: "{artist_dir}/{album_dir}/folder.{thumbnail_ext}"
```


Video Config
-----------------------------------
```
TV Show Standard:
    preset:
      - "base"
      - "sponsorblock"
      - "no_shorts"
      - "season_by_year__episode_by_month_day"
      - "include_info_json"
      - "tv_show_paths"
      - "Only Recent"
      - "plex_tv_show_by_date"

    overrides:
      only_recent_date_range: "2months"
      keep_files_after: "today-3months"

    output_options:
      maintain_download_archive: True  
```


Audio Sub
--------------------------------------------------
```
SleepAudio:
  preset:
    - "sleep"

  overrides:
    # Required to specify for every subscription
    url: "https://www.youtube.com/playlist?list=XXXX"
```


Video Sub
----------------------------------
```
TV Show Standard:
  = Sleep | = TV-G:
    "Sleep":
      overrides:
        url: "https://www.youtube.com/playlist?list=XXXX"
        tv_show_directory: "/sleeptv"
        only_recent_date_range: "100years"
        keep_files_after: "today-100years"
        subscription_indent_1: "Sleep"
        subscription_indent_2: "TV-G"  
```
