### DISCUSSION TITLE
Multiple URLs in Subscription

### DISCUSSION THREAD

**Discussion by lizaoreo** [jmbannon/ytdl-sub#818] [Q&A] [answered]
Working on downloading some music to play in the background with Plex.  I'm using the sample music config and subscriptions from the example section in the repo (though now that appears to have disappeared?).  I got it working good with my test video, a single video with chapters for the different tracks.  Then I went to add a second sub to the sub file.  But this time I have several videos from a channel, no playlist, that I'm trying to add.  I've tried different ways of formatting the URLs, but it always gives me an error that it wants a single string and not an array.  Do I have to make a separate subscription entry for each video or is there something I'm missing?

This is the sub code:
```
relaxing_sounds_kitchokudo:
  preset: "albums_from_chapters"
#  # Explicitly set the URL, track artist, and genre.
#  # Override various track properties using the regex variables we extracted.
  overrides:
    url: ["https://www.youtube.com/watch?v=mw34FQUIu3I", "https://www.youtube.com/watch?v=mw34FQUIu3I", "https://www.youtube.com/watch?v=VAl7q9dHGwY"]
    track_artist: "Relaxing Sounds Kitchokudo"
    track_genre: "Piano; Instrumental; Game; Rain; Jazz"
    track_title: "{chapter_title}"
```

And this is the config:
```
configuration:
  working_directory: '.ytdl-sub-downloads'
  umask: "002"

presets:
  base:
    output_options:
      output_directory: "{music_directory}"
      file_name: "{track_full_path}"
      thumbnail_name: "{album_cover_path}"
      maintain_download_archive: True

    ytdl_options:
      break_on_existing: True

    audio_extract:
      codec: "mp3"
      quality: 320

    music_tags:
      tags:
        artist: "{track_artist}"
        artists: "{track_artist}"
        albumartist: "{track_artist}"
        albumartists: "{track_artist}"
        title: "{track_title}"
        album: "{track_album}"
        track: "{track_number}"
        tracktotal: "{track_total}"
        year: "{track_year}"
        genre: "{track_genre}"

    overrides:
      track_title: "{title}"
      track_album: "{title}"
      track_artist: "{channel}"
      track_number: "1"
      track_number_padded: "01"
      track_total: "1"
      track_year: "{upload_year}"
      track_genre: "Unset"
      # Filename Overrides
      track_file_name: "{track_number_padded} - {track_title_sanitized}.{ext}"
      album_file_name: "folder.{thumbnail_ext}"
      # Directory Name Overrides
      music_directory: 'C:\users\admin\music'
      artist_dir: "{track_artist_sanitized}"
      album_dir: "[{track_year}] {track_album_sanitized}"
      # Full Filepath Overrides
      track_full_path: "{artist_dir}/{album_dir}/{track_file_name}"
      album_cover_path: "{artist_dir}/{album_dir}/{album_file_name}"

####################################################################################################

  single:
    preset: "base"

    download:
      download_strategy: "url"
      url: "{url}"

####################################################################################################

  albums_from_chapters:
    # Inherit from single
    preset: "single"

    chapters:
      embed_chapters: True
      allow_chapters_from_comments: True

    split_by_chapters:
      when_no_chapters: "pass"

    # Override various track properties using chapter variables.
    overrides:
      track_title: "{chapter_title}"   # Chapter title is the track title
      track_album: "{title}"           # Video's title is the album title
      track_number: "{chapter_index}"
      track_number_padded: "{chapter_index_padded}"
      track_total: "{chapter_count}"
```
