### DISCUSSION TITLE
Yaml Files Not Found [Running Docker on Synology via Container Manager]

### DISCUSSION THREAD

**Discussion by drinksomewhiskey** [jmbannon/ytdl-sub#854] [Q&A]
Hi All,

I successfully set up ytdl-sub via docker compose within Container Manager based on the following code:

```
services:
  ytdl-sub:
    image: ghcr.io/jmbannon/ytdl-sub-gui:latest
    container_name: ytdl-sub
    environment:
      - PUID=XXXX
      - PGID=XXXX
      - TZ=XXXXX/XXXXXXXXX
    volumes:
      - /volume1/docker/ytdl-sub:/config
      - /volume1/Libraries/Downloads/ytdl-sub/TV:/tv_shows  # optional
      - /volume1/Libraries/Downloads/ytdl-sub/Movies:/movies  # optional
      - /volume1/Libraries/Downloads/ytdl-sub/Music Videos:/music_videos  # optional
      - /volume1/Libraries/Downloads/ytdl-sub/Music:/music  # optional
    ports:
      - 8444:8443
    restart: unless-stopped
```

I had to change the local port from `8443` to `8444` as `8443` was already being used for something else however, I left the container port at the default `8443`.

Aside from this, I defined my volume directories accordingly as noted above.

This successfully set up the gui and I was able to pull it up at `http://localhost:8444/`. I got to VS Code and I see the `YTDL-SUB-Configs` folder within the directory, which also houses the `examples`, `config.yaml` and `subcriptions.yaml` files/folders pre-loaded.

I then followed started following the [walk-through guide](https://github.com/jmbannon/ytdl-sub/wiki/1.-Introduction) and am trying to work through [3. Creating and Using Your First Config](https://github.com/jmbannon/ytdl-sub/wiki/3.-Creating-and-Using-Your-First-Config). I created and placed the sample `config.yaml` and `subcriptions.yaml` files in the ` /volume1/docker/ytdl-sub` directory as defined in my Docker Compose file. I then try to dry run these files using the `ytdl-sub --dry-run --config config.yaml sub subscriptions.yaml` within the docker container's terminal window and get an output stating `[ytdl-sub] The config file 'config.yaml' could not be found. Did you set --config correctly?`. 

I am wondering what I may be missing as the yaml files are not found despite being placed in the `/config` directory. Does anyone see any errors in my set up / file placements?

Thank you in advance.
