### DISCUSSION TITLE
Playlist split into diffrent albums based on year

### DISCUSSION THREAD

**Discussion by PlexSheep** [jmbannon/ytdl-sub#913] [Q&A]
I have the following part in my subscriptions (for music without video)
```yaml
YouTube Releases:                                                                                                                   
  = Eurobeat:                                                                                                                       
    "Turbo":                                                                                                                        
      download:                                                                                                                     
        - "https://www.youtube.com/playlist?list=PLRktPAG0Z4OYxnRWDJphPh11euBWSMucb"                                                
        - "https://www.youtube.com/playlist?list=PLRktPAG0Z4OaqYZbUGifSu3NpFMFQA3-g"                                                
        - "https://www.youtube.com/playlist?list=PLRktPAG0Z4OYkx5Ixu6-yh6aJen6YRRyN"   
```

It does download the separate playlist into one genre and interpret like that (finding out how to do that wasn't so easy), but the playlists/albums get split into release years, which I don't want.

```zsh
% ls
'[2018] All Eurobeat Remixes'        '[2020] Anime Eurobeat Remixes'      '[2022] Anime Eurobeat Remixes'
'[2019] All Eurobeat Remixes'        '[2020] JOJO'\''s Eurobeat Remixes'  '[2022] JOJO'\''s Eurobeat Remixes'
'[2019] Anime Eurobeat Remixes'      '[2021] Anime Eurobeat Remixes'      '[2023] Anime Eurobeat Remixes'
'[2019] JOJO'\''s Eurobeat Remixes'  '[2021] JOJO'\''s Eurobeat Remixes'  '[2023] Real Eurobeat Remixes'
```

I want them combined, so "[2018] so and so" to "[2023] so and so" in a single directory. In jellyfin, I just have multiple albums with the same name but different songs.

![Screenshot_20240128_015104](https://github.com/jmbannon/ytdl-sub/assets/58274330/d3fc692f-721e-4f80-98e5-00f0fe031425)

**How can I make it so, that the playlists get combined, regardless of which year they are from?**
