### ISSUE TITLE
Poster is not getting downloaded in Plex

### ISSUE THREAD

**Issue by ajimix** [jmbannon/ytdl-sub#1013]
These are my test files:

`config.yaml`

```yaml
configuration:
  working_directory: "/tmp/.ytdl-sub-downloads"

presets:
  "Main TV Recent":
    preset:
      - "Plex TV Show by Date"
      - "Only Recent"

    overrides:
      only_recent_date_range: "5months"
      only_recent_max_files: 2
```

`subscriptions.yaml`

```yaml
__preset__:
  overrides:
    tv_show_directory: "/plex/media/YouTube"
    music_directory: "/plex/media/Music"

Main TV Recent:
  = Documentaries:
    "Veritasium": "https://www.youtube.com/@veritasium"
```

This is what ends up being created:

```
/plex/media/YouTube
  Veritasium
    Season 2024
      s2024.e053001 - What Jumping Spiders Teach Us About Color.info.json
      s2024.e053001 - What Jumping Spiders Teach Us About Color.mp4
      s2024.e053001 - What Jumping Spiders Teach Us About Color-thumb.jpg
      s2024.e062501 - Why People Prefer More Pain.info.json
      s2024.e062501 - Why People Prefer More Pain.mp4
      s2024.e062501 - Why People Prefer More Pain-thumb.jpg
```

I tried with different channels, also different kinds of configs, but I never managed to get the channel poster downloaded
