### ISSUE TITLE
Remove items that are not in a playlist anymore

### ISSUE THREAD

**Issue by Kwbmm** [jmbannon/ytdl-sub#1038]
Hey,
I have a non-listed playlist that I use as a `Watch Later`. The idea is that I go on youtube, put the video I wanna watch the in playlist and ytdl-sub downloads it when it runs.

This is the config I have:

```yaml
presets:
  base_watch_later:
    preset:
      - chunk_initial_download
      - max_1080p

    chapters:
      embed_chapters: True

    ytdl_options:
      break_on_existing: False
    output_options:
      output_directory: "{tv_show_directory}"
      file_name: "{tv_show_directory}/{channel}/{title_sanitized}.{ext}"
      thumbnail_name: "{tv_show_directory}/{channel}/{title_sanitized}.{thumbnail_ext}"
      info_json_name: "{tv_show_directory}/{channel}/{title_sanitized}.{info_json_ext}"
      maintain_download_archive: True
```

And this is the subscription file (a.k.a `watch_later.yaml`):
```yaml
__preset__:
  overrides:
      tv_show_directory: "/my/home/Watch Later"

Watch Later:
  preset:
    - "base_watch_later"
    - "no_shorts"
    - "sponsorblock"
    - "add_subs"
  download:
    url: "https://youtube.com/playlist?list=XYZ"
```

This works as I want because it splits the files in the playlist by their channel name.

The problem though is that I would like to keep the playlist on youtube and the ytdl-sub playlist in sync. When I remove a file from the youtube playlist, I would like to remove it from the `.ytdl-sub-Watch Later-download-archive.json` and also remove it from it's channel.

Is this possible?
