### ISSUE TITLE
Newbie here: Nothing happens with playlists?

### ISSUE THREAD

**Issue by jcandresen** [jmbannon/ytdl-sub#1047]
Hi Folks, 

This is my docker-compose: 
```
services:
  ytdl-sub:

    container_name: "ytdl-sub"

    devices:
      - "/dev/dri:/dev/dri"

    environment:
      - "TZ=America/Edmonton"
      - "PUID=1026"
      - "PGID=100"
    image: "ghcr.io/jmbannon/ytdl-sub-gui:latest"

    ports:
      - "38443:8443/tcp"

    volumes:
      - "/mnt/ssd/docker/ytdl-sub:/config"
      - "NFSMediaOnSynology:/data

version: "3.6"

volumes:
  NFSMediaOnSynology:
    external: true

```

This is my config file:

```
configuration:
  working_directory: ".ytdl-sub-working-directory"
  persist_logs:
    logs_directory: "/data/Youtube/ytdl-sub/logs"

```

This is my subscription file:
```
__preset__:
  overrides:
    tv_show_directory: "/data/Youtube/ytdl-sub/tv_shows"
    music_directory: "/data/Youtube/ytdl-sub/music"
    music_video_directory: "/data/Youtube/ytdl-sub/music_videos"

  ytdl_options:
    cookiefile: "/config/cookie.txt"
    verbose: true
    break_on_existing: false

  #############################################################################
  best_video_quality:
    format: "bestvideo+bestaudio/best"
    ytdl_options:
      merge_output_format: "mp4"

  "Best Video Quality":
    preset: 
      - best_video_quality

###################################################################
Plex TV Show by Date:
  = Mostly Walking:
    # Game: King's Quest (2015) as Season 1
    "~Mostly Walking":
      s01_name: "Season 1 - King's Quest (2015)"
      s01_url: "https://www.youtube.com/playlist?list=PLgmCLtUkEutKxMaHv8R3D-Nd6UGM39X3K"

    # Game: King's Quest V as Season 2
    "~Mostly Walking":
      s02_name: "Season 2 - King's Quest V"
      s02_url: "https://www.youtube.com/playlist?list=PLgmCLtUkEutKKUrcrO98zKEi3DTIzsTVr"

    # Game: King's Quest VI as Season 3
    "~Mostly Walking":
      s03_name: "Season 3 - King's Quest VI"
      s03_url: "https://www.youtube.com/playlist?list=PLgmCLtUkEutJ79cqTN3s9F8uP8eaHE4Q3"

    # Game: The Dig as Season 4
    "~Mostly Walking":
      s04_name: "Season 4 - The Dig"
      s04_url: "https://www.youtube.com/playlist?list=PLgmCLtUkEutKJXcBebjmYyiSjX1tH2IM0"

    # Game: Unavowed as Season 5
    "~Mostly Walking":
      s05_name: "Season 5 - Unavowed"
      s05_url: "https://www.youtube.com/playlist?list=PLgmCLtUkEutK7-8lHMR_kzSw4QFzOb32Y"

```
When I run  `ytdl-sub -l debug sub` I get the following output: 
[2024-09-08-150346.mostly_walking.success.log](https://github.com/user-attachments/files/16923686/2024-09-08-150346.mostly_walking.success.log)

Can you point a newbie in the correct direction?
