### ISSUE TITLE
Add the ability to download past live streams

### ISSUE THREAD

**Issue by JohnGrosshans** [jmbannon/ytdl-sub#1055]
Add the ability to have subscribed channels' shared past lives streams. Currently, channels will only download posted videos and past live streams are ignored. The ability to have a parameter to as well or only pull past live streams would be greatly helpful for some channels that are primarily live stream channels.

**Comment by jmbannon** [comment]
This should be possible via multiple urls, i.e.
```
Kodi TV Show by Date:
  "GameChops":
    - "https://www.youtube.com/@gamechops/"
    - "https://www.youtube.com/@gamechops/streams"
```

**Comment by jmbannon** [comment]
I think the default yt-dlp behavior is to ignore the streams tab when specifying a channel URL

**Comment by corvus-ch** [comment]
The proposed solution of explicitly adding the streams URL, does not work for me.

Could this be related to #738? I interpret this in that this filter is what excludes those videos. Overriding this either does not work, or I did something wrong in my config. So here it is:

```yaml
presets:
  base:
    match_filters:
      filters:
        - "!is_live & !is_upcoming & post_live"

  TV Show:
    preset:
      - "Only Recent"
      - "Jellyfin TV Show by Date"
      - "base"
```

and 

```yaml
TV Show:
  = MyTag:
    "My Channel":
      - "https://www.youtube.com/@MyChannel"
      - "https://www.youtube.com/@MyChannel/streams"
```

**Comment by jmbannon** [comment]
I don't think so @corvus-ch because those are only filtering ones that are actively live, upcoming, or post live (which means processing right afterward). Can you run with `--log-level debug` and provide the output here, that may tell us what is happening

**Comment by corvus-ch** [comment]
You are right. I messed up something different. I am running ytdl-sub within a container. It turns out, my container runtime had DNS resolution issues. This did result in nothing getting downloaded at all without any errors showing up in the output.

But I can confirm no, that adding the base URL and the streams URL results in the past lives streams being downloaded.

This is the config I used for testing.

```yaml
presets:
  TV Show:
    preset:
      - "Only Recent"
      - "Jellyfin TV Show by Date"
```

```yaml
TV Show:
  = MyTag:
    "My Channel":
      - "https://www.youtube.com/@MyChannel"
      - "https://www.youtube.com/@MyChannel/streams"
```

So, I do not see the need to change anything on the software itself. However, I believe this needs to be added to the documentation to prevent this from cumming up again.
