### ISSUE TITLE
Is it possible to pass `--parse-metadata` argument to ytdl_options?

### ISSUE THREAD

**Issue by ammgws** [jmbannon/ytdl-sub#1070]
Use-case: some channels have overly long descriptions that make browsing harder in Jellyfin, so I want to either truncate or discard descriptions entirely.

With yt-dlp I could use something like `yt-dlp --parse-metadata ":(?P<meta_description>)"` to remove the field, however it seems to me that it may not possible via how `ytdl_options` currently works, at least according to https://github.com/yt-dlp/yt-dlp/issues/3546

Or otherwise is there another way I could achieve the goal of shortening/removing the description field?

-----------

EDIT: I've gotten somewhat close with this inside my preset:
```
    nfo_tags:
      nfo_name: "{season_directory_name_sanitized}/{episode_file_name_sanitized}.nfo"
      nfo_root: "episodedetails"
      tags:
        aired: "{upload_date_standardized}"
        episode: "{upload_month}{upload_day_padded}"
        plot: "{custom_description}"
        season: "{upload_year}"
        title: "{title}"
        year: "{upload_year}"

    overrides:
      custom_description: >-
        {
          %slice( description, 0, 200 )
        }
```

ideally I just want to override the description field and not specify all the default nfo options
