### ISSUE TITLE
Help with multiple exclude terms

### ISSUE THREAD

**Issue by vodium-vastro** [jmbannon/ytdl-sub#1122]
Apologies, brand new to ytdlp-sub. I'm trying to test with downloading a subset of Youtube videos. I have the following:

config.yml

```yml
configuration:
  working_directory: ".ytdl-sub-working-directory"

presets:
  Jellyfin TV Show by Date Temporary:
    preset:
      - "Jellyfin TV Show by Date"
      - "Only Recent"

    overrides:
      tv_show_directory: "/youtube-temp"
      only_recent_date_range: "2weeks"

  Maple Leafs Highlights:
    preset: 
      - "Jellyfin TV Show by Date Temporary"
    overrides:
      filter_exclude:
          - >-
            {
              %and(
                %contains(%lower(title), 'maple leafs' ),
                %contains(%lower(title), 'highlights')
              )
            }
```

subsciptions.yml
```yml
__preset__:
  overrides:
    tv_show_directory: "/tv_shows"
    music_directory: "/music"

Maple Leafs Highlights:
  = Maple Leafs:
    "NHL - Maple Leafs Highlights": "https://www.youtube.com/@NHL"
```

When I run a dry-run all I see is:

```
[ytdl-sub] 
No files changed for NHL - Maple Leafs Highlights
[ytdl-sub] Download Summary:
NHL - Maple Leafs Highlights     0 0 0      0 ✔
Total: 1                         0 0 0     0 Success
```

Have I come at it at the completely wrong way?

Thanks
