### ISSUE TITLE
Poster.jpg and fanart.jpg not downloaded

### ISSUE THREAD

**Issue by karlic** [jmbannon/ytdl-sub#1131]
Version ytdl-sub 2024.11.06+0f542ac isn't downloading poster and fanart. 

Tried log level debug and can't see any reason there.

cat YT_subs.yaml shows:

```
# This example downloads the entirety of a channel (not limited to YouTube).
# Files will be stored in the form of:
#
#   /tv_shows
#       /Season 2021
#           s2021.e031701 - Pattys Day Video-thumb.jpg
#           s2021.e031701 - Pattys Day Video.mp4
#           s2021.e031701 - Pattys Day Video.nfo
#           s2021.e031702 - Second Pattys Day Video-thumb.jpg
#           s2021.e031702 - Second Pattys Day Video.mp4
#           s2021.e031702 - Second Pattys Day Video.nfo
#       /Season 2022
#           s2022.e122501 - Merry Christmas-thumb.jpg
#           s2022.e122501 - Merry Christmas.mp4
#           s2022.e122501 - Merry Christmas.nfo
#       poster.jpg
#       fanart.jpg
#       tvshow.nfo
#
# The idea is to use dates as numerics to represent season and episode numbers.

# Overrides to the prebuilt presets
__preset__:
  overrides:
    tv_show_directory: "/mnt/Emby/YouTube"  # Root folder of all ytdl-sub TV Shows
    # For 'Only Recent' preset, only keep vids within this range and limit
    only_recent_date_range: "1weeks"
    only_recent_max_files: 3
    environment:
      - PUID=999
      - PGID=10000
  
  # Pass any arg directly to yt-dlp's Python API
  ytdl_options:
    max_downloads: 8
    cookiefile: "cookie.txt" 
    format: "bestvideo[VCODEC=avc1]+bestaudio[ACODEC=mp4a]/mp4"
    postprocessors:
      - key: "SponsorBlock"
        when: "pre_process"
        categories:
          - "outro"
          - "selfpromo"
          - "preview"
          - "interaction"
          - "sponsor"
          - "music_offtopic"
          - "intro"
      - key: "ModifyChapters"
        remove_sponsor_segments:
          - "outro"
          - "selfpromo"
          - "preview"
          - "interaction"
          - "sponsor"
          - "music_offtopic"
          - "intro"
      - key: "FFmpegMetadata"
        add_chapters: true
        add_metadata: false

# Choose the player you intend to use by setting the top-level key to be either:
#   - Plex TV Show by Date:
#   - Jellyfin TV Show by Date:
#   - Kodi TV Show by Date:
Jellyfin TV Show by Date | max_1080p:

  # Sets genre tag to "Sailing"
  = Sailing | Only Recent:
    "Sailing Magic Carpet": "https://www.youtube.com/@SailingMagicCarpet"
    "Sailing Fair Isle": "https://www.youtube.com/@svfairisle"

  # Sets genre tag to "Narrowboats"
  = Narrowboats | Only Recent:
    "Holly The Cafe Boat": "https://www.youtube.com/@HollyTheCafeBoat"
    "Floating Our Boat": "https://www.youtube.com/@FloatingOurBoat"
    "Ben and Emily": "https://www.youtube.com/@BenandEmily"

  # Sets genre tag to "Generic"
  = Generic | Only Recent:
    "George Dunnett": "https://www.youtube.com/@Patchy"


```
