### ISSUE TITLE
Important documentation section has been deleted!

### ISSUE THREAD

**Issue by andrew-wja** [jmbannon/ytdl-sub#1137]
The docs section linked to in this comment has been deleted, and there are still stale references to it in the RST docs source files. This is super important -- I don't want ytdl-sub to redownload terabytes of 4K content from Youtube! Surely this should be on by default? And the docs should not have been deleted? I eventually found out how to set this crucial setting by reading the code :cry: 

https://github.com/jmbannon/ytdl-sub/blob/master/src/ytdl_sub/config/preset_options.py#L113

It appears there is also a bug because I am using the ytdl-sub-gui:latest image and this option is not on by default, but according to the YAML parsing code it should default to `True` if not set.

### Discussed in https://github.com/jmbannon/ytdl-sub/discussions/789

<div type='discussions-op-text'>

<sup>Originally posted by **bencdll** October 31, 2023</sup>
It seems that every time I run ytdl-sub it redownloads everything. How can I make it download only new videos?</div>

**Comment by andrew-wja** [comment]
Here's my config.yaml and subscriptions.yaml: 

```yaml
configuration:
  working_directory: ".ytdl-sub-working-directory"

presets:
  TV Show:
    preset:
      - "Jellyfin TV Show by Date"
      - "Only Recent"
```

```yaml
__preset__:
  overrides:
    tv_show_directory: "/data"
    only_recent_date_range: "15years"
    only_recent_max_files: 1

Jellyfin TV Show by Date | Only Recent:

  = Reality:
    "Fireplace 4K": "https://www.youtube.com/playlist?list=PLCBpXMNymy2rZ_PFn8z63jxpxp7aOlBmI"
    "Virtual Fireplace": "https://youtube.com/playlist?list=PLEO2ywhsmOLni56qGYyLWW34yoCQ5l3Oy&feature=shared"

```
