### ISSUE TITLE
All new episodes for a given channel are being downloaded with the same file prefix e.g. s01.e00001?

### ISSUE THREAD

**Issue by sinewave** [jmbannon/ytdl-sub#1142]
Hi, I'm running into an issue with several of the playlist that I've set up to download from YouTube where all the new files that are being added or using the same episode prefix of "s01.e00001 - <file name>" so in the folder i'll have 30 different episodes that all use the same prefix?

Here's an example of the configuration for one of the subscriptions. I have roughly 10 channels that all have the same issue, others seem to work fine?

```
Diary of a CEO:
  preset:
    - "plex_tv_show_collection"
    - "season_by_collection__episode_by_playlist_index_reversed"
    - "collection_season_1"
  
  overrides:
    tv_show_name: "Diary of a CEO"
    tv_show_directory: "/media/tv_shows"
    collection_season_1_url: "https://www.youtube.com/channel/UCGq-a57w-aPwyi3pW7XLiHw"
    collection_season_1_name: "Diary of a CEO"
    episode_title: "{title}"

  ytdl_options:
    cookiefile: "/config/youtube_cookies.txt"
```

Any thoughts on what I'm doing wrong / how to fix?
