### ISSUE TITLE
Uncaught error on ytdl-sub

### ISSUE THREAD

**Issue by papjco** [jmbannon/ytdl-sub#1147]
when i run my yaml i get this message:
```
[ytdl-sub] Validating subscriptions...
[ytdl-sub] An uncaught error occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/main.py", line 29, in main
    return_code = _main()
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/main.py", line 18, in _main
    subs = ytdl_sub.cli.entrypoint.main()
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/cli/entrypoint.py", line 244, in main
    subscriptions = _download_subscriptions_from_yaml_files(
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/cli/entrypoint.py", line 107, in _download_subscriptions_from_yaml_files
    subscriptions += Subscription.from_file_path(
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/subscriptions/subscription.py", line 127, in from_file_path
    subscriptions_dicts = SubscriptionValidator(
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/subscriptions/subscription_validators.py", line 384, in subscription_dicts
    **child.subscription_dicts(global_presets_to_apply=global_presets_to_apply),
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/subscriptions/subscription_validators.py", line 82, in subscription_dicts
    output_dict["overrides"] = dict(
TypeError: 'NoneType' object is not iterable
[ytdl-sub] Version 2024.10.09+18d0d74

```

Yaml is as follows:
```
preset:
  overrides:

  only_recent_max_files: 10
  only_recent_date_range: "2weeks"
  
  tv_show_directory: "/tv_shows"

    #music_directory: "/music"

  chunk_max_downloads: 20
# filter shorts -
    #should filter out shorts and live videos \/
  match_filters:
    filters:
      #- "age_limit<?18 & like_count>?100"
      # Other common match-filters
      - "original_url!*=/shorts/ & !is_live"
      # - "availability=?public"

  ytdl_options:
      # Ignore any download related errors and continue
      ignoreerrors: True
      # Stop downloading additional metadata/videos if it
      # exists in your download archive
      break_on_existing: True
      # Path to your YouTube cookies file to download 18+ restricted content
      #cookiefile: "/movies/cookies.txt"

  #chapters:
  # Embedded Chapter Fields
  #embed_chapters: True
  #allow_chapters_from_comments: False
  #remove_chapters_regex:
   # - "Intro"
   # - "Outro"

  # Sponsorblock Fields
  #sponsorblock_categories:
   # - "outro"
   # - "selfpromo"
   # - "preview"
   # - "interaction"
   # - "sponsor"
   # - "music_offtopic"
   # - "intro"
  #remove_sponsorblock_categories: "all"
  #force_key_frames: False

  #subtitles:
  #subtitles_name: "{title_sanitized}.{lang}.{subtitles_ext}"
  #subtitles_type: "srt"
  #embed_subtitles: False
  #languages:
  #  - "en"  # supports multiple languages
  #allow_auto_generated_subtitles: False

  #filter_exclude:
  #- >-
  #  { %contains( %lower(title), '#short' ) }
  #- >-
  #  { %contains( %lower(description), '#short' ) }



Jellyfin TV Show by Date | max_1080p:

  = Politics | = TV-PG-13 | Chunk Downloads:

    "Nathaniel Abbott": "https://www.youtube.com/@NathanielAbbott"
    "John Doyle": "https://www.youtube.com/@JohnDoyle"

  = Tech | = TV-R | Chunk Downloads:

    "MattKC": "https://www.youtube.com/@MattKC"

  = Tech | = TV-PG-13 | Chunk Downloads:

    "CS Ghost Animation" : "https://www.youtube.com/@CSGhostAnimation"
    
  = Tech | = TV-PG | Only Recent:

    "betapyteag": "https://www.youtube.com/@betapyteag"
    "Guy Dupont" : "https://www.youtube.com/@GuyDupont"
    "Fully Buffered" : "https://www.youtube.com/@FullyBuffered"
    "Hugh Jeffreys": "https://www.youtube.com/@HughJeffreys"  # 300 plus vids
    #"Macho Nacho Productions": "https://www.youtube.com/@MachoNachoProductions" # 225 vids
    #"Action Retro": "https://www.youtube.com/@ActionRetro"  # 300 plus vids
    #"Mental Outlaw": "https://www.youtube.com/@MentalOutlaw" # lots of shorts
 

  = Tech | = TV-PG | Chunk Downloads:

    "DankPods": "https://www.youtube.com/@DankPods" 
    "James Channel": "https://www.youtube.com/@Games_for_James"
    "f4mi": "https://www.youtube.com/@f4micom"
    "theunrealtarik" : "https://www.youtube.com/@theunrealtarik"
    "jvscholz" : "https://www.youtube.com/@jvscholz"

  = Automotive | = TV-PG-13 | Chunk Downloads:

    "Big Time": "https://www.youtube.com/@bigtimebigtimebigtime"
    "Garbage Time": "https://www.youtube.com/@GarbageTime420"
    "Whistlin Diesel": "https://www.youtube.com/@whistlindiesel"
    "Junkyard Digs": "https://www.youtube.com/@JunkyardDigs"
    "Westen Champlin": "https://www.youtube.com/@WestenChamplin"
    
  = Automotive | = TV-PG | Chunk Downloads:

    "Chris Fix": "https://www.youtube.com/@chrisfix" # shorts + 300 plus vids

  = Comedy | = TV-R | Chunk Downloads:

    "Michael Reeves": "https://www.youtube.com/@MichaelReeves"
    "Garn": "https://www.youtube.com/@GarnComedy"
    #"Doobus Goobus": "https://www.youtube.com/@DoobusGoobus" # 213 vids   



  = Music | = TV-PG | Chunk Downloads:

    "Shama": "https://www.youtube.com/@shama4realz"

 
  
 # = Arms | = TV-PG-13:

  #  "Hoffman Tactical" : "https://odysee.com/@hoffmantactical:3"

  = Audio | = TV-R | Chunk Downloads:

    "pierogi engineering" : "https://www.youtube.com/@pierogiengineering"
               #wubba dub dub boom boom  
    "crinacle" : "https://www.youtube.com/@crin"

  = Science | = TV-PG | Chunk Downloads:

    "Stuff Made Here" : "https://www.youtube.com/@StuffMadeHere"

  = Comedy | = TV-PG | Chunk Downloads:

    "somacguffin" : "https://www.youtube.com/@somacguffin"
  # koren funny man - 400 vids + lots of shorts

  = Law | = TV-PG-13 | Chunk Downloads:

    "Audit The Audit": "https://www.youtube.com/@AuditTheAudit" # 400 vids and shorts

 # = Documentary | = TV-PG | Chunk Downloads:

  #  "fern": "https://www.youtube.com/@fern-tv"

 #  = Tech | = TV-14 | Chunk Downloads:

  #  "Betting on Alsaka": "https://www.youtube.com/@MickWhipple"

 # = Politics | = TV-PG-13 | Chunk Downloads:

 #   "Decoy Voice": "https://www.youtube.com/@DecoyVoice"
 # shorts (lots)

 # = Comedy | = TV-PG-13 | Chunk Downloads:

  #  "Laugh Over Life": "https://www.youtube.com/@LaughOverLife"
 # lots of shorts

#for playlists or the like

Kodi TV Show Collection | max_1080p:

  = Comedy | = TV-PG-13 | Chunk Downloads: 

    "~Viva La Dirt League":
      s01_name: "Bored"
      s01_url: "https://www.youtube.com/playlist?list=PLSMETuURtTXDkOm6Xx4Q-1HS8W54GrBDm"
      s02_name: "Cost of Living"
      s02_url: "https://www.youtube.com/playlist?list=PLSMETuURtTXBRroexi4HlfMzpySAKD2Jf"
```

Config is as follows:
```
# Bare-bones config. Here are some useful links to get started:
#   Walk-through Guide:  https://ytdl-sub.readthedocs.io/en/latest/guides/index.html
#   Config Examples:     https://github.com/jmbannon/ytdl-sub/tree/master/examples
#   Prebuilt Presets:    https://ytdl-sub.readthedocs.io/en/latest/prebuilt_presets/index.html
#   Config Reference:    https://ytdl-sub.readthedocs.io/en/latest/config_reference/index.html
#
# The subscriptions in `subscriptions.yaml` uses prebuilt presets which do not require
# any additions to this config. They can be downloaded using the command:
#
#   ytdl-sub --config config.yaml sub subscriptions.yaml
#
# Or dry-ran with:
#
#   ytdl-sub --dry-run --config config.yaml sub subscriptions.yaml
#
# See the documentation above on how to build your own custom presets.
#
configuration:
  working_directory: ".ytdl-sub-working-directory"
```
