### ISSUE TITLE
TV Show Collection - fail quickly if missing season-specific variables

### ISSUE THREAD

**Issue by costowell** [jmbannon/ytdl-sub#1149]
When using this config
```yaml
__preset__:
  overrides:
    tv_show_directory: "tv_shows"

Jellyfin TV Show Collection:
  = Education:
    "Ben Eater": "https://www.youtube.com/@BenEater"
```
I get the following output even thought I have never downloaded before.
```
[ytdl-sub] No config specified, using defaults.
[ytdl-sub] Validating subscriptions...
[ytdl-sub] Beginning subscription download for Ben Eater
[ytdl-sub] Subscription full yaml:
presets:
  Ben Eater:
    chapters:
      embed_chapters: true
    download:
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_1_url) }'
      variables:
        collection_season_name: '{collection_season_1_name}'
        collection_season_number: '1'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_2_url) }'
      variables:
        collection_season_name: '{collection_season_2_name}'
        collection_season_number: '2'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_3_url) }'
      variables:
        collection_season_name: '{collection_season_3_name}'
        collection_season_number: '3'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_4_url) }'
      variables:
        collection_season_name: '{collection_season_4_name}'
        collection_season_number: '4'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_5_url) }'
      variables:
        collection_season_name: '{collection_season_5_name}'
        collection_season_number: '5'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_6_url) }'
      variables:
        collection_season_name: '{collection_season_6_name}'
        collection_season_number: '6'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_7_url) }'
      variables:
        collection_season_name: '{collection_season_7_name}'
        collection_season_number: '7'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_8_url) }'
      variables:
        collection_season_name: '{collection_season_8_name}'
        collection_season_number: '8'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_9_url) }'
      variables:
        collection_season_name: '{collection_season_9_name}'
        collection_season_number: '9'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_10_url) }'
      variables:
        collection_season_name: '{collection_season_10_name}'
        collection_season_number: '10'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_11_url) }'
      variables:
        collection_season_name: '{collection_season_11_name}'
        collection_season_number: '11'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_12_url) }'
      variables:
        collection_season_name: '{collection_season_12_name}'
        collection_season_number: '12'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_13_url) }'
      variables:
        collection_season_name: '{collection_season_13_name}'
        collection_season_number: '13'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_14_url) }'
      variables:
        collection_season_name: '{collection_season_14_name}'
        collection_season_number: '14'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_15_url) }'
      variables:
        collection_season_name: '{collection_season_15_name}'
        collection_season_number: '15'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_16_url) }'
      variables:
        collection_season_name: '{collection_season_16_name}'
        collection_season_number: '16'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_17_url) }'
      variables:
        collection_season_name: '{collection_season_17_name}'
        collection_season_number: '17'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_18_url) }'
      variables:
        collection_season_name: '{collection_season_18_name}'
        collection_season_number: '18'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_19_url) }'
      variables:
        collection_season_name: '{collection_season_19_name}'
        collection_season_number: '19'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_20_url) }'
      variables:
        collection_season_name: '{collection_season_20_name}'
        collection_season_number: '20'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_21_url) }'
      variables:
        collection_season_name: '{collection_season_21_name}'
        collection_season_number: '21'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_22_url) }'
      variables:
        collection_season_name: '{collection_season_22_name}'
        collection_season_number: '22'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_23_url) }'
      variables:
        collection_season_name: '{collection_season_23_name}'
        collection_season_number: '23'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_24_url) }'
      variables:
        collection_season_name: '{collection_season_24_name}'
        collection_season_number: '24'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_25_url) }'
      variables:
        collection_season_name: '{collection_season_25_name}'
        collection_season_number: '25'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_26_url) }'
      variables:
        collection_season_name: '{collection_season_26_name}'
        collection_season_number: '26'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_27_url) }'
      variables:
        collection_season_name: '{collection_season_27_name}'
        collection_season_number: '27'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_28_url) }'
      variables:
        collection_season_name: '{collection_season_28_name}'
        collection_season_number: '28'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_29_url) }'
      variables:
        collection_season_name: '{collection_season_29_name}'
        collection_season_number: '29'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_30_url) }'
      variables:
        collection_season_name: '{collection_season_30_name}'
        collection_season_number: '30'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_31_url) }'
      variables:
        collection_season_name: '{collection_season_31_name}'
        collection_season_number: '31'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_32_url) }'
      variables:
        collection_season_name: '{collection_season_32_name}'
        collection_season_number: '32'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_33_url) }'
      variables:
        collection_season_name: '{collection_season_33_name}'
        collection_season_number: '33'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_34_url) }'
      variables:
        collection_season_name: '{collection_season_34_name}'
        collection_season_number: '34'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_35_url) }'
      variables:
        collection_season_name: '{collection_season_35_name}'
        collection_season_number: '35'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_36_url) }'
      variables:
        collection_season_name: '{collection_season_36_name}'
        collection_season_number: '36'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_37_url) }'
      variables:
        collection_season_name: '{collection_season_37_name}'
        collection_season_number: '37'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_38_url) }'
      variables:
        collection_season_name: '{collection_season_38_name}'
        collection_season_number: '38'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_39_url) }'
      variables:
        collection_season_name: '{collection_season_39_name}'
        collection_season_number: '39'
      ytdl_options:
        playlist_items: -1:0:-1
    - download_reverse: false
      url: '{ %bilateral_url(collection_season_40_url) }'
      variables:
        collection_season_name: '{collection_season_40_name}'
        collection_season_number: '40'
      ytdl_options:
        playlist_items: -1:0:-1
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      - name: '{tv_show_poster_file_name}'
        uid: avatar_uncropped
      - name: '{tv_show_fanart_file_name}'
        uid: banner_uncropped
      source_thumbnails:
      - name: '{tv_show_poster_file_name}'
        uid: avatar_uncropped
      - name: '{tv_show_fanart_file_name}'
        uid: banner_uncropped
      url: '{collection_season_1_url}'
      variables:
        collection_season_name: '{collection_season_1_name}'
        collection_season_number: '1'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_2_url}'
      variables:
        collection_season_name: '{collection_season_2_name}'
        collection_season_number: '2'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_3_url}'
      variables:
        collection_season_name: '{collection_season_3_name}'
        collection_season_number: '3'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_4_url}'
      variables:
        collection_season_name: '{collection_season_4_name}'
        collection_season_number: '4'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_5_url}'
      variables:
        collection_season_name: '{collection_season_5_name}'
        collection_season_number: '5'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_6_url}'
      variables:
        collection_season_name: '{collection_season_6_name}'
        collection_season_number: '6'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_7_url}'
      variables:
        collection_season_name: '{collection_season_7_name}'
        collection_season_number: '7'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_8_url}'
      variables:
        collection_season_name: '{collection_season_8_name}'
        collection_season_number: '8'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_9_url}'
      variables:
        collection_season_name: '{collection_season_9_name}'
        collection_season_number: '9'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_10_url}'
      variables:
        collection_season_name: '{collection_season_10_name}'
        collection_season_number: '10'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_11_url}'
      variables:
        collection_season_name: '{collection_season_11_name}'
        collection_season_number: '11'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_12_url}'
      variables:
        collection_season_name: '{collection_season_12_name}'
        collection_season_number: '12'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_13_url}'
      variables:
        collection_season_name: '{collection_season_13_name}'
        collection_season_number: '13'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_14_url}'
      variables:
        collection_season_name: '{collection_season_14_name}'
        collection_season_number: '14'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_15_url}'
      variables:
        collection_season_name: '{collection_season_15_name}'
        collection_season_number: '15'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_16_url}'
      variables:
        collection_season_name: '{collection_season_16_name}'
        collection_season_number: '16'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_17_url}'
      variables:
        collection_season_name: '{collection_season_17_name}'
        collection_season_number: '17'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_18_url}'
      variables:
        collection_season_name: '{collection_season_18_name}'
        collection_season_number: '18'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_19_url}'
      variables:
        collection_season_name: '{collection_season_19_name}'
        collection_season_number: '19'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_20_url}'
      variables:
        collection_season_name: '{collection_season_20_name}'
        collection_season_number: '20'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_21_url}'
      variables:
        collection_season_name: '{collection_season_21_name}'
        collection_season_number: '21'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_22_url}'
      variables:
        collection_season_name: '{collection_season_22_name}'
        collection_season_number: '22'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_23_url}'
      variables:
        collection_season_name: '{collection_season_23_name}'
        collection_season_number: '23'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_24_url}'
      variables:
        collection_season_name: '{collection_season_24_name}'
        collection_season_number: '24'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_25_url}'
      variables:
        collection_season_name: '{collection_season_25_name}'
        collection_season_number: '25'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_26_url}'
      variables:
        collection_season_name: '{collection_season_26_name}'
        collection_season_number: '26'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_27_url}'
      variables:
        collection_season_name: '{collection_season_27_name}'
        collection_season_number: '27'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_28_url}'
      variables:
        collection_season_name: '{collection_season_28_name}'
        collection_season_number: '28'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_29_url}'
      variables:
        collection_season_name: '{collection_season_29_name}'
        collection_season_number: '29'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_30_url}'
      variables:
        collection_season_name: '{collection_season_30_name}'
        collection_season_number: '30'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_31_url}'
      variables:
        collection_season_name: '{collection_season_31_name}'
        collection_season_number: '31'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_32_url}'
      variables:
        collection_season_name: '{collection_season_32_name}'
        collection_season_number: '32'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_33_url}'
      variables:
        collection_season_name: '{collection_season_33_name}'
        collection_season_number: '33'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_34_url}'
      variables:
        collection_season_name: '{collection_season_34_name}'
        collection_season_number: '34'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_35_url}'
      variables:
        collection_season_name: '{collection_season_35_name}'
        collection_season_number: '35'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_36_url}'
      variables:
        collection_season_name: '{collection_season_36_name}'
        collection_season_number: '36'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_37_url}'
      variables:
        collection_season_name: '{collection_season_37_name}'
        collection_season_number: '37'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_38_url}'
      variables:
        collection_season_name: '{collection_season_38_name}'
        collection_season_number: '38'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_39_url}'
      variables:
        collection_season_name: '{collection_season_39_name}'
        collection_season_number: '39'
    - playlist_thumbnails:
      - name: '{season_poster_file_name}'
        uid: latest_entry
      url: '{collection_season_40_url}'
      variables:
        collection_season_name: '{collection_season_40_name}'
        collection_season_number: '40'
    nfo_tags:
      nfo_name: '{episode_file_path}.nfo'
      nfo_root: episodedetails
      tags:
        aired: '{episode_date_standardized}'
        episode: '{episode_number}'
        genre:
        - '{tv_show_genre}'
        mpaa: '{episode_content_rating}'
        plot: '{episode_plot}'
        season: '{season_number}'
        title: '{episode_title}'
        year: '{episode_year}'
    output_directory_nfo_tags:
      nfo_name: tvshow.nfo
      nfo_root: tvshow
      tags:
        genre:
        - '{tv_show_genre}'
        mpaa: '{tv_show_content_rating}'
        namedseason:
        - attributes:
            number: '1'
          tag: '{collection_season_1_name}'
        - attributes:
            number: '2'
          tag: '{collection_season_2_name}'
        - attributes:
            number: '3'
          tag: '{collection_season_3_name}'
        - attributes:
            number: '4'
          tag: '{collection_season_4_name}'
        - attributes:
            number: '5'
          tag: '{collection_season_5_name}'
        - attributes:
            number: '6'
          tag: '{collection_season_6_name}'
        - attributes:
            number: '7'
          tag: '{collection_season_7_name}'
        - attributes:
            number: '8'
          tag: '{collection_season_8_name}'
        - attributes:
            number: '9'
          tag: '{collection_season_9_name}'
        - attributes:
            number: '10'
          tag: '{collection_season_10_name}'
        - attributes:
            number: '11'
          tag: '{collection_season_11_name}'
        - attributes:
            number: '12'
          tag: '{collection_season_12_name}'
        - attributes:
            number: '13'
          tag: '{collection_season_13_name}'
        - attributes:
            number: '14'
          tag: '{collection_season_14_name}'
        - attributes:
            number: '15'
          tag: '{collection_season_15_name}'
        - attributes:
            number: '16'
          tag: '{collection_season_16_name}'
        - attributes:
            number: '17'
          tag: '{collection_season_17_name}'
        - attributes:
            number: '18'
          tag: '{collection_season_18_name}'
        - attributes:
            number: '19'
          tag: '{collection_season_19_name}'
        - attributes:
            number: '20'
          tag: '{collection_season_20_name}'
        - attributes:
            number: '21'
          tag: '{collection_season_21_name}'
        - attributes:
            number: '22'
          tag: '{collection_season_22_name}'
        - attributes:
            number: '23'
          tag: '{collection_season_23_name}'
        - attributes:
            number: '24'
          tag: '{collection_season_24_name}'
        - attributes:
            number: '25'
          tag: '{collection_season_25_name}'
        - attributes:
            number: '26'
          tag: '{collection_season_26_name}'
        - attributes:
            number: '27'
          tag: '{collection_season_27_name}'
        - attributes:
            number: '28'
          tag: '{collection_season_28_name}'
        - attributes:
            number: '29'
          tag: '{collection_season_29_name}'
        - attributes:
            number: '30'
          tag: '{collection_season_30_name}'
        - attributes:
            number: '31'
          tag: '{collection_season_31_name}'
        - attributes:
            number: '32'
          tag: '{collection_season_32_name}'
        - attributes:
            number: '33'
          tag: '{collection_season_33_name}'
        - attributes:
            number: '34'
          tag: '{collection_season_34_name}'
        - attributes:
            number: '35'
          tag: '{collection_season_35_name}'
        - attributes:
            number: '36'
          tag: '{collection_season_36_name}'
        - attributes:
            number: '37'
          tag: '{collection_season_37_name}'
        - attributes:
            number: '38'
          tag: '{collection_season_38_name}'
        - attributes:
            number: '39'
          tag: '{collection_season_39_name}'
        - attributes:
            number: '40'
          tag: '{collection_season_40_name}'
        title: '{tv_show_name}'
    output_options:
      file_name: '{episode_file_path}.{ext}'
      info_json_name: '{episode_file_path}.{info_json_ext}'
      maintain_download_archive: true
      output_directory: '{tv_show_directory}/{tv_show_name_sanitized}'
      thumbnail_name: '{thumbnail_file_name}'
    overrides:
      '%bilateral_url': "{ \n  %if(\n    %and(\n      enable_bilateral_scraping,\n\
        \      subscription_has_download_archive,\n      %is_bilateral_url($0)\n \
        \   ),\n    $0,\n    \"\"\n  )\n}"
      '%is_bilateral_url': '{ %contains( $0, "youtube.com/playlist" ) }'
      collection_season_10_name: '{s10_name}'
      collection_season_10_url: '{s10_url}'
      collection_season_11_name: '{s11_name}'
      collection_season_11_url: '{s11_url}'
      collection_season_12_name: '{s12_name}'
      collection_season_12_url: '{s12_url}'
      collection_season_13_name: '{s13_name}'
      collection_season_13_url: '{s13_url}'
      collection_season_14_name: '{s14_name}'
      collection_season_14_url: '{s14_url}'
      collection_season_15_name: '{s15_name}'
      collection_season_15_url: '{s15_url}'
      collection_season_16_name: '{s16_name}'
      collection_season_16_url: '{s16_url}'
      collection_season_17_name: '{s17_name}'
      collection_season_17_url: '{s17_url}'
      collection_season_18_name: '{s18_name}'
      collection_season_18_url: '{s18_url}'
      collection_season_19_name: '{s19_name}'
      collection_season_19_url: '{s19_url}'
      collection_season_1_name: '{s01_name}'
      collection_season_1_url: '{s01_url}'
      collection_season_20_name: '{s20_name}'
      collection_season_20_url: '{s20_url}'
      collection_season_21_name: '{s21_name}'
      collection_season_21_url: '{s21_url}'
      collection_season_22_name: '{s22_name}'
      collection_season_22_url: '{s22_url}'
      collection_season_23_name: '{s23_name}'
      collection_season_23_url: '{s23_url}'
      collection_season_24_name: '{s24_name}'
      collection_season_24_url: '{s24_url}'
      collection_season_25_name: '{s25_name}'
      collection_season_25_url: '{s25_url}'
      collection_season_26_name: '{s26_name}'
      collection_season_26_url: '{s26_url}'
      collection_season_27_name: '{s27_name}'
      collection_season_27_url: '{s27_url}'
      collection_season_28_name: '{s28_name}'
      collection_season_28_url: '{s28_url}'
      collection_season_29_name: '{s29_name}'
      collection_season_29_url: '{s29_url}'
      collection_season_2_name: '{s02_name}'
      collection_season_2_url: '{s02_url}'
      collection_season_30_name: '{s30_name}'
      collection_season_30_url: '{s30_url}'
      collection_season_31_name: '{s31_name}'
      collection_season_31_url: '{s31_url}'
      collection_season_32_name: '{s32_name}'
      collection_season_32_url: '{s32_url}'
      collection_season_33_name: '{s33_name}'
      collection_season_33_url: '{s33_url}'
      collection_season_34_name: '{s34_name}'
      collection_season_34_url: '{s34_url}'
      collection_season_35_name: '{s35_name}'
      collection_season_35_url: '{s35_url}'
      collection_season_36_name: '{s36_name}'
      collection_season_36_url: '{s36_url}'
      collection_season_37_name: '{s37_name}'
      collection_season_37_url: '{s37_url}'
      collection_season_38_name: '{s38_name}'
      collection_season_38_url: '{s38_url}'
      collection_season_39_name: '{s39_name}'
      collection_season_39_url: '{s39_url}'
      collection_season_3_name: '{s03_name}'
      collection_season_3_url: '{s03_url}'
      collection_season_40_name: '{s40_name}'
      collection_season_40_url: '{s40_url}'
      collection_season_4_name: '{s04_name}'
      collection_season_4_url: '{s04_url}'
      collection_season_5_name: '{s05_name}'
      collection_season_5_url: '{s05_url}'
      collection_season_6_name: '{s06_name}'
      collection_season_6_url: '{s06_url}'
      collection_season_7_name: '{s07_name}'
      collection_season_7_url: '{s07_url}'
      collection_season_8_name: '{s08_name}'
      collection_season_8_url: '{s08_url}'
      collection_season_9_name: '{s09_name}'
      collection_season_9_url: '{s09_url}'
      collection_season_number_padded: '{ %pad_zero(%int(collection_season_number),
        2) }'
      enable_bilateral_scraping: true
      episode_content_rating: '{tv_show_content_rating}'
      episode_date_standardized: '{upload_date_standardized}'
      episode_file_name: s{season_number_padded}.e{episode_number_padded} - {file_title}
      episode_file_path: '{season_directory_name_sanitized}/{episode_file_name_sanitized}'
      episode_number: '{upload_year_truncated}{upload_month_padded}{upload_day_padded}{upload_date_index_padded}'
      episode_number_padded: '{episode_number}'
      episode_plot: '{webpage_url}


        {description}'
      episode_title: '{upload_date_standardized} - {title}'
      episode_year: '{upload_year}'
      file_title: '{title_sanitized}'
      file_uid: '{uid_sanitized}'
      s01_name: ''
      s01_url: ''
      s02_name: ''
      s02_url: ''
      s03_name: ''
      s03_url: ''
      s04_name: ''
      s04_url: ''
      s05_name: ''
      s05_url: ''
      s06_name: ''
      s06_url: ''
      s07_name: ''
      s07_url: ''
      s08_name: ''
      s08_url: ''
      s09_name: ''
      s09_url: ''
      s10_name: ''
      s10_url: ''
      s11_name: ''
      s11_url: ''
      s12_name: ''
      s12_url: ''
      s13_name: ''
      s13_url: ''
      s14_name: ''
      s14_url: ''
      s15_name: ''
      s15_url: ''
      s16_name: ''
      s16_url: ''
      s17_name: ''
      s17_url: ''
      s18_name: ''
      s18_url: ''
      s19_name: ''
      s19_url: ''
      s20_name: ''
      s20_url: ''
      s21_name: ''
      s21_url: ''
      s22_name: ''
      s22_url: ''
      s23_name: ''
      s23_url: ''
      s24_name: ''
      s24_url: ''
      s25_name: ''
      s25_url: ''
      s26_name: ''
      s26_url: ''
      s27_name: ''
      s27_url: ''
      s28_name: ''
      s28_url: ''
      s29_name: ''
      s29_url: ''
      s30_name: ''
      s30_url: ''
      s31_name: ''
      s31_url: ''
      s32_name: ''
      s32_url: ''
      s33_name: ''
      s33_url: ''
      s34_name: ''
      s34_url: ''
      s35_name: ''
      s35_url: ''
      s36_name: ''
      s36_url: ''
      s37_name: ''
      s37_url: ''
      s38_name: ''
      s38_url: ''
      s39_name: ''
      s39_url: ''
      s40_name: ''
      s40_url: ''
      season_directory_name: Season {season_number_padded}
      season_number: '{collection_season_number}'
      season_number_padded: '{collection_season_number_padded}'
      season_poster_file_name: season{season_number_padded}-poster.jpg
      subscription_array: '{%from_json(''''''["https://www.youtube.com/c/BenEater"]'''''')}'
      subscription_indent_1: Education
      subscription_indent_2: '{tv_show_content_rating_default}'
      subscription_value: https://www.youtube.com/c/BenEater
      subscription_value_1: https://www.youtube.com/c/BenEater
      thumbnail_file_name: '{episode_file_path}-thumb.jpg'
      tv_show_content_rating: '{subscription_indent_2}'
      tv_show_content_rating_default: TV-14
      tv_show_directory: /tv_shows
      tv_show_fanart_file_name: fanart.jpg
      tv_show_genre: '{subscription_indent_1}'
      tv_show_genre_default: ytdl-sub
      tv_show_name: '{subscription_name}'
      tv_show_poster_file_name: poster.jpg
    preset:
    - _base
    - _episode_base
    - _episode_video_tags
    - _episode_nfo_tags
    - _url_bilateral_overrides
    - _tv_show_collection_bilateral
    - _jellyfin_tv_show
    - _tv_show_collection
    - jellyfin_tv_show_collection
    - season_by_collection__episode_by_year_month_day
    - Jellyfin TV Show Collection
    - __preset__
    video_tags:
      contentRating: '{episode_content_rating}'
      date: '{episode_date_standardized}'
      episode_id: '{episode_number}'
      genre: '{tv_show_genre}'
      show: '{tv_show_name}'
      synopsis: '{episode_plot}'
      title: '{episode_title}'
      year: '{episode_year}'
    ytdl_options:
      break_on_existing: true

[ytdl-sub:ytdl-options] Setting match-filters:
 - !is_live & !is_upcoming & !post_live
[ytdl-sub:ytdl-options] Setting breaking-match-filters: []
[ytdl-sub]
No files changed for Ben Eater
[ytdl-sub] Download Summary:
Ben Eater     0 0 0     0 ✔
Total: 1      0 0 0     0 Success
```
When switching `Jellyfin TV Show Collection` to `Jellyfin TV Show by Date` it starts to work.

This happens for versions `ytdl-sub 2024.12.14+ebe9908` and `ytdl-sub 2023.10.22+bfba4f0`.

Perhaps I need to do it how the [sample config does it](https://ytdl-sub.readthedocs.io/en/latest/prebuilt_presets/tv_shows.html#tv-show-collection)? If so, in the future it A) should warn me about it so that it doesn't fail silently like this and B) be documented that you *must* specify the season.
