### ISSUE TITLE
File naming documenation

### ISSUE THREAD

**Issue by KRider92** [jmbannon/ytdl-sub#1174]
Hi all,
Just wondering about the file naming documentation... I can't seem to find it.
I would love to have my files not named in the s####.e##### format, but instead all be named "yyyy-mm-dd - title (id).extension". But I can't get this to work and as I can't find any documentation I'm at a loss right now :/

Can you please help me in getting the right parameters set in the config file?

This is my current config file:

```
###############################################################################
# Top-level configurations to apply umask and persist error logs
configuration:
  umask: "002"
  persist_logs:
    logs_directory: './logs'
    keep_successful_logs: False

presets:

  ###############################################################################
  # Set tv_show_directory here instead of in the subscriptions file
  tv_show_paths:
    overrides:
      tv_show_directory: "/folder"

  ###############################################################################
  # base preset to use on all TV Show-based subscriptions
  base:
    preset:
      - "Jellyfin TV Show by Date"  # Set intended player
      - "best_video_quality"    # prebuilt preset to get best quality
      - "tv_show_paths"
      - "season_by_year__episode_by_month_day"

    # Embed chapters into video files
    chapters:
      embed_chapters: True

    # Embed English subtitles into video files (supports more)
    subtitles:
      embed_subtitles: True
      languages:
        - "en"
        - "de"
      allow_auto_generated_subtitles: True

    # ytdl_options lets you pass any arg into yt-dlp's Python API
    ytdl_options:
      # Set the cookie file
      cookiefile: "/configs/cookie.txt"

    # For YouTube, get English metadata if multiple languages are present
    extractor_args:
      youtube:
        lang:
          - "en"
```

Whereas this is my subscriptions.yaml:
```
__preset__:
  overrides:
    chunk_max_downloads: 2

Jellyfin TV Show by Date | Chunk Downloads:
  = genre1:
    "channel1": "https://www.youtube.com/@channel1"
    "channel2": "https://www.youtube.com/@channel2"

  = genre2:
    "channel3": "https://www.youtube.com/@channel3"
    "channel4": "https://www.youtube.com/@channel4"
    "channel5": "https://www.youtube.com/user/channel5"
[...]
```
