### ISSUE TITLE
Redundant downloads with multiple URLs and "Only Recent"

### ISSUE THREAD

**Issue by Steffengra** [jmbannon/ytdl-sub#1176]
With multiple URLs for one subscription and "Only Recent" preset some videos are redownloaded and immediately deleted.

For example:
`config.yaml`
```
configuration:
  working_directory: ".ytdl-sub-working-directory"

presets:

  add_subs:
    # Embed English subtitles into video files (supports more)
    subtitles:
      embed_subtitles: True
      languages:
        - "en"
      allow_auto_generated_subtitles: True

  YouTube Live:
    preset:
      - "Jellyfin TV Show by Date"
      - "add_subs"
      - "Only Recent"

    overrides:
      tv_show_directory: "/youtube"
      episode_title: "{title}"
```
`subscriptions.yaml`
```

__preset__:

  overrides:

    # For 'Only Recent' preset, only keep vids within this range and limit
    only_recent_date_range: "3months"
    only_recent_max_files: 20

  # Pass any arg directly to yt-dlp's Python API
  ytdl_options:

    cookiefile: "/config/cookie.txt"

YouTube Live:

  = Other | Max 1080p:
    "Level1Techs":
      - "https://www.youtube.com/@Level1Techs"
      - "https://www.youtube.com/@Level1Techs/streams"
      - "https://www.youtube.com/@Level1Linux"

```
At the moment, both `@Level1Linux` and `@Level1Techs/streams` have videos that qualify for `only_recent_date_range: "3months"`, but `@Level1Techs` alone has > 20 videos that are more recent. So every time ytdl-sub runs, the videos from  `@Level1Linux` and `@Level1Techs/streams`  are downloaded, and then immediately removed at the end of the run. Is this misconfiguration on my part?
