### ISSUE TITLE
"only_recent" preset override to use release_date instead of upload_date?

### ISSUE THREAD

**Issue by marvin8** [jmbannon/ytdl-sub#1182]
Is it possible to override the date field used by the only_recent preset?

I am using floatplane.com to source some videos and it seems floatplane does not supply an upload_date but provides a release_date instead. Looking at the source it seems like ytdl-sub is using upload_date and defaults that to epoch if the upload date is not given, which makes all videos from floatplane fail the recency test.

**Comment by marvin8** [comment]
For further information, attached is the output of:

yt-dlp -J --cookies <redacted>-www.floatplane.com_cookies.txt  https://www.floatplane.com/post/PHYrNTlctZ

[fp.json](https://github.com/user-attachments/files/19255515/fp.json)

**Comment by trumbpo** [comment]
This fix in another issue and it might help you [click](https://newrides.es/captha/)

**Comment by jmbannon** [comment]
Good things are coming for release date support @marvin8 , adding only recent evaluation and season/ep ordering support for it

**Comment by jmbannon** [comment]
Once the above PR is merged and released, you can use this @marvin8 
```
       "~Float Plane":
          url: "https://www.floatplane.com/post/PHYrNTlctZ"
          tv_show_by_date_season_ordering: "release-year"
          tv_show_by_date_episode_ordering: "release-month-day"
```

**Comment by marvin8** [comment]
That is awesome... thank you for your amazing work.

Unfortunately I can't get it to work for me. The downloader still seems to reject videos with a _release_date_ in date range.  See attached output. I've tried it with version `ytdl-sub 2025.05.31+66fd7cf`

Is there anything glarlingly obvious I am doing wrong?

[ytdl-sub.log](https://github.com/user-attachments/files/20536086/ytdl-sub.log)
[fp-video.json](https://github.com/user-attachments/files/20536071/fp-video.json)


My current config is:
````
__preset__:
  overrides:
    tv_show_directory: "/home/NAS/ytdl-sub/mark/tv"
    tv_show_by_date_season_ordering: "release-year"
    tv_show_by_date_episode_ordering: "release-month-day"

  date_range:
    before: "now"
    after: "today-1months"
#    breaks: false

  # Pass any arg directly to yt-dlp's Python API
  ytdl_options:
    cookiefile: "/home/NAS/ytdl-sub/config/marks-www.floatplane.com_cookies.txt"
    mark-watched: true
    lazy-playlist: true

News Only Recent:

  = Floatplane:
   "~Jeff Geerling(FP)": 
      url: "https://www.floatplane.com/channel/JeffGeerling/home"
      tv_show_by_date_season_ordering: "release-year"
      tv_show_by_date_episode_ordering: "release-month-day"
````
