### ISSUE TITLE
Would it be possible to add support for uploader information?

### ISSUE THREAD

**Issue by xlyralycanx** [jmbannon/ytdl-sub#1183]
When downloading metadata, a json for the uploader is generated, and some info in it is retrievable such as uploader_url. I was wondering how possible it would be to be able to call upon other tags in this file, specifically the channel 'description', 'channel_follower_count' and/or 'tags'? Or is it possible, but only when targeting the channel? Thanks for your time! Example below.

```
{
"id": "@markiplier"
"channel": "Markiplier"
"channel_id": "UC7_YxT-KID8kRbqZo7MyscQ"
"title": "Markiplier"
"channel_follower_count": 37400000
"description": "Hi, I'm Markiplier. I make videos. \n\nFrom quality content to meme-able garbage, from scary games to full-on interactive movies you'll find it all. You will, actually. I have over 5000 videos so I'm sure there's something you'd like. \n\nMaybe you like horror games, or funny games, or comedy sketches, or animations, or compilations, or reactions, or reviews, or challenges, or cryptic lore, or mind-crippling ennui, or stuff-that-is-guaranteed-to-probably-make-you-cry? Whatever you're into I'm sure there's something for you down in the briny deep of my video page. So why not dive in?\n\nOr don't. Life is yours to choose after all.\n"
"tags": ["markiplier", "comedy", "gaming", "funny videos", "funny moments", "sketch comedy", "laughing", "lets play", "challenge videos", "hilarious", "challenges", "sketches", "scary games", "funny games", "rage games", "mark fischbach"]
"uploader_id": "@markiplier"
"uploader_url": "https://www.youtube.com/@markiplier"
"playlist_count": 3
"uploader": "Markiplier"
"channel_url": "https://www.youtube.com/channel/UC7_YxT-KID8kRbqZo7MyscQ"
"_type": "playlist"
"webpage_url": "https://www.youtube.com/@markiplier"
"webpage_url_basename": "@markiplier"
}
```

**Comment by jmbannon** [comment]
Hi @xlyralycanx , any field in the info.json is accessible for use. See https://ytdl-sub.readthedocs.io/en/latest/config_reference/scripting/index.html#accessing-info-json-fields

For channel_follower_count, you can do something like
```
overrides:
  channel_follower_count: >-
   { %map_get( entry_metadata, "channel_follower_count", 0 ) }
```
Closing but happy to answer follow-up questions

**Comment by jmbannon** [comment]
In addition, `tags` can be accessed the same way, and you'll get an array. You can see array manipulations here:
https://ytdl-sub.readthedocs.io/en/latest/config_reference/scripting/scripting_functions.html#array-functions

**Comment by xlyralycanx** [comment]
Thank you!

I have just one more conundrum then, and that's how to add nfo files for channel and playlists together, instead of choosing one via output_directory_nfo_tags.

Thank you for maintaining this!

**Comment by jmbannon** [comment]
Can you elaborate @xlyralycanx  ? As in multiple URLs to a single TV show?

**Comment by xlyralycanx** [comment]
At the moment I am able to create .nfo files for each episode, and one .nfo in output_directory_nfo_tags. I can either use the latter (when downloading playlists or channels) to write 'tvshow.nfo' so Emby sees channel info, but misses playlist info, or I can write 'Season {sn)}/season.nfo' so Emby sees playlist info, but misses season info, but I haven't figured a way to write both.

The only reason I'm having this issue is because I wanted custom season names instead of numbering and must have season.nfo to do it aha

**Comment by xlyralycanx** [comment]
> At the moment I am able to create .nfo files for each episode, and one .nfo in output_directory_nfo_tags. I can either use the latter (when downloading playlists or channels) to write 'tvshow.nfo' so Emby sees channel info, but misses playlist info, or I can write 'Season {sn}/season.nfo' so Emby sees playlist info, but misses season info, but I haven't figured a way to write both.
> 
> The only reason I'm having this issue is because I wanted custom season names instead of numbering and must have season.nfo to do it aha

My config for clarity

```
  playlist:
    preset:
      - "Jellyfin TV Show by Date"
      - "default_values" #refers to some variables I made
      - "best_video_quality"
      - "sponsorblock"
    output_options:
      maintain_download_archive: True
      download_archive_name: ".ytdl-sub-{subscription_indent_2}-download-archive.json"
      output_directory: "/media/YouTube/Shared/{subscription_indent_2}"
      file_name: "Season {seasonnumber}/{subscription_indent_2} - {upload_date_standardized} - {title_sanitized_plex}.mp4"
      thumbnail_name: "Season {seasonnumber}/{subscription_indent_2} - {upload_date_standardized} - {title_sanitized_plex}-thumb.{thumbnail_ext}"
      info_json_name: "Season {seasonnumber}/{subscription_indent_2} - {upload_date_standardized} - {title_sanitized_plex}.{info_json_ext}"
    subtitles:
      subtitles_name: "Season {seasonnumber}/{subscription_indent_2} - {upload_date_standardized} - {title_sanitized_plex}.{lang}.{subtitles_ext}"
      embed_subtitles: False
      languages:
        - "en"
        - "en-orig"
      allow_auto_generated_subtitles: True
    download:
      - url: "{url}"
        playlist_thumbnails:
          - name: "season{seasonnumber}-poster.jpg"
            uid: "latest_entry"
          - name: "poster.jpg"
            uid: "avatar_uncropped"
          - name: "fanart.jpg"
            uid: "banner_uncropped"
        include_sibling_metadata: "{include_sibling_metadata}"
    video_tags:
      contentRating: "{rating}"
      date: "{upload_date_standardized}"
      episode_id: "{upload_date_standardized}"
      show: "{subscription_indent_2}"
      synopsis: "Episode from {webpage_url}\nSupport {uploader} at {uploader_url}\n\n{description}"
      title: "{title_sanitized_plex}"
      sorttitle: "{title_sanitized_plex}"
      mpaa: "{rating}"
      year: "{upload_year}"
    nfo_tags:
      nfo_name: "Season {seasonnumber}/{subscription_indent_2} - {upload_date_standardized} - {title_sanitized_plex}.nfo"
      nfo_root: "episodedetails"
      tags:
        title: "{title}"
        sorttitle: "{title_sanitized_plex}"
        season: "{seasonnumber}"
        episode: "{upload_date_standardized}"
        year: "{upload_year}"
        plot: "Episode from {webpage_url}\nSupport {uploader} at {uploader_url}\n\n{description}"
        aired: "{upload_date_standardized}"
        mpaa: "{rating}"
        genre:
          - "{genre1}"
          - "{genre2}"
          - "{genre3}"
          - "{genre4}"
    output_directory_nfo_tags:
      nfo_name: "Season {seasonnumber}/season.nfo"
      nfo_root: "season"
      tags:
        title: "{subscription_name}"
        sorttitle: "{subscription_name}"
        seasonnumber: "{seasonnumber}"
        plot: "Support {uploader} at {uploader_url}\n\n{playlist_plot}"
        release_date: "{release_date_standardized}"
        premiered: "{release_date_standardized}"
        mpaa: "{rating}"
        year: "{release_year}"
        genre:
          - "{genre1}"
          - "{genre2}"
          - "{genre3}"
    chapters:
      embed_chapters: True
    throttle_protection:
      sleep_per_download_s:
        min: 2.2
        max: 10.8
      sleep_per_subscription_s:
        min: 9.0
        max: 14.1
#      max_downloads_per_subscription:
#        min: 10
#        max: 36
    ytdl_options:
      cookiefile: "./cookies.txt"
      break_on_existing: True
```
