### ISSUE TITLE
Add channel id to output file path

### ISSUE THREAD

**Issue by wjbridge** [jmbannon/ytdl-sub#1198]
Do you have an example of how to include the channel id in the output file? I know it is realted to #984 but I cannot figure out how to include the channel id in the folder path. I need this for a jellyfin / emby plugin to extract the data based on channel id being in `[]` form in the folder itself.

I have tried to modify the `tv_show_name` and `tv_show_name_sanitized` but it keeps giving the status format error. Thanks so much...racking my brain for an hour now trying different things.

```
# Output Options
output_options:
  maintain_download_archive: True
  output_directory: '{tv_show_directory}/{tv_show_name_sanitized}'
  info_json_name: '{episode_file_path}.{info_json_ext}'
  thumbnail_name: ''
  file_name: '{episode_file_path}.{ext}'
  download_archive_name: ".{tv_show_name_sanitized}-download-archive.json"

# Overrides
overrides:
  tv_show_name: "{subscription_name} [{channel_id}]"
  tv_show_name_sanitized: "{subscription_name} [{channel_id}]"
  episode_file_name: "s{season_number_padded}.e{upload_date}_[{uid_sanitized_plex}]"
```
