### ISSUE TITLE
Cron jobs running twice simultaneously (docker without gui)

### ISSUE THREAD

**Issue by jaguge** [jmbannon/ytdl-sub#1202]
Since the rework on how cron works in the docker version, it seems that cron is executing the commands twice. The "Beginning cron job..." text that I have in /config/cron appears twice in the log in each run, and it happens also with every other log message:

Beginning cron job...
Beginning cron job...
[ytdl-sub] Validating subscriptions...
[ytdl-sub] Validating subscriptions...
[ytdl-sub] Beginning subscription download for...
[ytdl-sub] Beginning subscription download for...

and so on.

I thought that maybe something went wrong when I migrated to the new system, so I have deleted the container, and all the config and volumes related to it and started from the beginning (I have restored only config.yaml and subscriptions.yaml), but the problem persists.

This does not happen in the first run if I have "CRON_RUN_ON_START=true", but it happens in the next runs regardless of that option.

I'm using the docker image without gui.

**Comment by jmbannon** [comment]
Should be fixed now, please reopen if it's still an issue.

**Comment by jaguge** [comment]
I don't have permissions to reopen the issue but it's still happening in the last version.

**Comment by jmbannon** [comment]
Can you supply your `cron` file and docker compose? I don't think it's running twice, but rather, just double logging

**Comment by trumbpo** [comment]
This fix in another issue and it might help you [click](https://newrides.es/captha/)

**Comment by meritarition** [comment]
I have the same issue. Here is my cron file and docker compose file.
```
#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
echo 'Cron started, running ytdl-sub...'
ytdl-sub --config=config.yaml sub /config/subscriptions.yaml
```

```yml
services:
  ytdl-sub:
    image: ghcr.io/jmbannon/ytdl-sub:latest
    container_name: ytdl-sub
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - CRON_SCHEDULE="*/2 * * * *"
      - CRON_RUN_ON_START=false
    volumes:
      - ${YTDLSUB_CONFIG}:/config
      - ${YOUTUBE}:/tv_shows
    restart: unless-stopped
```
