### ISSUE TITLE
Downloading metadata takes a long time

### ISSUE THREAD

**Issue by Snuffy2** [jmbannon/ytdl-sub#1208]
It may be unavoidable or I may have my settings incorrect. 

When processing a subscription, downloading the metadata takes a long time. Sometimes up to an hour for a long playlist. I am using a date_range to only download recent files but it looks like it needs to process the metadata for the whole playlist first.

Config:
```yml
configuration:
  working_directory: '.ytdl-sub-working-directory'
  umask: '002'
  persist_logs:
    logs_directory: '/logs'
    keep_successful_logs: true

presets:
  default_playlist:
    preset:
      - 'plex_tv_show_by_date'
      - 'season_by_year__episode_by_month_day'
      - 'max_1080p'
    throttle_protection:
      sleep_per_download_s:
        min: 2.2
        max: 10.8
      sleep_per_subscription_s:
        min: 9.0
        max: 14.1
      max_downloads_per_subscription:
        min: 10
        max: 36
      subscription_download_probability: 1.0
    download:
      urls:
        - url: '{url}'
          playlist_thumbnails:
            - name: 'poster.jpg'
              uid: 'avatar_uncropped'
            - name: 'fanart.jpg'
              uid: 'banner_uncropped'
        - url: '{url2}'
          playlist_thumbnails:
            - name: 'poster.jpg'
              uid: 'avatar_uncropped'
            - name: 'fanart.jpg'
              uid: 'banner_uncropped'
    ytdl_options:
      ignoreerrors: True
      break_on_existing: False
      break_on_reject: False
    chapters:
      embed_chapters: True
      allow_chapters_from_comments: False
      sponsorblock_categories:
        - 'all'
      remove_sponsorblock_categories:
        - 'sponsor'
        - 'selfpromo'
        - 'preview'
      force_key_frames: False
    output_options:
      maintain_download_archive: True
    video_tags:
      title: '{title}'
      genre: ''
    overrides:
      episode_plot: '{description}


        {webpage_url}'
      episode_title: '{title}'
      url2: ''
    embed_thumbnail: True

  default_since_jan_2025:
    preset: default_playlist
    date_range:
      before: 'now'
      after: '20250101'
      breaks: false
```

Subscription:
```yml
__preset__:
  overrides:
    tv_show_directory: "/tv_shows"

  ytdl_options:
    cookiefile: "/config/sub_cookie.txt"
    break_on_existing: False
    break_on_reject: False

"AS Videos":
  preset:
    - default_since_jan_2025
  overrides:
    url: "https://www.youtube.com/playlist?list=PLJtitKU0CAehaZdgrPRzjyGFSEQ8URiQl"
```
