### ISSUE TITLE
Support yt-dlp's --format-sort flag

### ISSUE THREAD

**Issue by AlexGustafsson** [jmbannon/ytdl-sub#1212]
Add support for yt-dlp's `--format-sort` flag to allow for better format matching.

From yt-dlp's help:

```text
-S, --format-sort SORTORDER         Sort the formats by the fields given, see "Sorting Formats" for more
                                    details
```

Example use:

```shell
# Download the best video available with the largest resolution but no better than 480p,
# or the best video with the smallest resolution if there is no video under 480p
# Resolution is determined by using the smallest dimension.
# So this works correctly for vertical videos as well
yt-dlp -S "res:480"
```

This would allow for simple format filtering to download, for example, 1080p video as opposed to 4K video without complex expressions or knowing what formats are available beforehand.

**Comment by jmbannon** [comment]
There should be an equivalent python argument for this, which can be passed in ytdl_options.
Perhaps ytdl-sub should always call this under the hood

**Comment by AlexGustafsson** [comment]
Thanks, I assume this would work then:

```yaml
presets:
  decent_quality:
      # Download the best video available with the largest height but no larger
      # than 1080p, or the best video with the smallest resolution if there is no
      # video under 1080p
      ytdl_options:
        format_sort: res:1080
```

I'm fine by that. I don't necessarily think there needs to be an option / plugin for every thing ytdl exposes.

However, for whatever reason, that config seems to make it so ytdl-sub gets stuck on the first "Downloading metadata" step. To me that option seems to be unrelated to the metadata step, so I'm assuming I might have replaced other important options by overriding `ytdl_options`?
