### ISSUE TITLE
How to get --list-formats output included in the logs?

### ISSUE THREAD

**Issue by miangraham** [jmbannon/ytdl-sub#1226]
Hi and grats on the awesome project. I'm up and running with videos downloading successfully, but I'm trying to get some extra output in the persisted logs for debugging and monitoring purposes and having a bit of trouble. I'm not yet sure if this is a me-bug or unsupported behavior.

I tried to add available media formats to the download logs by including yt-dlp options `list-formats` and `no-simulate`. When using yt-dlp directly, it's just these two arguments as command parameters or config lines:

```
--list-formats
--no-simulate
```

Here's what I tried in the subscription yaml:

```yaml
ytdl_options:
  break_on_existing: true
  cachedir: /run/ytdl-sub/main/cache
  cookiefile: cookies.txt
  extractor_args:
    youtube:
      player_client:
      - default
      - -tv
      - web_safari
      - web_embedded
  format: bestvideo+bestaudio
  format-sort: res:1080,+codec:avc:opus
  list-formats: true
  no-simulate: true
```

And the resulting options reflected in the log:

```
[ytdl-sub:yt-dlp-downloader] ytdl_options: {'ignoreerrors': True, 'outtmpl': '/run/ytdl-sub/main/ExplainingComputers/%(i
d)S.%(ext)s', 'writethumbnail': True, 'ffmpeg_location': '/nix/store/20rmrl62qcqly9zvm64hc6d9yfws18ix-ffmpeg-7.1.1-bin/b
in/ffmpeg', 'download_archive': '/run/ytdl-sub/main/ExplainingComputers/.ytdl-sub-ExplainingComputers-download-archive.j
son-ytdl-archive', 'max_downloads': 5, 'merge_output_format': 'mp4', 'postprocessors': [{'key': 'FFmpegVideoRemuxer', 'w
hen': 'post_process', 'preferedformat': 'mp4'}, {'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}],
 'break_on_existing': True, 'cachedir': '/run/ytdl-sub/main/cache', 'cookiefile': 'cookies.txt', 'extractor_args': {'you
tube': {'player_client': ['default', '-tv', 'web_safari', 'web_embedded']}}, 'format': 'bestvideo+bestaudio', 'format-so
rt': 'res:1080,+codec:avc:opus', 'list-formats': True, 'no-simulate': True}
```

With `list-formats` and `no-simulate` in place, I'd expect a normal download with the result of `--list-formats` included in the log, as it works this way using yt-dlp directly at the command line.

What I see in the log is this:

```
[ytdl-sub:yt-dlp] [youtube] Extracting URL: https://www.youtube.com/watch?v=kN1MWBa3yiw
[ytdl-sub:yt-dlp] [youtube] kN1MWBa3yiw: Downloading webpage
[ytdl-sub:yt-dlp] [youtube] kN1MWBa3yiw: Downloading web safari player API JSON
[ytdl-sub:yt-dlp] [youtube] kN1MWBa3yiw: Downloading web embedded client config
[ytdl-sub:yt-dlp] [youtube] kN1MWBa3yiw: Downloading web embedded player API JSON
...
[ytdl-sub:yt-dlp] [youtube] kN1MWBa3yiw: Downloading m3u8 information
[ytdl-sub:yt-dlp] [info] kN1MWBa3yiw: Downloading 1 format(s): 399+251
[ytdl-sub:yt-dlp] [info] Downloading video thumbnail 45 ...
[ytdl-sub:yt-dlp] [info] Writing video thumbnail 45 to: /run/ytdl-sub/main/ExplainingComputers/kN1MWBa3yiw.webp
[ytdl-sub:yt-dlp] [download] Destination: /run/ytdl-sub/main/ExplainingComputers/kN1MWBa3yiw.f399.mp4
[ytdl-sub:yt-dlp] ^M[download]   0.0% of   43.99MiB at  Unknown B/s ETA Unknown
...
[ytdl-sub:yt-dlp] ^M[download] 100.0% of   19.64MiB at   91.20MiB/s ETA 00:00
[ytdl-sub:yt-dlp] ^M[download] 100% of   19.64MiB in 00:00:00 at 43.99MiB/s
[ytdl-sub:yt-dlp] [Merger] Merging formats into "/run/ytdl-sub/main/ExplainingComputers/kN1MWBa3yiw.mp4"
```

The download's fine, but `--list-formats` doesn't seem to be having any effect. If it works, it adds a pretty table in `[info]`. Did the added arguments not make it through to the yt-dlp command? It feels like they got misplaced.

I'd appreciate any debugging suggestions, or ideas on whether I'm doing this wrong rather than running into an in-built limitation of some sort. Thanks in advance.

**Comment by miangraham** [comment]
Problem solved by reading the suggested docstring which [the docs already pointed out](https://ytdl-sub.readthedocs.io/en/latest/config_reference/plugins.html#ytdl-options) but I missed while rushing to the example config. Changing `ytdl_options` to match the python interface got me the expected `listformats` output and also fixed my `format_sort` option that I hadn't realized was broken.

Here are the corrected options for posterity:

```yaml
ytdl_options:
  break_on_existing: true
  cachedir: /run/ytdl-sub/main/cache
  cookiefile: cookies.txt
  extractor_args:
    youtube:
      player_client:
      - default
      - -tv
      - web_safari
      - web_embedded
  format: bestvideo+bestaudio
  format_sort:
  - res:1080
  - +codec:avc:opus
  listformats: true
  simulate: false
```

Sorry for the noise and thanks for your patience!
