### ISSUE TITLE
Sometimes downloads lower quality even though higher quality is available

### ISSUE THREAD

**Issue by nothing2obvi** [jmbannon/ytdl-sub#1241]
ytdl-sub is sometimes downloading lower quality videos even though higher quality videos are available. The following is the last subpreset in my preset, but it sometimes downloads 360p videos even though 1080p is available:

```
Files Override 4K:
    overrides:
      embed_thumbnail: True
    file_convert:
      convert_to: "mkv"
    format: "(bv*[height<=2160]+bestaudio/best[height<=2160])"
    subtitles:
      subtitles_name: "{episode_file_path}.{lang}.{subtitles_ext}"
      subtitles_type: "srt"
      embed_subtitles: False
      languages:
        - "en"
        - "fa"
        - "fr"
        - "it"
        - "ko"
        - "ja"
        - "es"
        - "tl"
        - "zh"
      allow_auto_generated_subtitles: True
    nfo_tags:
      tags:
        plot: "{description}\n\n{webpage_url}"
    ytdl_options:
      cookiefile: "/config/cookies.txt"
```

We discussed this on Discord and it appears to be due to throttling. In regards to the `.json`, you said that "format looks promising but will require some parsing."

**Comment by jmbannon** [comment]
Recapping on my idea discussed in discord: we can parse the downloaded video's resolution and see if it meets a certain criteria. If it does not (i.e. require >=1080, get 360), throw an error to stop additional downloads and discard the downloaded 360p video.

I believe this is a new way for YT to throttle

**Comment by smoobandit** [comment]
Just wanting to flag that I also have this issue.  For me it always seems to the the one youtube channel that is limited to 360p.

`https://www.youtube.com/channel/UCicSZTMCesYkoNgkGhn2KFA`

Seems to have started between 8th and 11th June.

**Comment by jmbannon** [comment]
Good to know, I will prioritize this task next time I have ytdl-sub time

**Comment by jmbannon** [comment]
Once https://github.com/jmbannon/ytdl-sub/pull/1243 is pushed, could someone try out the following?
Simply add the override variable (adjust desired height if needed):

```
resolution_assert: >-
  {
    %assert(
      %gte( height, 1080 ),
      %concat( "Entry ", title, " does not have the expected resolution, stopping" )
    )
  }
```

If this works well I can make it an official preset

**Comment by smoobandit** [comment]
I have updated to ytdl-sub-2025.6.19.post1, but I am also an idiot, so have no idea where to put that code for testing.  My subscriptions.yaml does not have a preset section, so I thought I would create one like this:

```
__preset__:
resolution_assert: >-
  {
    %assert(
      %gte( height, 1080 ),
      %concat( "Entry ", title, " does not have the expected resolution, stopping" )
    )
  }
  
cinemasins:
[...etc...]
```

And that just got me: 

```
[ytdl-sub] Validating subscriptions...
[ytdl-sub] Validation error in subscriptions.yaml.__preset__: should be of type object.
```

So clearly I have no idea what I am doing.

**Comment by jmbannon** [comment]
```
__preset__:
  overrides:
    resolution_assert: >-
       etc
```
@smoobandit
