### ISSUE TITLE
Difficult to get subtitles working with Jellyfin

### ISSUE THREAD

**Issue by juj** [jmbannon/ytdl-sub#1246]
Hi, thanks for a great project.

I wanted to import some videos into Jellyfin, with subtitles. It took me several hours to get to a working state, so I thought I'd describe some of the unexpected challenges that I faced, in case it might be useful.

First, I copied the block from the [example in the docs](https://ytdl-sub.readthedocs.io/en/latest/config_reference/plugins.html#subtitles) into my .yml script:

```yaml
__preset__:
  overrides:
    only_recent_date_range: "7days"
    tv_show_directory: "/mnt/jellyfin/shows"

  subtitles:
    subtitles_name: "{title_sanitized}.{lang}.{subtitles_ext}"
    subtitles_type: "srt"
    embed_subtitles: False
    languages:
      - "en"  # supports multiple languages
      - "de"
    allow_auto_generated_subtitles: True

Jellyfin TV Show by Date | Only Recent Archive:
  = Documentaries:
    "Stand-up Maths": "https://www.youtube.com/@standupmaths"
    "Numberphile": "https://www.youtube.com/@numberphile"
    "root42": "https://www.youtube.com/@root42"
```

This unfortunately does not work with Jellyfin. I don't know if the example was intended to be Jellyfin specific or for some other project, though the issue is that the subtitles get downloaded in the wrong directory with respect to the shows. (they go in the parent directory from the `Season 2025` directory where shows go in)

In Jellyfin it seems that .srt subtitles must reside in the same directory next to the video .mp4 files, and the .srt files must have an identical matching file basename with the .mp4 file.

---------------------------------------------------

With manual trial and error, I was able to decipher that to match the default filename for shows, one must use `subtitles_name` form

```yaml
__preset__:
  overrides:
    only_recent_date_range: "7days"
    tv_show_directory: "/mnt/jellyfin/shows"

  subtitles:
    subtitles_name: "Season {upload_year}/s{upload_year}.e{upload_month_padded}{upload_day_padded}{upload_date_index_padded} - {title}.{subtitles_ext}"
    subtitles_type: "srt"
    embed_subtitles: False
    languages:
      - "en"
#      - "de" # doesn't work, cannot expand {lang} since filename won't match
    allow_auto_generated_subtitles: False

Jellyfin TV Show by Date | Only Recent Archive:
  = Documentaries:
    "Stand-up Maths": "https://www.youtube.com/@standupmaths"
    "Numberphile": "https://www.youtube.com/@numberphile"
    "root42": "https://www.youtube.com/@root42"
```
It would be useful  in the docs to have the default value of each field listed, that would help match subtitles_name with the default output filename.

Or, since the YAML is now known to be intended to use with Jellyfin (since user listed `Jellyfin TV Show by Date`), it seems that the only correct value (as far as I understand of Jellyfin) for `subtitles_name` would be that string, so it would be nice for specifying that to be redundant and work 'out of the box'.

This means that the `{lang}` scheme in particular doesn't seem to work with Jellyfin to have multiple subs, since the subtitles filename must match the video file name - unless there is some scheme I have missed.

---------------------------------------------------

Then another error is that the `{title}` expansion does not always match the actual video title. For example, the recent root42 channel video is downloaded as

```
s2025.e062101 - Let's Code MS DOS 0x2F： Mandelbrot Fractal.mp4
```
but with `subtitles_name: "Season {upload_year}/s{upload_year}.e{upload_month_padded}{upload_day_padded}{upload_date_index_padded} - {title}.{subtitles_ext}"`, the subtitles get a filename
```
s2025.e062101 - Let's Code MS DOS 0x2F: Mandelbrot Fractal.mp4
```
It looks like `{title}` does some kind of Unicode->ASCII normalization and won't then match the Unicode string value of the video filename, if the uploaded video had used Unicode chars.

---------------------------------------------------

Finally, I realized that by setting

```
  subtitles:
    embed_subtitles: True
    languages:
      - "en"
      - "de"
    allow_auto_generated_subtitles: True
```
multiple sub languages will work, since the subs will be embedded in the video, so the Jellyfin filename matching problem does not occur.

However there is then an unfortunate behavioral change in Jellyfin (which doesn't seem to be controllable), that the subtitles become American news broadcast style rolling closed captions that scroll in the video line by line, rather than being the usual separate full blocks of text that would appear in isolation. Not a ytdl-sub problem of course, though still interesting to note. So I'd prefer to use `embed_subtitles: False` to get the more appealing behavior, but that has the filename matching and Unicode problems, as described above.

---------------------------------------------------

Finally, by running the above YAML script, for some reason the `"Stand-up Maths": "https://www.youtube.com/@standupmaths"` channel is not downloading any subtitles, no matter if `embed_subtitles:` is set to `False` or `True`.

There are no errors logged, and viewing on YouTube, the video it downloaded - `s2025.e061701 - A simple equation that behaves weirdly - Numberphile.mp4` does display subtitles as usual.. so not completely sure what makes that video different than others where subs do work.

---------------------------------------------------

Hope these are helpful for anyone else trying to get Jellyfin sub downloads to work. Thanks again for the nice project.
