### ISSUE TITLE
Improving readability of downloaded shows in Jellyfin?

### ISSUE THREAD

**Issue by juj** [jmbannon/ytdl-sub#1247]
When downloading some videos with

```yaml
__preset__:
  overrides:
    only_recent_date_range: "7days"
    tv_show_directory: "/mnt/jellyfin/shows"

Jellyfin TV Show by Date | Only Recent Archive:
  = Documentaries:
    "Veritasium": "https://www.youtube.com/@veritasium"
    "Stand-up Maths": "https://www.youtube.com/@standupmaths"
    "Numberphile": "https://www.youtube.com/@numberphile"
    "root42": "https://www.youtube.com/@root42"
    "C++ Weekly With Jason Turner": "https://www.youtube.com/@cppweekly"
```

I get the following generated into Jellyfin:

![Image](https://github.com/user-attachments/assets/d24f59eb-1081-4a1a-8319-6f4f14336feb)

where the challenge is that the video name won't even fit into view from all the prefix.

I wonder if there might exist a way to get the show text to just contain the video name, without any `S2025:E62001 - 2025-06-19 - ` prefix?

E.g.

```
Veritasium
The Simplest Unsolved Problem in Math
```

(The `s1:e5` structure feels embarrassingly cringe and 90s warez-y)

I tried downloading the videos into Jellyfin's Movies/ directory instead, but oddly for some reason, all videos then come out as "The Making of Squid Game 2". Jellyfin seems to automatically pull metadata for each ytdl-sub downloaded video incorrectly. Maybe that's not what I'd want.

Sorry for the noise if this is a Jellyfin problem rather than a ytdl-sub problem. Does Jellyfin insist on displaying a Season/Episode structure always for TV Shows, or I wonder if there might be a way to customize this? Thanks for any insight!
