### ISSUE TITLE
"Did not get any data blocks" while writing subtitles

### ISSUE THREAD

**Issue by Icericus** [jmbannon/ytdl-sub#1249]
My ytdl-sub-setup is currently failing on multiple videos, all for the same reason.
It tries to pull subtitle data, fails, downloads the video and then fails when it tries to access the subtitle file that doesn't exist.
The error first appeared for me at 2025-06-11 on a Tom Scott video (that is now private).
The current videos in question:
https://www.youtube.com/watch?v=iuv_15Z67PE
https://www.youtube.com/watch?v=W96a8svXo14

My config.yaml:
```
configuration:
  working_directory: '/tmp/ytdl-sub-downloads'
  persist_logs:
    logs_directory: '/config/logs'
    keep_successful_logs: True

presets:

  video:
    preset:
      - "max_1080p"
    output_options:
      output_directory: "/media/Youtube"
      file_name: "{video_path}.{ext}"
      thumbnail_name: "{video_path}.{thumbnail_ext}"
      maintain_download_archive: True
    ytdl_options:
      break_on_existing: True
      rate-limit: 5M
      match_filters:
        filters:
          - "original_url!*=/shorts/ & !is_live"
#      max_downloads: 4
    overrides:
      video_name: "S{release_year_truncated}E{release_month_padded}{release_day_padded} - {title_sanitized}"
      video_type: "{channel}"
      video_folder: "Uncategorized"
      video_path: "{video_type_sanitized}/{video_folder_sanitized}/{video_name}"
    nfo_tags:
      nfo_name: "{video_path}.nfo"
      nfo_root: "episodedetails"
      tags:
        title: "{title}"
        season: "{release_year_truncated}"
        episode: "{release_month_padded}{release_day_padded}"
        year: "{release_year}"
        plot: "{webpage_url}"
        releasedate: "{release_date_standardized}"
    subtitles:
      subtitles_name: "{video_path}.{lang}.{subtitles_ext}"
      subtitles_type: "srt"
      embed_subtitles: False
      languages:
        - "en"
        - "de"
      allow_auto_generated_subtitles: False
    chapters:
      embed_chapters: True
    download:
#      download_strategy: "url"
      url: "{url}"
      playlist_thumbnails:
        - name: "{video_folder}/poster.jpg"
          uid: "avatar_uncropped"
        - name: "{video_folder}/backdrop.jpg"
          uid: "banner_uncropped"

  archive_video:
    preset:
      - "max_1080p"
    output_options:
      output_directory: "/media/Youtube"
      file_name: "{video_path}.{ext}"
      thumbnail_name: "{video_path}.{thumbnail_ext}"
      info_json_name: "{video_path}.{info_json_ext}"
      maintain_download_archive: True
    ytdl_options:
      break_on_existing: True
      rate-limit: 5M
#      max_downloads: 4
    overrides:
      video_name: "S{release_year_truncated}E{release_month_padded}{release_day_padded} - {title_sanitized}"
      video_type: "{channel}"
      video_path: "Archive/{video_type_sanitized}/{video_name}"
    nfo_tags:
      nfo_name: "{video_path}.nfo"
      nfo_root: "episodedetails"
      tags:
        title: "{title}"
        season: "{release_year_truncated}"
        episode: "{release_month_padded}{release_day_padded}"
        year: "{release_year}"
        plot: "{webpage_url}"
        releasedate: "{release_date_standardized}"
    subtitles:
      subtitles_name: "{video_path}.{lang}.{subtitles_ext}"
      subtitles_type: "srt"
      embed_subtitles: False
      languages:
        - "en"
        - "de"
    chapters:
      embed_chapters: True
    download:
#      download_strategy: "url"
      url: "{url}"
      playlist_thumbnails:
        - name: "{video_folder}/poster.jpg"
          uid: "avatar_uncropped"
        - name: "{video_folder}/backdrop.jpg"
          uid: "banner_uncropped"

  playlist:
    preset:
      - "video"
      - "chunk_initial_download"
    overrides:
      video_folder: "{playlist_title}"
    download:
#      download_strategy: "url"
      url: "{url}"
      playlist_thumbnails:
        - name: "{video_folder}/poster.jpg"
          uid: "avatar_uncropped"
        - name: "{video_folder}/backdrop.jpg"
          uid: "banner_uncropped"

  archive_playlist:
    preset:
      - "archive_video"
      - "chunk_initial_download"
    overrides:
      video_type: "{channel} - {playlist_title_sanitized}"

  recent_videos:
    preset:
      - "video"
    date_range:
      after: "now-{timelimit}"
    output_options:
      keep_files_after: "now-{timelimit}"
    overrides:
      timelimit: "2months"
      video_folder: "Recent Videos"
    download:
       playlist_thumbnails:
        - name: "poster.jpg"
          uid: "avatar_uncropped"
        - name: "banner.jpg"
          uid: "banner_uncropped"
    
  full_channel:
    preset:
      - "video"
      - "chunk_initial_download"
    overrides:
      video_folder: "All"
    download:
       playlist_thumbnails:
        - name: "poster.jpg"
          uid: "avatar_uncropped"
        - name: "banner.jpg"
          uid: "banner_uncropped"

  sponsorblock:
    chapters:
      sponsorblock_categories:
        - "outro"
        - "selfpromo"
        - "preview"
        - "interaction"
        - "sponsor"
        - "intro"
      remove_sponsorblock_categories: "all"
      force_key_frames: False
    date_range:
      before: "today-2days"
```

The relevant parts of my subscriptions.yaml:
```
worthikids_all:
  preset:
    - "full_channel"
  download: "https://www.youtube.com/@Worthikids/videos"

techconn_all:
  preset:
    - "full_channel"
  download: "https://www.youtube.com/@TechnologyConnections/videos"
```

The error file for the first video (second is the same so I only send one):
[2025-06-26-021952.worthikids_all.error.log](https://github.com/user-attachments/files/20923691/2025-06-26-021952.worthikids_all.error.log)
