### ISSUE TITLE
Recursive dl_aliases

### ISSUE THREAD

**Issue by jmbannon** [jmbannon/ytdl-sub#141]
Should be able to specify other dl_aliases in a dl_alias, i.e.

```yaml
configuration:
  working_directory: '/tmp/ytdl-sub-downloads'
  dl_aliases:
    video: "--preset yt_video"
    video-url: "--youtube.video_url"
    type: "--overrides.video_type"
    single-music-video: "--video --type 'Music Video' --video_url"
```
instead of
```yaml
configuration:
  working_directory: '/tmp/ytdl-sub-downloads'
  dl_aliases:
    video: "--preset yt_video"
    video-url: "--youtube.video_url"
    type: "--overrides.video_type"
    single-music-video: "--preset yt_video --overrides.video_type 'Music Video' --youtube.video_url"
```
