### ISSUE TITLE
Allow override variables in StringDateTimeValidator

### ISSUE THREAD

**Issue by jmbannon** [jmbannon/ytdl-sub#149]
```
  yt_channel:
    preset: "yt_playlist"
    youtube:
      download_strategy: "channel"
      after: "now-6months"
    output_options:
      keep_files_after: "now-6months"
```
Should be simplified by
```
  yt_channel:
    preset: "yt_playlist"
    youtube:
      download_strategy: "channel"
      after: "{time_range}"
    output_options:
      keep_files_after: "{time_range}"
    overrides:
      time_range: "now-6months"
```
