### ISSUE TITLE
Support for subtitles

### ISSUE THREAD

**Issue by jmbannon** [jmbannon/ytdl-sub#163]
A commonly requested feature that should be a part of the output options like thumbnail

**Comment by Code-Slave** [comment]
if added it would be nice to scan and dl missing subs too if possible

**Comment by jmbannon** [comment]
@Code-Slave agreed. This issue should handle that as well as updating other things: https://github.com/jmbannon/ytdl-sub/issues/155

**Comment by jmbannon** [comment]
Proposed config for subtitles will be:
```
    output_options:
      subtitles:
        # subtitles file
        subtitles_name: "{episode_name}.{subtitles_lang}.{subtitles_ext}"
        subtitles_type: "srt"
        # OR subtitles embedded
        embed_subtitles: True
        # options (these will be the default)
        languages: "en"  # supports list of multiple langs
        allow_automatic_subtitles: True
  ```

**Comment by jmbannon** [comment]
Implemented subtitles as a plugin actually, so the format looks like:
```
presets:
  my_preset:
    subtitles:
      # subtitles file
      subtitles_name: "{episode_name}.{subtitles_lang}.{subtitles_ext}"
      subtitles_type: "srt"
      # AND/OR subtitles embedded
      embed_subtitles: False
      # options (these will be the default)
      languages: "en"  # supports list of multiple langs or "all"
      allow_automatic_subtitles: False
```
