### ISSUE TITLE
Retrying ytdl-sub download errors

### ISSUE THREAD

**Issue by destrugter** [jmbannon/ytdl-sub#190]
When downloading longer videos, the app breaks when attempting to retry. The specific video it's failing on is about 2 hours 12 minutes long. Eventually the download speed goes down to 40 kb/s and just gives up at some point.

Log file
[ytdl-sub.vq125gz.txt](https://github.com/jmbannon/ytdl-sub/files/9387229/ytdl-sub.vq125gz.txt)

config
```
configuration:
  working_directory: '/tmp/ytdl-sub-downloads'

# All example presets are included in this default config.yaml,
# feel free to change it as you see fit. For a detailed explanation
# of the examples, see https://ytdl-sub.readthedocs.io/en/latest/examples.html
presets:

  #############################################################################
  # Downloads single videos and stores them as Kodi/Jellyfin/Emby music videos,
  # which all live in a single directory.
  yt_music_video:
    youtube:
      download_strategy: "video"

    output_options:
      output_directory: "{music_video_directory}"
      file_name: "{music_video_name}.{ext}"
      thumbnail_name: "{music_video_name}-thumb.jpg"

    nfo_tags:
      nfo_name: "{music_video_name}.nfo"
      nfo_root: "musicvideo"
      tags:
        artist: "{artist}"
        title: "{title}"
        album: "Music Videos"
        year: "{upload_year}"

    overrides:
      music_video_directory: "/music_videos"
      music_video_name: "{artist_sanitized} - {title_sanitized}"
      # artist: # FILL THIS OUT IN THE SUBSCRIPTION

  #############################################################################
  # Downloads playlists and stores all videos as Kodi/Jellyfin/Emby music
  # videos, which all live in a single directory.
  yt_music_video_playlist:
    preset: "yt_music_video"
    youtube:
      download_strategy: "playlist"

    output_options:
      maintain_download_archive: True

  yt_channel_as_tv:
    
    # Use YouTube as our source. Our strategy is download the entire channel.
    # Configure channel-specific parameters to make images appear as artwork
    youtube:
      download_strategy: "channel"
      channel_avatar_path: "poster.jpg"
      channel_banner_path: "fanart.jpg"
    
    # Define media file output options using variables
    output_options:
      output_directory: "{youtube_tv_shows_directory}/{tv_show_name_sanitized}"
      file_name: "{episode_name}.{ext}"
      thumbnail_name: "{episode_name}-thumb.jpg"
      maintain_download_archive: True
    
    # Define 'override' variables, which can contain a mix of hardcoded strings
    # and 'source' variables that are derived from the video itself.
    overrides:
      youtube_tv_shows_directory: "/tv_shows"
      episode_name: "Season {upload_year}/s{upload_year}.e{upload_month_padded}{upload_day_padded} - {title_sanitized}"
     
    # Use the 'nfo_tags' plugin to generate an NFO file for each video.
    # See the config in the `examples/` directory for a full example
    nfo_tags:
      nfo_name: "{episode_name}.nfo"
      nfo_root: "episodedetails"
      tags:
        title: "{title}"
        season: "{upload_year}"
        episode: "{upload_month}{upload_day_padded}"
        plot: "{description}"
        year: "{upload_year}"
        aired: "{upload_date_standardized}"

    # In the output directory, create a tvshow.nfo file. Kodi looks for this
    # in the root of the TV show directory to get the TV show (title) name.
    output_directory_nfo_tags:
      nfo_name: "tvshow.nfo"
      nfo_root: "tvshow"
      tags:
        title: "{tv_show_name}"

    ytdl_options:
      break_on_existing: False  # stop downloads (newest to oldest) if a video is already downloaded
```

subscriptions
```
hazel_channel:
  # Inherit all fields in the 'yt_channel_as_tv' preset
  preset: "yt_channel_as_tv"
  
  # Add the `channel_url` parameter here since it's unique for each subscription
  youtube:
    channel_url: "https://www.youtube.com/c/hazelll"
    
  # Similarly, define the {tv_show_name} variable since it's also unique to each
  # subscription.
  overrides:
    tv_show_name: "Hazel Videos"
```

command
`ytdl-sub --config=/config/config.yaml sub /config/subscriptions.yaml`
