### ISSUE TITLE
Plex configuration almost works except when multiple videos have same upload date

### ISSUE THREAD

**Issue by henryb3** [jmbannon/ytdl-sub#234]
I've teased out a working config.yaml for Plex.   The problem is that I need an additional Youtube Source Variable (like hour and/or minute) to help differentiate videos that have the same upload date.   ie: if a channel posts 2 or more videos in one day, they will end up as "versions" grouped together.  S{upload_year}E{upload_month_padded}{upload_day_padded} .  Is there another way to make the episode numbers more unique?

  Here are snippets of my preset:

#Almost got Plex happy with metadata.  Still tweaking metadata for the dates.
    video_tags:
      tags:
        track: "{title}"
        episode_id: "{title}"
        title: "{title}"
        show: "{tv_show_name}"
        year: "{upload_date_standardized}"
        creation_time: "{upload_date_standardized}"
        season_number: "{upload_year}"
        episode_sort: "{upload_month_padded}{upload_day_padded}"
        description: "{description}"
        synopsis: "{description}"

    overrides:
      youtube_tv_shows_directory: "/tv_shows"
      episode_name: "{upload_year}/{tv_show_name_sanitized} - S{upload_year}E{upload_month_padded}{upload_day_padded} - {title_sanitized}"

**Comment by jmbannon** [comment]
hour/minute/sec unfortunately are not available for scraping. I do not think there are any variables available right now to make it unique. We could add new ones likes current `time_hour`/`time_minute`/`time_second`/`time_millisecond`, then use those in the episode name.

**Comment by jmbannon** [comment]
Another question that raises though is, how large of episode numbers does plex support? If it's {upload_month_padded}{upload_day_padded}{time_hour}{time_minute}{time_second}{time_millisecond}, that's

MM-DD-HH-MM-SS-MMMM, 14 digits long

Could also try hashing the episode name into a number that's 4 digits long

(Also protip: add {upload_date_standardized} into your title for readability within plex)

**Comment by henryb3** [comment]
The length of the episode number is a good concern.  current time_hour/time_minute/time_second sound like a great solution.   The question is will those variables shift properly for each download? ie: we don't want set them to the time of invocation of ytdl-sub but for when the file is downloaded and written.

**Comment by jmbannon** [comment]
We download each video individually so it should have enough separation to be unique so long as it's set right after it's downloaded. Before I add those vars, try to see if plex will scrape that format

**Comment by henryb3** [comment]
I think I have a cleaner solution.   If there are multiple videos posted on a day in a channel, we should have an incremented variable per video.   My filename format then would be:  S{upload_year}E{upload_month_padded}{upload_day_padded} {video_num}.   {video_num} would be incremented per video on days the channel had multiple videos.  Otherwise, on a single video day, it would just stay at 01 for example.

**Comment by jmbannon** [comment]
@henryb3 The issue with that is we'd have to implement a way to maintain state of what's been downloaded in a day. Not that it can't be done, but IMO it's better to avoid adding complexity if possible.

I'll be adding a change soon to expose `playlist_index` to both YouTube channels and videos. For channels, it's indexed as `1` being the most recently uploaded video.

If you perform one download each day, then `s{upload_year}e{upload_month}{upload_day_padded}{playlist_index_padded}` should be unique.

If you want more frequent downloads, say every X hours, then we could do `s{upload_year}e{upload_month}{upload_day_padded}{current_hour_padded}{playlist_index_padded}` . But that still has a pretty big episode number :thinking:

**Comment by jmbannon** [comment]
took the plunge and downloaded plex to test out large ep numbers with success :)
```
Finished processing [anus S2010 E1111111]
```
Worked with 7 digits, that should be enough for `s{upload_year}e{upload_month_padded}{upload_day_padded}{current_hour_padded}{playlist_index}`

Will get `playlist_index` updated for channel soon

**Comment by henryb3** [comment]
@jmbannon Thanks!   I think I need to clarify what I meant by the incremented video counter.   

Example:  A youtube channel has 3 videos uploaded on August 4th, 1 on August 5th, and 2 on August 6th.   When ytdl-sub is run over that date range, it will download the metadata first for 6 videos.... so it will do 1/6, 2/6, 3/6, 4/6, 5/6, 6/6 then start downloading the videos.  The incremented video counter does not count the number of videos on the day you are downloading, it increments for the day the videos are posted.   So if ytdl-sub downloads the August 4th videos first (ie: 1/6, 2/6, 3/6) it would increment the counter for each of those (so 1, 2, 3).   When it then downloads the video for August 5th, it would reset back to 1 that counter.   Then for August 6th it would start with 1 and end with 2 on the second video.  Does that make sense?

**Comment by jmbannon** [comment]
Got it. You'd still need to maintain state within a download invocation. Plus this wouldn't apply to playlists since they can be of any order.

I think `playlist_index` will accomplish the same end-goal. The ep number won't look as pretty but regardless, I recommend putting the standardized date into the title for readability.

So with your example, and episode name of `s{upload_year}e{upload_month_padded}{upload_day_padded}{playlist_index_padded}`, you'd get:

```
s2022e080401
s2022e080402
s2022e080403
s2022e080504
s2022e080605
s2022e080606
```
The only issue I see now is, say on your first download there are 1000+ vids to download. playlist_index would always need to maintain a padding of 4 digits. Same issue applies to your approach (though highly unlikely to go above 3 digits, but I don't want to make assumptions).

Could mitigate this by making more padding playlist index variables. Your example then turns into:
```
s2022e08040001
s2022e08040002
s2022e08040003
s2022e08050004
s2022e08060005
s2022e08060006
```

**Comment by jmbannon** [comment]
+ if you want to download multiple times a day, throw the `current_hour` in there, then it becomes:
```
s2022e0804100001  # downloaded 10am Aug 4th
s2022e0804100002
s2022e0804100003
s2022e0805230001  # downloaded 11pm Aug 5th
s2022e0806050001  # downloaded 5am of Aug 6th
s2022e0806140001  # downloaded 2pm of Aug 6th
```

**Comment by henryb3** [comment]
Sounds great!  Thank you for your work on putting all these pieces together.

**Comment by nicolecomputer** [comment]
@henryb3 Can you share your working Plex config?

**Comment by henryb3** [comment]
@nicolecomputer This is what I am using.  The tags section is a bit messy. I was throwing around variables and fields to see what would stick.   I recommend downloading in mp4 formats directly because if you download and use the conversion options, it takes forever.  Also please note that if there are multiple videos on the same day, plex will treat them as versions of the same episode until @jmbannon implements his solution above.  Subtitle download and work in Plex as well.


```
configuration:
  working_directory: '.ytdl-sub-downloads'

presets:

  ###############################################################################
  # FULL ARCHIVE
  # This preset will download every single video in a YouTube channel.
  yt_channel_as_tv:
    # YouTube channels are our source/download strategy
    # Use the channel avatar and banner images for Kodi
    youtube:
      download_strategy: "channel"
      channel_avatar_path: "poster.jpg"
      channel_banner_path: "fanart.jpg"

    # For advanced YTDL users only; any YTDL parameter can be set here.
    # To download age-restricted videos, you will need to set your cookie
    # file here as a ytdl parameter. For more info, see
    # https://ytdl-sub.readthedocs.io/en/latest/faq.html#download-age-restricted-youtube-videos
    #
    # ytdl_options:
    #   cookiefile: "path/to/cookie_file.txt

    # For each video downloaded, set the file and thumbnail name here.
    # We set both with {episode_name}, which is a variable we define in
    # the overrides section further below to represent our date-like episode
    # naming convention. Using override variables helps reduce copy-paste.
    #
    # Another field worth mentioning is maintain_download_archive=True. This
    # is generally a good thing to enable with channels because it will
    # store previously downloaded video ids to tell YTDL not to re-download
    # them on a successive invocation.
    output_options:
      output_directory: "{youtube_tv_shows_directory}/{tv_show_name_sanitized}"
      file_name: "{episode_name}.{ext}"
      thumbnail_name: "{episode_name}-thumb.jpg"
      maintain_download_archive: True

    ytdl_options:
      format: "bv[ext=mp4]+ba[ext=m4a]"
      break_on_reject: False

    video_tags:
      tags:
        track: "{title}"
        episode_id: "{title}"
        title: "{title}"
        show: "{tv_show_name}"
        year: "{upload_date_standardized}"
        date: "{upload_date_standardized}"
        creation_time: "{upload_date_standardized}"
        season_number: "{upload_year}"
        episode_sort: "{upload_month_padded}{upload_day_padded}"
        description: "{description}"
        synopsis: "{description}"

    subtitles:
      subtitles_name: "{upload_year}/{tv_show_name_sanitized} - S{upload_year}E{upload_month_padded}{upload_day_padded}.{lang}.{subtitles_ext}"
      subtitles_type: "srt"
      embed_subtitles: False
      languages: "en"  # supports list of multiple languages

    # Overrides is a section where we can define our own variables, and use them in
    # any other section. We define our tv show directory and episode file name here,
    # which gets reused above for the video, thumbnail, and NFO file.
    overrides:
      youtube_tv_shows_directory: "/tv_shows"
      episode_name: "{upload_year}/{tv_show_name_sanitized} - S{upload_year}E{upload_month_padded}{upload_day_padded} - {title_sanitized}"

  ###############################################################################
  # 2022 ARCHIVE
  # This preset downloads the above year only
  yt_channel_as_tv_2022:
    preset: "yt_channel_as_tv"
    date_range:
      before: "20221231"
      after: "20220101"

 ###############################################################################
  # 2021 ARCHIVE
  # This preset downloads the above year only
  yt_channel_as_tv_2021:
    preset: "yt_channel_as_tv"
    date_range:
      before: "20211231"
      after: "20210101"

```

**Comment by Glynax** [comment]
Just thought I'd throw my two cents in. I was using YoutubeDL-Material with this configuration and it imported pretty well into plex. 
![image](https://user-images.githubusercontent.com/7043861/192081165-66f342fa-579f-47c6-a0bd-07ece8fb3fa3.png)

If you name it something like this 
![image](https://user-images.githubusercontent.com/7043861/192081340-dd5cc3b6-6efa-47ec-a7b9-0280abfd07a9.png)

you can make them show up by year in plex like this 

![image](https://user-images.githubusercontent.com/7043861/192081349-a2c5a4c5-92e0-49c1-aced-1d81cb53677a.png)

With this metadata agent and scanner (google for their githubs) 

![image](https://user-images.githubusercontent.com/7043861/192081357-5bb0fc52-7ef7-468b-a4ea-cd57a7bf13b2.png)

![image](https://user-images.githubusercontent.com/7043861/192081374-3eaf004f-5ddd-4520-93cd-4ab7e0f4385d.png)

**Comment by jmbannon** [comment]
@henryb3 [playlist_index_padded6](https://ytdl-sub.readthedocs.io/en/latest/config.html#ytdl_sub.entries.variables.youtube_variables.YoutubeVideoVariables.playlist_index_padded6) is now added, if you do downloads once a day with `s{upload_year}e{upload_month_padded}{upload_day_padded}{playlist_index_padded6}`, it should work.

**Comment by jmbannon** [comment]
@henryb3 disregard my comment above. Spent some quality time making a built-in preset for plex tv shows: https://ytdl-sub.readthedocs.io/en/latest/presets.html#tv-shows

Your config comment above really helped me get started, thanks for that! Try out this config:
```
configuration:
  working_directory: '.ytdl-sub-downloads'

presets:

  ###############################################################################
  # FULL ARCHIVE
  # This preset will download every single video in a YouTube channel.
  yt_channel_as_tv:
    preset:
      - "plex_tv_show_by_date"
      - "season_by_year__episode_by_month_day"

    ytdl_options:
      format: "bv[ext=mp4]+ba[ext=m4a]"
      break_on_reject: False

    subtitles:
      subtitles_name: "{upload_year}/{tv_show_name_sanitized} - S{upload_year}E{upload_month_padded}{upload_day_padded}.{lang}.{subtitles_ext}"
      subtitles_type: "srt"
      embed_subtitles: False
      languages: "en"  # supports list of multiple languages

    overrides:
      tv_show_directory: "/tv_shows"
      episode_plot: "{webpage_url}\n\n{description}"

  ###############################################################################
  # 2022 ARCHIVE
  # This preset downloads the above year only
  yt_channel_as_tv_2022:
    preset: "yt_channel_as_tv"
    date_range:
      before: "20221231"
      after: "20220101"

 ###############################################################################
  # 2021 ARCHIVE
  # This preset downloads the above year only
  yt_channel_as_tv_2021:
    preset: "yt_channel_as_tv"
    date_range:
      before: "20211231"
      after: "20210101"
```

**Comment by jmbannon** [comment]
your subscription should look like this:
```
pensioncraft:
  preset:
    - "yt_channel_as_tv"
  overrides:
    tv_show_name: "PensionCraft"
    url: "https://www.youtube.com/c/Pensioncraft"
```
