### ISSUE TITLE
Remove `break_on_reject` from youtube.channel default ytdl options

### ISSUE THREAD

**Issue by henryb3** [jmbannon/ytdl-sub#242]
I am attempting to create configurations to download any channel's videos by year (trying to break up my downloads into chunks) to watch my disk space and traffic. 

If you attempt to download a range of videos using a configuration similar to this in config.yaml:
  
```
 yt_channel_as_tv_2017:
    preset: "yt_channel_as_tv"
    date_range:
      before: "20171231"
      after: "20170101"
```

It will fail to download videos if the most recent channel video is not included in the range.  It will attempt to grab the first video and provide this error: "[ytdl-sub:yt-dlp] [download] 2018-11-02 upload date is not in range 2017-01-01 - 2017-12-31"   Then it will not attempt to download any other videos.   

If I adjust the before range to "20181105" it will download everything from 2018 and then all of 2017.
