### ISSUE TITLE
Downloading videos after a specified date validation error

### ISSUE THREAD

**Issue by fluffystranger** [jmbannon/ytdl-sub#243]
Hello again.
Is downloading videos after a specified date (range) unsupported anymore?
This used to work for me flawlessly but is now broken after a `docker-compose pull` today

```
# ytdl-sub --dry-run sub
[ytdl-sub] Validation error in electroboom_channel.youtube: 'electroboom_channel.youtube' contains the field 'after' which is not allowed. Allowed fields: channel_avatar_path, channel_banner_path, channel_url
```

extract from subscriptions.yaml
```
electroboom_channel:
  preset: "youtube_channel"
  youtube:
    after: "now-2days"
    channel_url: "https://www.youtube.com/c/Electroboom"
  output_options:
    keep_files_after: "now-4week"
  ytdl_options:
    format: "bestvideo[ext=mp4][width<=1920][height<=1080]+bestaudio[ext=m4a] / best[ext=mp4] / best"
  overrides:
    episode_name: "{upload_year}/{channel}/{upload_year}_{upload_month_padded}_{upload_day_padded} - {title_sanitized}"
    channel_avatar_path: "{upload_year}/{channel}/poster.jpg"
    channel_banner_path: "{upload_year}/{channel}/fanart.jpg"
```

Commenting the line fixes it, but using this was quite a useful approach for me when adding new subscription entries and downloading only e.g. the last month of the videos from said youtube channel.

Cheers!

**Comment by jmbannon** [comment]
Use the date_range plugin instead of specifying before/after in the channel. I indeed broke this, probably should have kept it backwards compatible for longer. Apologies!

**Comment by jmbannon** [comment]
More specifically, you'll want:
```
youtube:
    channel_url: "https://www.youtube.com/c/Electroboom"
  output_options:
    keep_files_after: "now-4week"
  date_range:
    after: "now-2days"
```
