### ISSUE TITLE
Add plugin for filtering media via regex

### ISSUE THREAD

**Issue by jmbannon** [jmbannon/ytdl-sub#28]
Be able to specify regex to include or exclude media by matching title name to regex

Should look like
```
my_preset:
  regex_filter:
    title:
      include:  # If one of these matches, include it
      - ".*Official Video.*"
      exclude:  # If one of these matches, exclude it
      - "sadfasdfdf"
```
