### ISSUE TITLE
Prebuilt presets: Add source description to tv show nfo description

### ISSUE THREAD

**Issue by jmbannon** [jmbannon/ytdl-sub#290]

**Comment by jmbannon** [comment]
Only Kodi can read this. Closing for now until there's more broad support

**Comment by cbunn81** [comment]
Does this mean the YouTube description for a video? Because it is already possible to add this to an NFO file for an episode. There is already [a source variable for the description](https://ytdl-sub.readthedocs.io/en/latest/config.html#ytdl_sub.entries.variables.entry_variables.EntryVariables.description). And within the [nfo_tags](https://ytdl-sub.readthedocs.io/en/latest/config.html#nfo-tags) section of the presets, you can set the description source variable to the `plot` key, which is what Kodi would be expecting. I can't speak for other applications.

Here is an example:
```yaml
    nfo_tags:
      nfo_name: "{episode_path}.nfo"
      nfo_root: "episodedetails"
      tags:
        title: "{title}"
        season: "{season}"
        episode: "{episode}"
        year: "{upload_year}"
        aired: "{upload_date_standardized}"
        plot: "{description}"
```
