### ISSUE TITLE
Conversion and other things not working

### ISSUE THREAD

**Issue by Zenderix** [jmbannon/ytdl-sub#298]
Hey there,

I've been trying to get this running but half the stuff I try straight up doesn't work.

Specifically: How do I convert files? File_converter as well as ytdl_options just do not do anything, always outputs as .webm. Sponsorblock isn't removing categories either. Can I tell yt-dlp to use a download rate limit? 

I can't figure this stuff out from the docs.

Would appreciate some help with this.

Config & Subscription below:

Config:
```
configuration:
  working_directory: '/media/tmp'
presets:
  youtube:
    file_converter:
      convert_to: "mp4"

    overrides:
      custom_file_name: "{upload_year}.{upload_month_padded}.{upload_day_padded}.{uid}"
      output_directory: "/media"
    youtube:
      download_strategy: "playlist"

    output_options:
      output_directory: "{output_directory}"
      file_name: "{custom_file_name}.{ext}"
      thumbnail_name: "{custom_file_name}.{thumbnail_ext}"

    chapters:
      sponsorblock_categories:
        - "outro"
        - "selfpromo"
        - "preview"
        - "interaction"
        - "sponsor"
        - "music_offtopic"
        - "intro"
      remove_sponsorblock_categories: "all"
      force_key_frames: False

    video_tags:
      tags:
        title: "{title}"
        date: "{upload_date}"
        description: "{description}"

    ytdl_options:
      ignoreerrors: True
      break_on_existing: True
      cookiefile: "/config/cookies.txt"
      ratelimit: "6M"

  #  ytdl_options:
  #    ignorerrors: True
  #    break_on_existing: True
  #    cookiefile: "/config/cookies.txt"
  #    ratelimit: 6M
  #    postprocessors:
  #    # Convert the videos to mkv format
  #    - key: "FFmpegVideoConvertor"
  #      when: "post_process"
  #      preferedformat: "mp4"

```

Subscriptions:
```
youtube:
  preset:
    - "jellyfin_tv_show_collection"
    - "season_by_collection__episode_by_year_month_day_reversed"
    - "collection_season_1"
  overrides:
    # required
    tv_show_name: "Youtube Videos"
    tv_show_directory: "/media/"
    collection_season_1_url: " "
    collection_season_1_name: "Videos"
    # can be modified from their default value
    episode_title: "{upload_date_standardized} - {title_sanitized}"
    episode_description: "{description}"

```

**Comment by csjoh** [comment]
I'm having the same problem - ytdl-sub always downloads webm no matter what I try. If I invoke yt-dlp manually in the docker container with the options I've used for years, running it manually, it works as expected and downloads mp4 files.

My config.yaml looks like this:

```
configuration:
  working_directory: '/tmp/ytdl-sub-downloads'

  #############################################################################
  # Download Youtube channels as TV shows
  yt_channel_as_tv:
    youtube:
      download_strategy: "channel"
      channel_avatar_path: "poster.jpg"
      channel_banner_path: "fanart.jpg"

    subtitles:
      subtitles_name: "Season {upload_year}/{tv_show_name_sanitized} - S{upload_year}E{upload_month_padded}{upload_day_padded} - {title_sanitized}.{lang}.{subtitles_ext}"
      subtitles_type: "srt"
      embed_subtitles: False
      languages: "en"
      allow_auto_generated_subtitles: True

    file_converter:
      convert_to: "mp4"

    output_options:
      output_directory: "{youtube_tv_shows_directory}/{tv_show_name_sanitized}"
      file_name: "{episode_name}.{ext}"
      thumbnail_name: "{episode_name}-thumb.jpg"

    overrides:
      youtube_tv_shows_directory: "/tv_shows"
      episode_name: "Season {upload_year}/{tv_show_name_sanitized} - S{upload_year}E{upload_month_padded}{upload_day_padded} - {title_sanitized}"

  ytdl_options:
    format: "bestvideo[height<=1080]+bestaudio[ext=m4a]/bestvideo+bestaudio/best"
    #format: "bv[height<=1080,ext=mp4]"
    cookiefile: "/config/cookies.txt"
    prefer_ffmpeg: True
    merge_output_format: "mp4"

  postprocessors:
    - key: "FFmpegVideoConverter"
      when: "post_process"
      preferedformat: "mp4"
```
I've tried both versions of the "format" line and neither of them work.

subscriptions.yaml:
```
rif_channel:
  preset: "yt_channel_as_tv"

  youtube:
    channel_url: "https://www.youtube.com/channel/UCiSx0uc5XdIYgcfIPKotc-g"

  overrides:
    tv_show_name: "RIF Podcast"
```

The combination of these two files does work apart from ytdl-sub not wanting to download anything but webm files, and not wanting to convert said webm files to anything else afterwards.

**Comment by jmbannon** [comment]
Try running with `--log-level debug` and paste it here when a webm downloads. Also could you point me to a specific vid that downloads webm? I'll try to reproduce

**Comment by jmbannon** [comment]
For sponsorblock not removing categories, you could be hitting a rate limit. yt-dlp/ytdl-sub will continue the download if so, and no sponsor segments will be cut. I'm not sure what the ytdl_options arg is for rate limiting downloads, I'll figure that out next when I have some time

**Comment by jmbannon** [comment]
I just realized the docs have `file_converter`, it should be `file_convert`. My bad lol. I just tried a few vids from RIF podcast and they were converting from webm to mp4.

A few other issues/suggestions for your guys' configs.

@Zenderix 
Your subscription is not using your `youtube` preset. You need to add that to the list of presets in the subscription. In addition, all of the file naming is taken care of in the prebuilt jellyfin tv show presets. Use this simpler config:

```
configuration:
  working_directory: '/media/tmp'
presets:
  youtube_show_single_season:
    preset:
      - "jellyfin_tv_show_collection"
      - "season_by_collection__episode_by_year_month_day_reversed"
      - "collection_season_1"
    file_convert:
      convert_to: "mp4"

    overrides:
      tv_show_directory: "/media/"
      collection_season_1_name: "Videos"
      # can be modified from their default value
      episode_title: "{upload_date_standardized} - {title_sanitized}"
      episode_description: "{description}"

    chapters:
      sponsorblock_categories:
        - "outro"
        - "selfpromo"
        - "preview"
        - "interaction"
        - "sponsor"
        - "music_offtopic"
        - "intro"
      remove_sponsorblock_categories: "all"
      force_key_frames: False

    video_tags:
      tags:
        title: "{title}"
        date: "{upload_date}"
        description: "{description}"

    ytdl_options:
      cookiefile: "/config/cookies.txt"
      ratelimit: "6M"
```
Then your subscription:
```
some_channel:
  preset:
    - "youtube_show_single_season"
  overrides:
    # required
    tv_show_name: "Youtube Videos"
    collection_season_1_url: "FILL OUT"
```
