### ISSUE TITLE
Use in both jellyfin and Plex?

### ISSUE THREAD

**Issue by psyciknz** [jmbannon/ytdl-sub#305]
I've got ytdl-sub working well for jellyfin.   Unfortunately, the jellyfin. Swiftfin tvOS client leaves. A little to be desired on my older Apple TV (so slow, pressing buttons does nothing).   So I'd like to expose the same library to Plex. 

What can I add to the configs so that Plex can get the metadata - since they were fairly useless at nfo and other local metadata support.   

That's for the great program though.   I've moved from a podsync implementation.

**Comment by psyciknz** [comment]
Ahh...don't mind me.   I thought about it before I tried it.  

I just pointed Plex at the ytd-sub folder and all the images, videos have all worked.  Do you embed the details in an mp4?  Bravo!!

**Comment by jmbannon** [comment]
Follow this guide: https://ytdl-sub.readthedocs.io/en/latest/presets.html#tv-shows
And specify both plex + jellyfin tv show presets in your config

**Comment by jmbannon** [comment]
And yes by specifying both plex + jellyfin it will both embed details in the mp4 + make nfo files

**Comment by psyciknz** [comment]
The docs did confuse me a little.   In read the docs.   You have multiple presets and on a subscription you add more or o e of them.  But don't necessarily have some of the YouTube settings. 

But then In the main read me you can have examples with only o e preset.   But it specifies YouTube settings.

**Comment by jmbannon** [comment]
Ya sorry for the confusion, need to update the docs. Presets (and anything list-based) can either enter a single value OR a list within the yaml, i.e.

```
preset: "jellyfin_tv_show_by_date"
```
and
```
preset:
  - "jellyfin_tv_show_by_date"
```
are equivalent.

For your preset, do something like
```
tv_show:
  preset:
    - "jellyfin_tv_show_by_date"
    - "plex_tv_show_by_date"
```

**Comment by psyciknz** [comment]
I couldn't figure out these settings.

youtube:
      download_strategy: "channel"
      channel_avatar_path: "poster.jpg"
      channel_banner_path: "fanart.jpg"

In the read the docs structure.   This in I my config.yaml under
Preset:
  Tv_show:

I needed This as if I added just the channel banner etc (it complained about YouTube) then the tv show .jpg was overwrites but the episode thumbnail

**Comment by jmbannon** [comment]
@psyciknz 
Use this example config and subscriptions:

https://github.com/jmbannon/ytdl-sub/blob/master/examples/tv_show_config.yaml
https://github.com/jmbannon/ytdl-sub/blob/master/examples/tv_show_subscriptions.yaml

**Comment by psyciknz** [comment]
I think I did use those originally.  But added poster and avatar.  But they seemed to be from the episode so it overwrote the poster.jpg all the time.

I can post it if you want.

What from the config.yaml has the show poster being dumped to the show folder (before the season is output)

**Comment by jmbannon** [comment]
Bugfix for it is here: https://github.com/jmbannon/ytdl-sub/pull/304
Should be live fairly soon. I would try using that method again, it will overwrite the poster.jpg once another vid from the channel is downloaded

**Comment by psyciknz** [comment]
```
configuration:
  working_directory: '.ytdl-sub-downloads'
presets:
  # Your main TV show preset - all your tv show subscriptions will use this.
  tv_show:
    preset:
      # Choose one of the following player types:
      - "jellyfin_tv_show_by_date"  # replace with desired player type

      - "season_by_year__episode_by_month_day"  # replace with desired season/episode format

    download_strategy: "channel"
    channel_avatar_path: "poster.jpg"
    channel_banner_path: "fanart.jpg"

    ytdl_options:
      format: "bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"
    
    nfo_tags:
      nfo_name: "{channel}.nfo"
      nfo_root: "Youtube"
      tags:
        title: "{title}"
        year: "{upload_year}"

    overrides:
      tv_show_directory: "/yt-tv"  # replace with path to tv show directory
      episode_plot: "{description}"
      file_name: "{title_sanitized}_[{uid}].{ext}"

####################################################################################################

  # Preset to only download and keep recent videos
  only_recent_videos:

    # Only download videos within the download_range
    date_range:
      after: "today-{download_range}"

    # Stops fetching metadata if the video is out of range (saves time + bandwidth)
    ytdl_options:
      break_on_reject: True

    # Deletes any videos older than download_range. WARNING: do not use
    # "season_by_year__episode_by_download_index" if you plan to delete older videos
    output_options:
      keep_files_after: "today-{download_range}"

    # Set the duration of download_range, defaults to 2 months
    overrides:
      download_range: "2months"

####################################################################################################

  # Preset for the hoarders who want to also save the info.json file
  include_info_json:
    output_options:
      info_json_name: "{episode_file_path}.{info_json_ext}"

```

Here's the config.yaml that I'm intending to run.  
```
 download_strategy: "channel"
    channel_avatar_path: "poster.jpg"
    channel_banner_path: "fanart.jpg"
```
Was the area where in your old samples these are in a youtube: section.  But doesn't seem to be applicable in the new format.
Just want to confirm, before I push this back and get an updated code
