### ISSUE TITLE
Detected multiple top-level parents crash

### ISSUE THREAD

**Issue by orthanc42** [jmbannon/ytdl-sub#322]
was told to post this here by DaveAnon in discord. having an issue with my config and subscriptions.yaml files.

here is the log file.

```
[ytdl-sub] Beginning subscription download for heavy_d
[ytdl-sub] Subscription full yaml:
presets:
  heavy_d:
    chapters:
      embed_chapters: true
      force_key_frames: false
      remove_sponsorblock_categories:
      - sponsor
      - preview
      sponsorblock_categories:
      - intro
      - outro
      - selfpromo
      - preview
      - interaction
      - sponsor
      - music_offtopic
    date_range:
      after: today-{download_range}
      before: today-2days
    download:
      playlist_thumbnails:
      - name: '{tv_show_poster_file_name}'
        uid: avatar_uncropped
      - name: '{tv_show_fanart_file_name}'
        uid: banner_uncropped
      url: '{url}'
    file_convert:
      convert_to: mp4
    output_options:
      file_name: '{episode_file_path}.{ext}'
      keep_files_after: today-{download_range}
      maintain_download_archive: true
      output_directory: '{tv_show_directory}/{tv_show_name_sanitized}'
      thumbnail_name: '{episode_file_path}-thumb.jpg'
    overrides:
      download_range: 2months
      episode: '{upload_month}{upload_day_padded}'
      episode_date_standardized: '{upload_date_standardized}'
      episode_file_name: '{tv_show_name} - S{season}E{episode_padded} - {title_sanitized}'
      episode_file_path: Season {season_number_padded}/{episode_file_name}
      episode_number: '{upload_month}{upload_day_padded}{upload_date_index_padded}'
      episode_number_padded: '{upload_month_padded}{upload_day_padded}{upload_date_index_padded}'
      episode_padded: '{upload_month_padded}{upload_day_padded}'
      episode_path: Season {season}/{episode_file_name}
      episode_plot: '{webpage_url}'
      episode_title: '{upload_date_standardized} - {title}'
      episode_year: '{upload_year}'
      season: '{upload_year}'
      season_number: '{upload_year}'
      season_number_padded: '{season_number}'
      season_poster_file_name: Season{season_number_padded}.jpg
      season_title: '{season_number_padded}'
      tv_show_directory: /tv_shows
      tv_show_fanart_file_name: fanart.jpg
      tv_show_genre: ytdl-sub
      tv_show_name: Heavy D Sparks
      tv_show_poster_file_name: poster.jpg
      url: https://www.youtube.com/c/HeavyDSparks
    preset:
    - _episode_video_tags
    - _plex_tv_show
    - _tv_show_by_date
    - _episode_base
    - _season_by_year
    - plex_tv_show_by_date
    - season_by_year__episode_by_month_day
    - sponsorblock
    - tv_show
    - only_recent_videos
    video_tags:
      tags:
        date: '{episode_date_standardized}'
        episode_id: '{episode_number}'
        genre: '{tv_show_genre}'
        season_number: '{season_number}'
        show: '{tv_show_name}'
        synopsis: '{episode_plot}'
        title: '{episode_title}'
        year: '{episode_year}'
    ytdl_options:
      break_on_existing: true
      break_on_reject: true

[ytdl-sub:downloader] ytdl_options: {'ignoreerrors': True, 'outtmpl': '.ytdl-sub-downloads/heavy_d/%(id)s.%(ext)s', 'download_archive': '.ytdl-sub-downloads/heavy_d/.ytdl-subscribe-heavy_d-download-archive.txt', 'writethumbnail': False, 'daterange': <yt_dlp.utils.DateRange object at 0x14a53625e320>, 'postprocessors': [{'key': 'FFmpegVideoRemuxer', 'when': 'post_process', 'preferedformat': 'mp4'}, {'key': 'SponsorBlock', 'when': 'pre_process', 'categories': ['intro', 'outro', 'selfpromo', 'preview', 'interaction', 'sponsor', 'music_offtopic']}, {'key': 'ModifyChapters'}, {'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}, {'key': 'ModifyChapters', 'force_keyframes': False, 'remove_sponsor_segments': ['sponsor', 'preview']}, {'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}, {'key': 'FFmpegVideoRemuxer', 'when': 'post_process', 'preferedformat': 'mp4'}, {'key': 'SponsorBlock', 'when': 'pre_process', 'categories': ['intro', 'outro', 'selfpromo', 'preview', 'interaction', 'sponsor', 'music_offtopic']}, {'key': 'ModifyChapters'}, {'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}, {'key': 'ModifyChapters', 'force_keyframes': False, 'remove_sponsor_segments': ['sponsor', 'preview']}, {'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}], 'break_on_existing': True, 'break_on_reject': True, 'writeinfojson': True, 'skip_download': True}
[ytdl-sub:yt-dlp] [youtube:tab] HeavyDSparks: Downloading webpage
[ytdl-sub:yt-dlp] [youtube:tab] Downloading all uploads of the channel. To download only the videos in a specific tab, pass the tab's URL
[ytdl-sub:yt-dlp] [youtube:tab] HeavyDSparks/streams: Downloading webpage
[ytdl-sub:yt-dlp] [youtube:tab] HeavyDSparks/shorts: Downloading webpage
[ytdl-sub:yt-dlp] [youtube:tab] Downloading as multiple playlists, separated by tabs. To download as a single playlist instead, pass https://www.youtube.com/playlist?list=UUGTKwjs1ctvgwCRa67RNO-Q
[ytdl-sub:yt-dlp] [download] Downloading playlist: HeavyDSparks
[ytdl-sub:yt-dlp] [info] Writing playlist metadata as JSON to: .ytdl-sub-downloads/heavy_d/HeavyDSparks.info.json
[ytdl-sub:yt-dlp] [youtube:tab] Playlist HeavyDSparks: Downloading 3 videos of 3
[ytdl-sub:yt-dlp] [download] Downloading video 1 of 3
[ytdl-sub:yt-dlp] [download] Downloading playlist: HeavyDSparks - Videos
[ytdl-sub:yt-dlp] [info] Writing playlist metadata as JSON to: .ytdl-sub-downloads/heavy_d/UCGTKwjs1ctvgwCRa67RNO-Q.info.json
[ytdl-sub:yt-dlp] [youtube:tab] Playlist HeavyDSparks - Videos: Downloading 1 videos
[ytdl-sub:yt-dlp] [download] Rescuing a Family That Was Stranded For 3 Days After Other Tow Companies Failed has already been recorded in the archive
[ytdl-sub:downloader] ExistingVideoReached, stopping additional downloads
[ytdl-sub] An uncaught error occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ytdl_sub/main.py", line 28, in main
    _main()
  File "/usr/lib/python3.10/site-packages/ytdl_sub/main.py", line 19, in _main
    ytdl_sub.cli.main.main()
  File "/usr/lib/python3.10/site-packages/ytdl_sub/cli/main.py", line 146, in main
    transaction_logs = _download_subscriptions_from_yaml_files(config=config, args=args)
  File "/usr/lib/python3.10/site-packages/ytdl_sub/cli/main.py", line 55, in _download_subscriptions_from_yaml_files
    transaction_log = subscription.download(dry_run=args.dry_run)
  File "/usr/lib/python3.10/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 256, in download
    for entry in downloader.download():
  File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/downloader.py", line 554, in download
    parents, orphan_entries = self._download_url_metadata(collection_url=collection_url)
  File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/downloader.py", line 510, in _download_url_metadata
    self.parents = EntryParent.from_entry_dicts(
  File "/usr/lib/python3.10/site-packages/ytdl_sub/entries/entry_parent.py", line 249, in from_entry_dicts
    if (root_parent := cls._get_disconnected_root_parent(url, parents)) is not None:
  File "/usr/lib/python3.10/site-packages/ytdl_sub/entries/entry_parent.py", line 225, in _get_disconnected_root_parent
    raise ValueError(
ValueError: Detected multiple top-level parents. Please file an issue on GitHub with the URLs used to produce this error
[ytdl-sub] Please upload the error log file '/tmp/ytdl-sub.j49lwz60' and make a Github issue at https://github.com/jmbannon/ytdl-sub/issues with your config and command/subscription yaml file to reproduce. Thanks for trying ytdl-sub!
```

**Comment by orthanc42** [comment]
config.yaml
```
# This config uses prebuilt presets included with ytdl-sub to download and format
# channels from YouTube or other sites supported by yt-dlp into a TV show for
# your favorite player. The directory format will look something like
#
#   /tv_shows
#       /Season 2021
#           s2021.e0317 - Pattys Day Video-thumb.jpg
#           s2021.e0317 - Pattys Day Video.mp4
#           s2021.e0317 - Pattys Day Video.nfo
#       /Season 2022
#           s2022.e1225 - Merry Christmas-thumb.jpg
#           s2022.e1225 - Merry Christmas.mp4
#           s2022.e1225 - Merry Christmas.nfo
#       poster.jpg
#       fanart.jpg
#       tvshow.nfo
#
# The idea is to use dates as numerics to represent season and episode numbers.
configuration:
  working_directory: '.ytdl-sub-downloads'

presets:

  # Your main TV show preset - all your tv show subscriptions will use this.
  tv_show:
    preset:
      # Choose one of the following player types:
      # - "kodi_tv_show_by_date"
      # - "jellyfin_tv_show_by_date"
      # - "plex_tv_show_by_date"

      - "plex_tv_show_by_date"  # replace with desired player type

      # Choose one of the following season/episode formats:
      # - "season_by_year__episode_by_month_day"
      # - "season_by_year_month__episode_by_day"
      # - "season_by_year__episode_by_month_day_reversed"
      # - "season_by_year__episode_by_download_index"

      - "season_by_year__episode_by_month_day"  # replace with desired season/episode format

      # Include any of the presets listed below in your 'main preset' if you want
      # it applied to every TV show. Or, use them on the individual subscriptions.
      # - "only_recent_videos"
      # - "add_subtitles"
      - "sponsorblock"
      # - "include_info_json"

    # To download age-restricted videos, you will need to uncomment and set your cookie
    # file here as a ytdl parameter. For more info, see
    # https://ytdl-sub.readthedocs.io/en/latest/faq.html#download-age-restricted-youtube-videos
    #
    # ytdl_options:
    #   cookiefile: "/config/cookie_file.txt"  # replace with actual cookie file path

    overrides:
      tv_show_directory: "/tv_shows"  # replace with path to tv show directory
      # Fields in the prebuilt preset that can be changed:
      #
      # episode_title: "{upload_date_standardized} - {title}"
      # episode_plot: "{webpage_url}"  # source variable for the video description is {description}
      tv_show_name: "OVERRIDE IN SUBSCRIPTION"
      season: "{upload_year}"
      episode: "{upload_month}{upload_day_padded}"
      episode_padded: "{upload_month_padded}{upload_day_padded}"
      episode_file_name: "{tv_show_name} - S{season}E{episode_padded} - {title_sanitized}"
      episode_path: "Season {season}/{episode_file_name}"

####################################################################################################

  # Preset to only download and keep recent videos
  only_recent_videos:

    # Only download videos within the download_range
    date_range:
      after: "today-{download_range}"

    # Stops fetching metadata if the video is out of range (saves time + bandwidth)
    ytdl_options:
      break_on_reject: True

    # Deletes any videos older than download_range. WARNING: do not use
    # "season_by_year__episode_by_download_index" if you plan to delete older videos
    output_options:
      keep_files_after: "today-{download_range}"

    # Set the duration of download_range, defaults to 2 months
    overrides:
      download_range: "2months"

####################################################################################################

  # Preset to download subtitles (either by file or embedded)
  # add_subtitles:
    # Embed subtitles into the video
    # embed_subtitles: True
    # And/or download them as a file. Uncomment to download as file:
    # subtitles_name: "{episode_file_path}.{lang}.{subtitles_ext}"
    # subtitles_type: "srt"

    # languages: "en"  # supports list of multiple languages
    # allow_auto_generated_subtitles: True  # allow auto subtitles

####################################################################################################

  # Preset to cut sponsor segments from videos
  sponsorblock:
    # If you download using cron, it is wise to add a delay before downloading ad-filled content to
    # give folks time to submit sponsor segments. Uncomment to wait 2 days before download a video.
    date_range:
      before: "today-2days"

    chapters:
      # Remove all of these sponsorblock categories
      sponsorblock_categories:
        - "intro"
        - "outro"
        - "selfpromo"
        - "preview"
        - "interaction"
        - "sponsor"
        - "music_offtopic"
      remove_sponsorblock_categories:
        - "sponsor"
        - "preview"
      force_key_frames: False

####################################################################################################

  # Preset for the hoarders who want to also save the info.json file
  include_info_json:
    output_options:
      info_json_name: "{episode_file_path}.{info_json_ext}"

```

**Comment by orthanc42** [comment]
subscriptions.yaml
```
# Define any number subscriptions in a single file, or use multiple
# files to organize (i.e by genre)

heavy_d:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Heavy D Sparks"
    url: "https://www.youtube.com/c/HeavyDSparks"

lpl:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Lock Picking Lawyer"
    url: "https://www.youtube.com/c/lockpickinglawyer"

laurakampf:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Laura Kampf"
    url: "https://www.youtube.com/c/laurakampf"

demoranch:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Demolition Ranch"
    url: "https://www.youtube.com/channel/UCBvc7pmUp9wiZIFOXEp1sCg"

offtheranch:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Off the Ranch"
    url: "https://www.youtube.com/c/OffTheRanch"

smartereveryday:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Smarter Every Day"
    url: "https://www.youtube.com/c/smartereveryday"

fitnessoutrageous:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Ali Spagnola's Fitness Outrageous"
    url: "https://www.youtube.com/c/FitnessOutrageous"

alispagnola:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Ali Spagnola"
    url: "https://www.youtube.com/c/alispagnola"

markrober:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Mark Rober"
    url: "https://www.youtube.com/c/MarkRober"

kallmekris:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "KallMeKris"
    url: "https://www.youtube.com/channel/UCiciOsypkXcqSFqSPd-NRVA"

kentuckyballistics:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Kentucky Ballistics"
    url: "https://www.youtube.com/c/Kentucky Ballistics"

abom79:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Abom79"
    url: "https://www.youtube.com/c/Abom79"

armin:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Armin van Buuren"
    url: "https://www.youtube.com/channel/UCu5jfQcpRLm9xhmlSd5S8xw"

williamosman:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "William Osman"
    url: "https://www.youtube.com/c/williamosman"

williamosman2:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "William Osman 2"
    url: "https://www.youtube.com/c/WilliamOsman2"

carlalallimusic:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Carla Lalli Music"
    url: "https://www.youtube.com/c/CarlaLalliMusic123"
    
pulpcomedy:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Pulp Comedy"
    url: "https://www.youtube.com/channel/UCjnrbTISBUbFoGeqULsBzhw"

woodwhisperer:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "The Wood Whisperer"
    url: "https://www.youtube.com/channel/UCKp44bWWZIiOPShPN_ytShw"

waterjetchannel:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Waterjet Channel"
    url: "https://www.youtube.com/c/WaterjetChannel"

jameshoffman:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "James Hoffman"
    url: "https://www.youtube.com/channel/UCMb0O2CdPBNi-QqPk5T3gsQ"

physicsgirl:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Physics Girl"
    url: "https://www.youtube.com/c/physicsgirl"

slowmoguys:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "The Slow Mo Guys"
    url: "https://www.youtube.com/channel/UCUK0HBIBWgM2c4vsPhkYY4w"

slowmoguys2:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "The Slow Mo Guys"
    url: "https://www.youtube.com/c/TheSlowMoGuys2"

julienolke:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Julie Nolke"
    url: "https://www.youtube.com/c/FeelingPeckish"

deviantollam:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Deviant Ollam"
    url: "https://www.youtube.com/channel/UC4dxXZQq-ofAadUWbqhoceQ"

technologyconnections:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Technology Connections"
    url: "https://www.youtube.com/c/TechnologyConnections"

mathiaswandel:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Mathias Wandel"
    url: "https://www.youtube.com/c/Matthiaswandel"

mathiaswandel2:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Mathias Random Stuff"
    url: "https://www.youtube.com/channel/UC3_AWXcf2K3l9ILVuQe-XwQ"

kenji:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "J. Kenji López-Alt"
    url: "https://www.youtube.com/c/JKenjiLopezAlt"

alexandradaddario:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Alexandra Daddario"
    url: "https://www.youtube.com/channel/UCIU3ZZKZxT5e7OBA5avh5VQ"

girlwiththedogs:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Girl with the Dogs"
    url: "https://www.youtube.com/c/GirlWithTheDogs"

jaybates:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Jay Bates"
    url: "https://www.youtube.com/c/JayBates"

fireballtool:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Fireball Tool"
    url: "https://www.youtube.com/c/FireballTool"

fireball2ool:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Fireball 2ool"
    url: "https://www.youtube.com/c/Fireball2ool"

michaelalm:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Michael Alm"
    url: "https://www.youtube.com/c/MichaelAlm"

ambitionstrikes:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Ambition Strikes"
    url: "https://www.youtube.com/c/AmbitionStrikes"

stumpynubs:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Stumpy Nubs"
    url: "https://www.youtube.com/c/StumpyNubs"

clairesaffitz:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Claire Saffitz"
    url: "https://www.youtube.com/c/ClaireSaffitzxDessertPerson"

inheritancemachining:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Inheritance Machining"
    url: "https://www.youtube.com/c/inheritancemachining"

ethanchlebowski:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Ethan Chlebowski"
    url: "https://www.youtube.com/c/CookwithE"

tomscott:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Tom Scott"
    url: "https://www.youtube.com/c/TomScottGo"

petersripol:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Peter Sripol"
    url: "https://www.youtube.com/c/PeterSripol"

colinfurze:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Colin Furze"
    url: "https://www.youtube.com/c/colinfurze"
```
