### ISSUE TITLE
add separate regex filters for playlist and direct video link for multi_url download strategy

### ISSUE THREAD

**Issue by Behem07h** [jmbannon/ytdl-sub#337]
the user is unlikely to directly link a video or playlist that contains videos they dont want to download, however they may want to use the same subscriptions.yaml entry to also include a channel link and use regex filters to download videos from there. Separating the regex filters for the different link types would allow the use of a more strict regex filter on some link types and a more lenient one on other link types, without having to use 2 subscriptions.yaml entries. 

this would turn
my_strict_filter:
    preset: "multi_url_download"
    download:
        urls:
            - url: "youtube_channel_url"
my_lenient_filter:
    preset: "multi_url_download"
    download:
        urls:
            - url: "youtube_playlist_url"
            
into simply
my_filters:
    preset: "multi_url_download"
    download:
        urls:
            - url: "youtube_channel_url"
            - url: "youtube_playlist_url"
            
thus making subscriptions.yaml more compact and organised

**Comment by jmbannon** [comment]
You can probably do this by using the `variables` param: https://ytdl-sub.readthedocs.io/en/latest/config.html#ytdl_sub.downloaders.generic.multi_url.MultiUrlDownloadOptions.variables

Both URLs will have this variable, but for one URL just set it to something dumb like "NA" and the other to what you want to filter on. Do vice versa for the other. Something like this:

```
my_strict_filter:
  download:
    urls:
    - url: "Channel 1"
      variables:
        channel_title: "{title}"
        playlist_title: "NOPE"
    - url: "Playlist 1"
      variables:
        channel_title: "NOPE"
        playlist_title: "{title}"
```
