### ISSUE TITLE
Support native thumbnail embeding

### ISSUE THREAD

**Issue by Vorror** [jmbannon/ytdl-sub#343]
Currently, I'm using the [Youtube song example](https://github.com/jmbannon/ytdl-sub/blob/master/examples/music_audio_from_videos.yaml) as the basis for my config file. 

When downloading music, I need to use ```ytdl_options:``` options to embed thumbnails:

```
  song:
    ytdl_options:
      postprocessors:
      - key: "EmbedThumbnail"
        when: "post_process"

    output_options:
      output_directory: "{music_directory}"
      file_name: "{custom_track_name_sanitized}.{ext}"

      # Required, thumbnail won't be embedded otherwise
      thumbnail_name: "{custom_track_name_sanitized}-thumb.{thumbnail_ext}"
```

It's a bit annoying since I'm forced to have an extra unwanted file for every song(I don't need the thumbnail after it's embedded)

The actual issue I'm having is with embedding thumbnails when also using the `split_by_chapters` option. Example:

```
album_from_chapters:
    preset: "song"
    
    ytdl_options:
      postprocessors:
      - key: "EmbedThumbnail"
        when: "post_process"

    output_options:
      file_name: "{custom_album_name_sanitized}/{chapter_index_padded} - {custom_track_name_sanitized}.{ext}"
      thumbnail_name: "{custom_album_name_sanitized}/folder.{thumbnail_ext}"

    chapters:
      embed_chapters: True

    split_by_chapters:
      when_no_chapters: "pass"
```

When the songs are downloaded, only the _first_ song has the thumbnail embedded. 

---

So, my request is: Is it possible to get an `embedd_thumbnail` option that works with the `split_by_chapters` option so every song has a thumbnail?
