### ISSUE TITLE
Custom post-processing with ffmpeg

### ISSUE THREAD

**Issue by bpoulliot** [jmbannon/ytdl-sub#352]
## **[Feature Request]**
In situ post-processing for scraped media with configurable encoders and quality.
### Description
REVISED: Removing extraneous info, expanding and clarifying examples with specific commands.

Most quality/compression decisions cannot be made via format selection, such as conversion to x265, libfdk_aac audio, exact scaling, subtitle burn-in, etc... Having these options configurable as part of the program offers a huge benefit and expands the unique feature set of ytdl-sub.

### Background
Currently `ytdl_options` plugin does not function for post-processing (expected behavior, not documented) Tested with several variations of: `postprocessor_args: "-c:v libx265 -preset slow -crf 28 -c:a libfdk_aac -ac 2 -b:a 64k"`. All failed, but did not cause an early exit and scraping continued. Seems like the option was largely ignored.

### Detailed Request Info
It would be great to be able to do a few things during post-processing...
1. Select a supported video codec using ffmpeg notation (e.g., `libx265` or `hevc_qsv`).
2. Support hardware accelerated video transcoding if available (may require a device to be passed into the container, plus additional options for each additional encoder supported).
3. Indicate a preset for the video encoder if supported.
4. Allow for specifying a video profile (e.g., `-profile:v main10`) to allow for 10-bit (x265) or level/tier (h264).
5. Choose a constant rate factor (CRF) or global_quality if supported.
6. Choose an audio codec available in the compiled ffmpeg version, choose an alternate ffmpeg version, or compile ffmpeg at runtime with desired features enabled (e.g., libopus, hevc_qsv, libfdk_aac, non-free components). You can technically already accomplish the middle option using a `custom-cont-init.d` script, but finding a pre-compiled ffmpeg with all the options you need is difficult. 
**REMOVED (incorrect)**: ~~(e.g., jellyfin-ffmpeg is compiled with hardware acceleration, opus, libfdk_aac, etc...)~~
7. Specify any advanced options -- audio channels, video or audio bitrate, as well as advanced options for the encoder.

### EXAMPLES (Reformatted, Extended)
I discovered -- since submitting this issue -- that I was approaching hevc_qsv incorrectly, plus I failed to demonstrate the CLI commands.  I omitted some problematic commands that require specific hardware/software combos in favor of the 80/20 principle. Feel free to reach out with questions.
#### Software x265 in MP4 container with "experimental" OPUS audio
`ffmpeg -hide_banner -loglevel info \` # hide init print with enabled options, set log level
`-i "*/path/to/input_1.webm*" [-i "*/path/to/input_2.aac*" ... -i "*/path/to/input_n.srt*"] \` # specify full/workdir paths for each file to be muxed/encoded[^1]
`-strict experimental \` # enable "experimental" options, e.g., OPUS in MP4 container
`[-max_muxing_queue_size 4096 \]` # optional, raise muxing queue to avoid processing errors (arbitrary integer of "packets")
`-map 0:v:0 -map 0:a:0 [-map 1:a:0 ... -map n:s:0] \` # map each desired stream to the output[^2]
`-c:v:0 libx265 -preset slow -crf 23 -tune animation \` # set codec, preset, CRF for video stream 0[^3]
`-profile main10 -pix_fmt yuv420p10le \` # profile and pix_fmt allow encoding in 10-bit depth[^4]
`[-x265-params :limit-sao=1:deblock=1,1:bframes=8:psy-rd=1.5:psy-rdoq=2:aq-mode=3:ref=6]` # optional[^5]
`-c:a:0 opus -ac:0 2 -b:a:0 64k -vbr on \` # set audio codec, audio channels, bitrate, add'l encoder-specific options[^6]
`-c:s:0 copy [-c:s:n copy] \` # copy embedded subtitle streams, avoid the rabbit hole of conversion or extraction[^7]
`-y "/path/to/output_file.mkv" # non-interactive overwrite and specify output file and container (via file extension)

#### Hardware-Accelerated (QuickSync) with standard AAC
Since I covered multiple inputs up top and that's universal, I'll assume the download profile in ytdl-sub is `format: "bestvideo+bestaudio/best"` which could yield video, audio, and subtitle files to simplify.

`ffmpeg -hide_banner -loglevel info \`
`-init_hw_device qsv=hw -filter_hw_device hw \` # initialize hw acceleration device, specify type
`-i "/path/to/input_video.webm" -i "/path/to/input_audio.mp3" -i "/path/to/input_subs.srt" \` # all three possible input files
`[-look_ahead 1] -strict experimental -max_muxing_queue_size 2048 \` # `look_ahead` **before any output/encoder selection** invokes LA_ICQ mode for *decoding* (optional)
`-map 0:v:0 -map 1:a:0 -map 2:s:0 \` # map all inputs to single output file
`-c:v:0 hevc_qsv  -preset slower -global_quality 18 \` # specify HEVC QuickSync, encoder preset, quality estimate (similar to CRF)
`-extbrc 1 -b_strategy 1 -look_ahead 1 \ # advanced options `extbrc` and `b_strategy` are extra quality refinement, `look_ahead` invokes LA_ICQ for *encoding*
`-profile:v main10 -pix_fmt p010le \` # specify 10-bit profile and correct pixel format for QSV encoding
`-c:a:0 aac -c:s:0 copy \` # pick audio encoder and copy subtitles
`-y "/path/to/output_file.mkv"` # non-interactive overwrites, specify output file and container (via extension)

### CLOSING
Reach out if I can help. I'm not much of a developer, but I do enjoy tinkering. Video has been a passion for a long time. Happy to assist where I can.

[^1]: Inputs can be any number of any supported file type, generally video, audio, subtitle, or image (for embedding metadata).
[^2]: [Mapping is complex](https://trac.ffmpeg.org/wiki/Map), but super useful when taking disparate components and pulling them into a single file. The basic syntax is `[input]:[stream type]:[specifier]` where input and specifier are zero-indexed (that is, 0 value for input means the first input you specified earlier, v means this map refers strictly to video from that input file, and 0 value for specifier is the first video stream contained in that file). Useful, unclear options include things like negative mapping (everything *except* a certain stream) and stream re-ordering (set audio streams in specific order). Easiest approach is to use [stream type specification](https://ffmpeg.org/ffmpeg.html#Stream-specifiers) but absolute can be used as well if you omit the stream type identifier.
[^3]: Arguments `-c:v[:n]` and `-c:a[:n]` are shorthand for -codec:[stream type]:[specifier] followed by desired encoder. Multiple video streams not overly common, but can happen. Multiple audio streams quite common. My recommendation is to make folks choose a single codec they like for all audio streams, at least at the start.
[^4]: Profile used heavily as main10 preferred for animation and 4K content. Unfortunately, much of the time pix_fmt is required as well if converting 8-bit --> 10-bit or converting weird encodes to something more common or compatible. I do not understand this well, but I know that `-pix_fmt yuv420p` is standard 8-bit colorspace for libx265, `-pix_fmt yuv420p10le` is 10-bit colorspace for libx265, and `-pix_fmt p010le` is 10-bit colorspace for hevc_qsv encoding.
[^5]: Too many advanced parameters to discuss. Many can only be set via the `-x265-params` flag. [More info on x265 tuning options](https://x265.readthedocs.io/en/master/cli.html#performance-options) if you decide you hate yourself. I would be shocked if anybody needs many of the advanced options, but even simple tools like Handbrake just leave an empty box for a "dig your own grave with options" adventure.
[^6]: I use `-ac 2` to specify the number of audio channels the end product. A lot of people will gag that I don't handle my own mix-down of channels since this option essentially just drops low-frequency audio. Universally compatible, `-b:a 64k` is shorthand for -bitrate:[stream] (`a` for audio in this case, can also be used for `v` video) and helps to keep file size small or close to a specific target; also dangerous due to encoder disparities in transparency.
[^7]: I can provide an example of burning in subtitles (hard subs) if needed. It's just a little more complex and is source-format dependent. Can become a quagmire fairly quickly, but since you'd mainly be dealing with SRT that makes it simpler.

**Comment by jmbannon** [comment]
Thanks a lot for context and arg info, makes it very easy for me!

Have been thinking about this the past few days. Both approaches have their pros and cons - guardrails with defaults make it nice for those not savvy with ffmpeg (including myself). On the other hand, having the freedom to do any ffmpeg command might be nice for advanced users.

**Comment by bpoulliot** [comment]
I got a notification while I was revising my original issue....there's a lot better info I can give. Trying to make it more clear, so stay tuned and I'll have something (hopefully) better in a few. Depending on how hard error handling would be, you could set up, 3 presets for an ffmpeg plugin that handled simple use cases (either all-or-nothing or options like "video_codec" with limited choices) and then a single free-for-all version that just passes the command on to ffmpeg CLI/API with a warning that it won't correct your wrong settings and a generic catch for errors that gives exit code/reason.

**Comment by jmbannon** [comment]
Have given it more thought, I think we should just make it as customizable as possible. Then we can add some prebuilt presets to do simple x265 conversion.

As the ffmpeg expert, do you think filename extensions will change during post processing? If someone changes the file name/ext then ytdl-sub won't find it. We'd need some way to convey that in the config if someone does change file names or extensions.

**Comment by jmbannon** [comment]
Similarly, if someone makes multiple files from one file, that'd need config support.

**Comment by jmbannon** [comment]
Also any ideas or suggestions on how this should look in the config?

**Comment by bpoulliot** [comment]
I like the idea of starting simple. It's quite possible the file extensions will change depending on settings. I know that I have been using the existing file_convert plugin for MKV format, but I assume you account for that. Could we mimic that "update" process for the entry if ffmpeg can spit out something usable when it succeeds? A little more context on how/when/where it would break might help me brainstorm.

For now, I wonder if there's a way to artificially limit ffmpeg to a single output. I have a couple ideas of how a config could look that might lock it down a bit. Part of this is coming up with a template of what default options should be for the moment. Even customizable, there's a limit of how much guessing you can do.
## Basic Choose Your Own Adventure
```
plugin:
    ffmpeg_post:
        video: "-c:v libx265  -preset slow -crf 23 -tune animation -profile main10 -pix_fmt yuv420p10le -x265-params limit-sao=1:deblock=1,1:bframes=8:psy-rd=1.5:psy-rdoq=2:aq-mode=3:ref=6"
        audio: "-c:a aac -ac 2 -b:a 192k"
        subs: "-c:s copy"
        container: [mkv] | mp4 # decides file extension
```
Assumptions: One file input after it has been assembled by the initial yt-dlp ffmpeg call, no mapping to be done unless somebody knows their exact file stream topology. Still pretty simple and lets you assemble the command piece by piece. Run:
```
ffmpeg -hide_banner -loglevel info -y -i "/path/to/input/file.old_ext" -strict experimental -map 0:v -map 0:a -map 0:s? [video_block] [audio_block] [subs_block] "/path/to/output/file.[container]"
```
Simple and straightforward, and you could set a few defaults if needed. I would need to test if mapping causes generic video and audio options to fail, but I don't believe so.

*NOTE:* The encoders **libaom-av1**(?), **libmp3lame**, **libopus**, and **libfdk_aac** require that ffmpeg be compiled with each enabled. Not all default implementations will have them available, but that banner we hide with each ffmpeg command actually shows what is enabled and we can always double check using `ffmpeg -codecs` to list everything in exhaustive detail.
## Guided
```
plugin:
    ffmpeg_post:
        container: [mkv] | mp4
        video:
            encoder: copy | [libx265] | libx264 | h264_qsv | hevc_qsv | libaom-av1
            preset: ultrafast | superfast | veryfast | faster | fast | [medium] | slow | slower | veryslow
            profile: [main] | main10 # set pix_fmt based on choice here, x264 not compatible with 10-bit
            pix_fmt (auto/hidden): [yuv420p] | yuv420p10le # only change if main10 profile selected
            quality: [23] | int | -b:v 12345k
            adv: [  ] # allow for things like -x265 params
        audio:
            encoder: copy | [aac] | flac | ac3 | libmp3lame | libopus | libfdk_aac 
            stereo: true | [false] # skip -ac 2 if false, just use encoder and quality
            quality: [-b:a 384k] | (*empty*) | -q:a (*num*)  # default empty? 384k?, complex to decide (https://trac.ffmpeg.org/wiki/Encode/HighQualityAudio)
        subtitles:
            embed: [true] | false # true --> -c:s copy, false --> do nothing (sub file should already be written out)
```
And now we build the same way, noting that `copy` replaces encoder name, indicating "don't re-encode this stream": 
```
ffmpeg -hide_banner -loglevel info -y -i "/path/to/input/file.old_ext" -strict experimental -map 0:v -map 0:a -map 0:s? -c:v *[encoder] [preset] [profile] [pix_fmt auto] [quality] [adv]* -c:a *[encoder] [stereo/pass] [quality] [subs/no]* "/path/to/output/file.*[container]*"
```

I like the latter solution better, but it's a bit more calculating behind the scenes and some guess work. Fewer chances for somebody to mess it up, though. That's all I got for tonight, it's time to pass out. Thanks for engaging with me on this, wracking my brain has been fun.
[^1]: ffmpeg must be compiled with these encoders enabled in order to use them, which may not be standard
