### ISSUE TITLE
Square thumbnail support

### ISSUE THREAD

**Issue by Vorror** [jmbannon/ytdl-sub#383]
#### Feature request

It would be great if there were a config option that either cropped or downloaded(assuming YT has square images) the embedded thumbnail. For music, square thumbs work best. It's also mentioned [here](https://github.com/yt-dlp/yt-dlp/issues/429), but I don't know how relevant it is.

**Comment by Kentaro1043** [comment]
I found the right configuration for YT Music's square thumbnails. Here it is:

```yaml
    ytdl_options:
      postprocessors:
        - key: "FFmpegThumbnailsConvertor"
          format: "jpg"
        - key: "EmbedThumbnail"
      postprocessor_args:
        - "-c:v"
        - "mjpeg"
        - "-qmin"
        - "1"
        - "-qscale:v"
        - "1"
        - "-vf"
        - "crop=min(iw\\,ih):min(iw\\,ih)"
```

This is my full config.yaml: https://github.com/Kentaro1043/dotfiles/blob/main/home-manager/files/ytdl-sub/config.yaml

I still haven't found the right configuration for folder.jpg, and I've spent a lot of time on these configurations. Providing a prebuilt configuration seems like a good idea.
