### ISSUE TITLE
YT Playlist not downloading

### ISSUE THREAD

**Issue by psyciknz** [jmbannon/ytdl-sub#397]
Hi got a playlist I never seem to get output for
Subscription is:
```
wtf1:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "WTF1"
    url: "https://www.youtube.com/playlist?list=PLB-vNGnkFt6wV5UF7pDSr--OgIxIfPvqL"
    # Optional
    tv_show_genre: "DIY"
```

Where tv_show is:
```
tv_show:
    preset:
      # Choose one of the following player types:
      - "jellyfin_tv_show_by_date"  # replace with desired player type
      - "season_by_year__episode_by_month_day"  # replace with desired season/episode format
    ytdl_options:
      format: "bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"
    overrides:
      tv_show_directory: "/yt-tv"  # replace with path to tv show directory
      episode_plot: "{description}"
      file_name: "{title_sanitized}_[{uid}].{ext}"
```
Just never seems to gather any videos.

**Comment by psyciknz** [comment]
Added logging
```
[ytdl-sub] Beginning subscription download for wtf1
[ytdl-sub] Subscription full yaml:
presets:
  wtf1:
    chapters:
      embed_chapters: true
    date_range:
      after: today-{download_range}
    generic:
      playlist_thumbnails:
      - name: '{tv_show_poster_file_name}'
        uid: avatar_uncropped
      - name: '{tv_show_fanart_file_name}'
        uid: banner_uncropped
      url: '{url}'
    nfo_tags:
      nfo_name: '{episode_file_path}.nfo'
      nfo_root: episodedetails
      tags:
        aired: '{episode_date_standardized}'
        episode: '{episode_number}'
        genre: '{tv_show_genre}'
        plot: '{episode_plot}'
        season: '{season_number}'
        title: '{episode_title}'
        year: '{episode_year}'
    output_directory_nfo_tags:
      nfo_name: tvshow.nfo
      nfo_root: tvshow
      tags:
        genre: '{tv_show_genre}'
        title: '{tv_show_name}'
    output_options:
      file_name: '{episode_file_path}.{ext}'
      keep_files_after: today-{download_range}
      maintain_download_archive: true
      output_directory: '{tv_show_directory}/{tv_show_name_sanitized}'
      thumbnail_name: '{episode_file_path}-thumb.jpg'
    overrides:
      download_range: 2months
      episode_date_standardized: '{upload_date_standardized}'
      episode_file_name: s{season_number_padded}.e{episode_number_padded} - {uid_sanitized}
      episode_file_path: Season {season_number_padded}/{episode_file_name}
      episode_number: '{upload_month}{upload_day_padded}{upload_date_index_padded}'
      episode_number_padded: '{upload_month_padded}{upload_day_padded}{upload_date_index_padded}'
      episode_plot: '{description}'
      episode_title: '{upload_date_standardized} - {title}'
      episode_year: '{upload_year}'
      file_name: '{title_sanitized}_[{uid}].{ext}'
      season_number: '{upload_year}'
      season_number_padded: '{season_number}'
      season_poster_file_name: season{season_number_padded}-poster.jpg
      season_title: '{season_number_padded}'
      tv_show_directory: /yt-tv
      tv_show_fanart_file_name: fanart.jpg
      tv_show_genre: DIY
      tv_show_name: WTF1
      tv_show_poster_file_name: poster.jpg
      url: https://www.youtube.com/playlist?list=PLB-vNGnkFt6wV5UF7pDSr--OgIxIfPvqL
    preset:
    - _episode_video_tags
    - _episode_nfo_tags
    - _jellyfin_tv_show
    - _tv_show_by_date
    - _episode_base
    - _season_by_year
    - jellyfin_tv_show_by_date
    - season_by_year__episode_by_month_day
    - tv_show
    - only_recent_videos
    video_tags:
      tags:
        date: '{episode_date_standardized}'
        episode_id: '{episode_number}'
        genre: '{tv_show_genre}'
        season_number: '{season_number}'
        show: '{tv_show_name}'
        synopsis: '{episode_plot}'
        title: '{episode_title}'
        year: '{episode_year}'
    ytdl_options:
      break_on_existing: true
      break_on_reject: true
      format: bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best

[ytdl-sub:downloader] ytdl_options: {'ignoreerrors': True, 'outtmpl': '.ytdl-sub-downloads/wtf1/%(id)s.%(ext)s', 'download_archive': '.ytdl-sub-downloads/wtf1/.ytdl-subscribe-wtf1-download-archive.txt', 'writethumbnail': False, 'daterange': <yt_dlp.utils.DateRange object at 0x7f5697e6bfa0>, 'break_on_reject': True, 'postprocessors': [{'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}, {'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}], 'break_on_existing': True, 'format': 'bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', 'writeinfojson': True, 'skip_download': True}
[ytdl-sub:yt-dlp] [youtube:tab] PLB-vNGnkFt6wV5UF7pDSr--OgIxIfPvqL: Downloading webpage
[ytdl-sub:yt-dlp] [youtube:tab] PLB-vNGnkFt6wV5UF7pDSr--OgIxIfPvqL: Downloading API JSON with unavailable videos
[ytdl-sub:yt-dlp] [download] Downloading playlist: F101
[ytdl-sub:yt-dlp] [download] Downloading playlist: F101
[ytdl-sub:yt-dlp] [info] Writing playlist metadata as JSON to: .ytdl-sub-downloads/wtf1/PLB-vNGnkFt6wV5UF7pDSr--OgIxIfPvqL.info.json
[ytdl-sub:yt-dlp] [youtube:tab] Playlist F101: Downloading 66 videos of 66
[ytdl-sub:yt-dlp] [download] Downloading video 1 of 66
[ytdl-sub:yt-dlp] [youtube] 1wpGljiiLeE: Downloading webpage
[ytdl-sub:downloader] Downloading metadata for F101
[ytdl-sub:yt-dlp] [youtube] 1wpGljiiLeE: Downloading android player API JSON
[ytdl-sub:yt-dlp] [download] 2022-07-13 upload date is not in range 2022-10-23 - 9999-12-31
```

If I read that right, is it complining the download is too old?  This has been running in this config for months though, an dnever downloaded anything.

**Comment by psyciknz** [comment]
With debug, and with suggested (from discord set the break_on_reject: false)
```
[ytdl-sub] Beginning subscription download for wtf1
[ytdl-sub] Subscription full yaml:
presets:
  wtf1:
    chapters:
      embed_chapters: true
    date_range:
      after: today-{download_range}
    generic:
      playlist_thumbnails:
      - name: '{tv_show_poster_file_name}'
        uid: avatar_uncropped
      - name: '{tv_show_fanart_file_name}'
        uid: banner_uncropped
      url: '{url}'
    nfo_tags:
      nfo_name: '{episode_file_path}.nfo'
      nfo_root: episodedetails
      tags:
        aired: '{episode_date_standardized}'
        episode: '{episode_number}'
        genre: '{tv_show_genre}'
        plot: '{episode_plot}'
        season: '{season_number}'
        title: '{episode_title}'
        year: '{episode_year}'
    output_directory_nfo_tags:
      nfo_name: tvshow.nfo
      nfo_root: tvshow
      tags:
        genre: '{tv_show_genre}'
        title: '{tv_show_name}'
    output_options:
      file_name: '{episode_file_path}.{ext}'
      keep_files_after: today-{download_range}
      maintain_download_archive: true
      output_directory: '{tv_show_directory}/{tv_show_name_sanitized}'
      thumbnail_name: '{episode_file_path}-thumb.jpg'
    overrides:
      download_range: 2months
      episode_date_standardized: '{upload_date_standardized}'
      episode_file_name: s{season_number_padded}.e{episode_number_padded} - {uid_sanitized}
      episode_file_path: Season {season_number_padded}/{episode_file_name}
      episode_number: '{upload_month}{upload_day_padded}{upload_date_index_padded}'
      episode_number_padded: '{upload_month_padded}{upload_day_padded}{upload_date_index_padded}'
      episode_plot: '{description}'
      episode_title: '{upload_date_standardized} - {title}'
      episode_year: '{upload_year}'
      file_name: '{title_sanitized}_[{uid}].{ext}'
      season_number: '{upload_year}'
      season_number_padded: '{season_number}'
      season_poster_file_name: season{season_number_padded}-poster.jpg
      season_title: '{season_number_padded}'
      tv_show_directory: /yt-tv
      tv_show_fanart_file_name: fanart.jpg
      tv_show_genre: DIY
      tv_show_name: WTF1
      tv_show_poster_file_name: poster.jpg
      url: https://www.youtube.com/playlist?list=PLB-vNGnkFt6wV5UF7pDSr--OgIxIfPvqL
    preset:
    - _episode_video_tags
    - _episode_nfo_tags
    - _jellyfin_tv_show
    - _tv_show_by_date
    - _episode_base
    - _season_by_year
    - jellyfin_tv_show_by_date
    - season_by_year__episode_by_month_day
    - tv_show
    - only_recent_videos
    video_tags:
      tags:
        date: '{episode_date_standardized}'
        episode_id: '{episode_number}'
        genre: '{tv_show_genre}'
        season_number: '{season_number}'
        show: '{tv_show_name}'
        synopsis: '{episode_plot}'
        title: '{episode_title}'
        year: '{episode_year}'
    ytdl_options:
      break_on_existing: true
      break_on_reject: false
      format: bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best

[ytdl-sub:downloader] ytdl_options: {'ignoreerrors': True, 'outtmpl': '.ytdl-sub-downloads/wtf1/%(id)s.%(ext)s', 'download_archive': '.ytdl-sub-downloads/wtf1/.ytdl-subscribe-wtf1-download-archive.txt', 'writethumbnail': False, 'daterange': <yt_dlp.utils.DateRange object at 0x7fc97649f520>, 'break_on_reject': False, 'postprocessors': [{'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}, {'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}], 'break_on_existing': True, 'format': 'bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', 'writeinfojson': True, 'skip_download': True}
[ytdl-sub:yt-dlp] [youtube:tab] PLB-vNGnkFt6wV5UF7pDSr--OgIxIfPvqL: Downloading webpage
[ytdl-sub:yt-dlp] [youtube:tab] PLB-vNGnkFt6wV5UF7pDSr--OgIxIfPvqL: Downloading API JSON with unavailable videos
[ytdl-sub:yt-dlp] [download] Downloading playlist: F101
[ytdl-sub:yt-dlp] [info] Writing playlist metadata as JSON to: .ytdl-sub-downloads/wtf1/PLB-vNGnkFt6wV5UF7pDSr--OgIxIfPvqL.info.json
[ytdl-sub:yt-dlp] [youtube:tab] Playlist F101: Downloading 66 videos of 66
[ytdl-sub:yt-dlp] [download] Downloading video 1 of 66
[ytdl-sub:yt-dlp] [youtube] 1wpGljiiLeE: Downloading webpage
[ytdl-sub:downloader] Downloading metadata for F101
[ytdl-sub:yt-dlp] [youtube] 1wpGljiiLeE: Downloading android player API JSON
[ytdl-sub:yt-dlp] [download] 2022-07-13 upload date is not in range 2022-10-23 - 9999-12-31
```

And it continues.   Just been no videos.
