### ISSUE TITLE
Ability to embed video files, avoid writing thumbnail files

### ISSUE THREAD

**Issue by martinspaniol** [jmbannon/ytdl-sub#403]
I have two questions regarding thumbnails. I have the following subscriptions.yaml file:
```yaml
test:
  preset:
    - "plex_tv_show_collection"
    - "season_by_collection__episode_by_year_month_day" 
    - "collection_season_1"
  overrides:
    tv_show_name: "Test Show"
    tv_show_directory: "/share1/Downloads"
    collection_season_1_url: "https://www.youtube.com/playlist?list=PL5BC0FC26BECA5A35"
    collection_season_1_name: "Season for Testing"
```
This results in the following folders and files:
```
root@666fd5b56487:/config# tree /share1/Downloads/Test\ Show/
/share1/Downloads/Test Show/
├── Season 01
│   ├── s01.e11020101 - 0SVukUyys10-thumb.jpg
│   ├── s01.e11020101 - 0SVukUyys10.mp4
│   ├── s01.e11022701 - qPybBrXspds-thumb.jpg
│   ├── s01.e11022701 - qPybBrXspds.mp4
│   ├── s01.e11032101 - DBjFvs6HafU-thumb.jpg
│   └── s01.e11032101 - DBjFvs6HafU.mp4
└── Season01.jpg
```
I know that I can embed the episode thumbnails `-thumb.jpg`files with the following:
```
ytdl_options:
  postprocessors:
    - key: "EmbedThumbnail"
      when: "post_process"
```
When embedding the episode thumbnails, the `-thumb.jpg` files are created though. 
So the **first question** is, is there any way to prevent the creation of the `-thumb.jpg` files without changing the prebuilt presets? Is there any way to override the `thumbnail_name` in `episode.yaml`to `null` so the episode thumbnails are not created?

Note: Embedding thumbnails could be easier to use in general. Maybe you could implement it the same way as `embed_subtitles`.

If I change the `collection_season_1_url` to `https://www.youtube.com/playlist?list=PLtgLx2K6W8-CZDpth3ddOfURE4PwMWeFl` the season thumbnail is not present:
```
root@666fd5b56487:/config# tree /share1/Downloads/Test\ Show/
/share1/Downloads/Test Show/
└── Season 01
    ├── s01.e20082401 - TI9VPiURd0U-thumb.jpg
    ├── s01.e20082401 - TI9VPiURd0U.mp4
    ├── s01.e20110901 - xnVbJzkTCsE-thumb.jpg
    └── s01.e20110901 - xnVbJzkTCsE.mp4
```
So the **second question** is, any idea why there is no season thumbnail for this url?
