### ISSUE TITLE
Season name not reflected in plex

### ISSUE THREAD

**Issue by martinspaniol** [jmbannon/ytdl-sub#404]
I'm using the following `subscriptions.yaml` file:
```yaml
test:
  preset:
    - "plex_tv_show_collection"
    - "season_by_collection__episode_by_year_month_day" 
    - "collection_season_1"
  overrides:
    tv_show_name: "Test Show"
    tv_show_directory: "/share1/Downloads"
    collection_season_1_url: "https://www.youtube.com/playlist?list=PL5BC0FC26BECA5A35"
    collection_season_1_name: "Season for Testing"
```
This uses the prebuilt preset `collection_season_1` which should create an nfo file with the season name ("Season for Testing") in it:
```yaml
    output_directory_nfo_tags:
      tags:
        namedseason:
          - tag: "{collection_season_1_name}"
            attributes:
              number: "1"
```
Unfortunately no nfo file is being created this way. Also in my plex library the season is just called "Season 1". I could manually update the season name within plex but I thought ytdl-sub would do this. What am I doing wrong? Is there any way to reflect the season name from the yaml file in plex?
