### ISSUE TITLE
Updating date range has no effect

### ISSUE THREAD

**Issue by mcarlton00** [jmbannon/ytdl-sub#410]
When using a `date_range` in a preset, updating the time value after the initial download doesn't have any effect.

Full config files: https://gist.github.com/mcarlton00/890124d6aa6dc091740f0125a87c4841

```yaml
  recent:
    date_range:
      before: "today"
      after: "today-{download_range}"
    overrides:
      download_range: "2weeks"
```

When downloading a channel with this preset, it will download the specified `download_range` videos during the first run.  However, if the time range is updated to a longer period, say `3weeks` as an example (either in the preset or in the overrides of the channel itself) it doesn't download any other videos that match the new range.
