### ISSUE TITLE
Working directory lock error

### ISSUE THREAD

**Issue by emteedubs** [jmbannon/ytdl-sub#423]
Keep getting the following error. I host my volume on a Synology NAS for which the main server connects to via NFS. When I change the directory it will often download with no issues the first time. But after that, subsequent times this error will continue to happen. Any advice? Thank you in advance.

**Error**
```
[ytdl-sub] An uncaught error occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ytdl_sub/main.py", line 28, in main
    _main()
  File "/usr/lib/python3.10/site-packages/ytdl_sub/main.py", line 19, in _main
    ytdl_sub.cli.main.main()
  File "/usr/lib/python3.10/site-packages/ytdl_sub/cli/main.py", line 172, in main
    with _working_directory_lock(config=config):
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.10/site-packages/ytdl_sub/cli/main.py", line 138, in _working_directory_lock
    lock_file = open(lock_file_path, "w", encoding="utf-8")
PermissionError: [Errno 13] Permission denied: '/tmp/_data_downloads_ytdl_sub'
[ytdl-sub] Please upload the error log file '/tmp/ytdl-sub.1zm2n8ay' and make a Github issue at https://github.com/jmbannon/ytdl-sub/issues with your config and command/subsc>
```

**Config**
```configuration:
  working_directory: "/data/downloads/ytdl_sub"

presets:

  # Preset for Cantonese TV shows
  tv_show_cantonese:
    preset:
      - "tv_show"

    overrides:
      tv_show_directory: "/data/media/tv/chinese/cantonese"

  # Preset for Mandarin TV shows
  tv_show_mandarin:
    preset:
      - "tv_show"

    overrides:
      tv_show_directory: "/data/media/tv/chinese/mandarin"

  # Preset for English TV shows
  tv_show_english:
    preset:
      - "tv_show"

    overrides:
      tv_show_directory: "/data/media/tv/english"

  # Your main TV show preset - all your tv show subscriptions will use this.
  tv_show:
    preset:
      - "plex_tv_show_by_date"  # replace with desired player type

      - "season_by_year__episode_by_month_day"  # replace with desired season/episode format

    ytdl_options:
      # cookiefile: "/config/cookie_file.txt"  # replace with actual cookie file path
      break_on_existing: True
      maintain_download_archive: True
      windowsfilenames: True
      merge_output_format: "mp4"

    overrides:
      tv_show_directory: "/data/media/tv/"  # replace with path to tv show directory
  
####################################################################################################

  # Preset to only download and keep recent videos
  only_recent_videos:

    # Only download videos within the download_range
    date_range:
      after: "today-{download_range}"

    # Stops fetching metadata if the video is out of range (saves time + bandwidth)
    ytdl_options:
      break_on_reject: True

    # Deletes any videos older than download_range. WARNING: do not use
    # "season_by_year__episode_by_download_index" if you plan to delete older videos
    output_options:
      keep_files_after: "today-{download_range}"

    # Set the duration of download_range, defaults to 2 months
    overrides:
      download_range: "3months"

####################################################################################################

  # Preset to download subtitles (either by file or embedded)
  add_subtitles:
    subtitles:

      subtitles_name: "{episode_file_path}.{lang}.{subtitles_ext}"
      subtitles_type: "srt"

      languages: # supports list of multiple languages
        - "en"
        - "zh-tw"
        - "zh-cn"
      allow_auto_generated_subtitles: True  # allow auto subtitles

####################################################################################################

  # Preset to cut sponsor segments from videos
  sponsorblock:
    chapters:

      sponsorblock_categories:
        - "intro"
        - "outro"
        - "selfpromo"
        - "preview"
        - "interaction"
        - "sponsor"
        - "music_offtopic"
      remove_sponsorblock_categories: "all"
      force_key_frames: False

####################################################################################################

  # Preset for the hoarders who want to also save the info.json file
  include_info_json:
    output_options:
      info_json_name: "{episode_file_path}.{info_json_ext}"
```

***Sub:***
```
奔跑吧 (2014) [tvdb-311425]:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show_mandarin" # Options: "tv_show_cantonese", "tv_show_mandarin", "tv_show_english"
    - "add_subtitles"
    - "only_recent_videos" # Enable for variety shows
    - "sponsorblock"
    # - "include_info_json"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "奔跑吧 (2014) [tvdb-311425]" # Used to generate show folder name
    url: "https://www.youtube.com/playlist?list=PLwIAzDfsrXYyK-wxhAaq7wEa-7d7xEfLH"
    # Optional - can be modified from their default value
    tv_show_genre: "Variety"
    # episode_title: "{upload_date_standardized} - {title}"
    # episode_description: "{webpage_url}"
```

**Comment by jmbannon** [comment]
This is not a config issue, it's a Docker/permission issue. What does your docker compose look like? My suggestion is to have the volume of the container on the same machine that it runs on.

**Comment by emteedubs** [comment]
Here's my docker compose. All my other docker services run off my NFS mounted volumes on my NAS without issue including MeTube. Storage on my local machine is only for VM data, and everything I download will need to be on the NAS. So I would prefer not have to find another service to copy the downloaded videos from my local storage back on to the NAS. Are there other suggestions I can try?

```
  ytdl-sub:
    image: ghcr.io/jmbannon/ytdl-sub:latest
    container_name: ytdl-sub
    restart: unless-stopped
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/appdata/ytdl-sub/config:/config
      - $DATADIR:/data
      # ensure directories have root permissions for automating downloads
      - $DOCKERDIR/appdata/ytdl-sub/crontab_files:/etc/crontabs
      - $DOCKERDIR/appdata/ytdl-sub/custom-services.d:/custom-services.d
      - $DOCKERDIR/appdata/ytdl-sub/custom-cont-init:/custom-cont-init.d
    networks:
      - traefik_proxy
```
