### ISSUE TITLE
Create `best_video` preset

### ISSUE THREAD

**Issue by jmbannon** [jmbannon/ytdl-sub#466]
```
ytdl_options:
    format: "bestvideo+bestaudio/best"
    merge_output_format: "mp4"
    remux_video:"mp4"
```
