### ISSUE TITLE
capture_group_if_match value (opposite of capture_group_defaults) 

### ISSUE THREAD

**Issue by Behem07h** [jmbannon/ytdl-sub#479]
currently, capture groups are only useful for metadata or file names, as their value if the regex is a match cannot be standardized. I propose that a capture_group_if_match value (or something to this effect) be added, which would take the place of the capture group value if the regex were a match.

for example:
`
regex:
    from:
        title:
            match:
                - ((?:^|\W)Instrumental(?:$|\W))/gi #captures "Instrumental"
                capture_group_names:
                - "captured_is_instrumental" #might need to find a way to standardize the caps here
                capture_group_defaults:
                - ""
                capture_group_if_match:
                - "/Instrumental"
output_options:
    output_directory: "{mv_dir}"
    file_name: "{captured_is_instrumental}/{mv_artist}/{mv_file_name}.{ext}"
`
this would put any videos with "instrumental" in the title into a subdirectory titled "Instrumental".
were this done without a capture_group_if_match, you would end up with varying subdirectories with different variations of "instrumental", such as "[Instrumental]", "INSTRUMENTAL", "Instrumental" etc

**Comment by jmbannon** [comment]
If I understand correctly, then in other words, have a capture group be able to output a different value other than the capture itself.

I like this idea a lot actually. We could make it work by doing:
```
# For each entry's `description` value...
        description:
          # Match with capture groups and defaults.
          # This tries to scrape a date from the description and produce new
          # source variables
          match:
           - "([0-9]{4})-([0-9]{2})-([0-9]{2})"

          # Each capture group creates these new source variables, respectively,
          # as well a sanitized version, i.e. `captured_upload_year_sanitized`
          capture_group_names:
           - "captured_upload_year"
           - "captured_upload_month"
           - "captured_upload_day"

          # And if the string does not match, use these as respective default
          # values for the new source variables.
          capture_group_defaults:
            - "{upload_year}"
            - "{upload_month}"
            - "{upload_day}"
          
          # For each regex capture, set its output variable to this
          capture_group_outputs:
            - "{captured_upload_year}"
            - "{captured_upload_month}"
            - "{captured_upload_day}"
```            
So by default, the regex capture just outputs itself like the example above. But also gives you the ability to set it to a static string, like "Instrumental" in your case
