### ISSUE TITLE
How override yt_dlp format options?

### ISSUE THREAD

**Issue by webysther** [jmbannon/ytdl-sub#486]
How I can pass this option for yt_dlp on ytdl-sub?

`yt-dlp -f "(bv*[vcodec~='^((he|a)vc|h26[45])']+ba) / (bv*+ba/b)"`

BTW: great option to download auto generated sub and put in the correct format. <3

**Comment by webysther** [comment]
```yaml
    ytdl_options:
      break_on_reject: True
      format: "(bv*[vcodec~='^((he|a)vc|h26[45])']+ba) / (bv*+ba/b)"
```
