### ISSUE TITLE
Add docs on how to not download poster + fanart in prebuilt presets

### ISSUE THREAD

**Issue by jmbannon** [jmbannon/ytdl-sub#506]

**Comment by xlyralycanx** [comment]
I want to know *how to* download these for playlists, my install doesn't and idk which preset to use

**Comment by jmbannon** [comment]
> I want to know _how to_ download these for playlists, my install doesn't and idk which preset to use

It should by default for playlists. Create a new issue with debug logs and we can look there

**Comment by markalex2209** [comment]
Doesn't 
```yml
    overrides:
      tv_show_fanart_file_name: ""
      tv_show_poster_file_name: ""
```
already achieve this?
