### ISSUE TITLE
Add default `ytdl_options` and `output_options` for certain download_strategy

### ISSUE THREAD

**Issue by jmbannon** [jmbannon/ytdl-sub#53]
Youtube channel + playlist should include
```
ytdl_options:
  breakonexisting: True 
  breakonreject: True
output_options:
  maintain_download_archive: True  # global default False
```
Soundcloud discography should include
```
output_options:
  maintain_download_archive: True 
```
by default, and have this documented in the download strategy section.

This should help reduce YAML redundancy for fields that will most likely always be enabled for particular download strategies.
