### ISSUE TITLE
download_strategy validation error

### ISSUE THREAD

**Issue by jmbannon** [jmbannon/ytdl-sub#584]
```
configuration:
  working_directory: '/tmp/ytdl-sub-downloads'
  dl_aliases:
    video: "--preset yt_video"
    video-url: "--download.url"
    # changed from video-type: "--overrides.video_type"
    tv-show-name: "--overrides.tv_show_name"

presets:
  yt_video:
    download:
      download_strategy: "url"

    output_options:
      # changed from "/config/first_config/output_videos"
      output_directory: "/media/{tv_show_name_sanitized}"
      # changed from "{video_path}.{ext}"
      file_name: "{episode_path}.{ext}"
      # changed from "{video_path}.{thumbnail_ext}"
      thumbnail_name: "{episode_path}-thumb.{thumbnail_ext}"
      
    nfo_tags:
      nfo_name: "{episode_path}.nfo"
      nfo_root: "episodedetails"
      tags:
        title: "{title}"
        season: "{season}"
        episode: "{episode}"
        year: "{upload_year}"
        aired: "{upload_date_standardized}"
    
    output_directory_nfo_tags:
      nfo_name: "tvshow.nfo"
      nfo_root: "tvshow"
      tags:
        title: "{tv_show_name}"
      
    overrides:
      tv_show_name: "OVERRIDE IN SUBSCRIPTION"
      season: "{upload_year}"
      episode: "{upload_month}{upload_day_padded}"
      episode_padded: "{upload_month_padded}{upload_day_padded}"
      episode_file_name: "s{season}e{episode_padded}.{title_sanitized}"
      episode_path: "Season {season}/{episode_file_name}"
      
  yt_playlist:
    preset: "yt_video"
    output_options:
      maintain_download_archive: True
    ytdl_options:
      break_on_existing: True

  yt_channel:
    preset: "yt_playlist"
    # added: downloads channel avatar and banner to the output directory
    download:
       playlist_thumbnails:
        - name: "poster.jpg"
          uid: "avatar_uncropped"
        - name: "banner.jpg"
          uid: "banner_uncropped"
      
  recent_videos:
    preset:
      - "yt_playlist"
    date_range:
      after: "now-6months"
```
returns
```
[ytdl-sub] Validation error in yt_channel.download: missing the required field 'download_strategy'
```
