### ISSUE TITLE
episode_title not working right with Plex

### ISSUE THREAD

**Issue by timbroder** [jmbannon/ytdl-sub#597]
This is very likely user error, but my episode titles in Plex aren't using the title's of the youtube episodes.

For testing I made a sample playlist [here](https://www.youtube.com/playlist?list=PLX6lyBnpvNQ3KTC-b7gO_lyivJ8osqId6). It has [this](https://www.youtube.com/watch?v=4vmRBi48u_s&list=PLX6lyBnpvNQ3KTC-b7gO_lyivJ8osqId6&index=1&t=2s) one video in it

Using the config below, I thought I would have had a title similar to `Demon's Souls Boss 1-1: Phalanx`, but it has `Episode 31901`. 

What did I do wrong?

![CleanShot 2023-04-25 at 15 01 37@2x](https://user-images.githubusercontent.com/121503/234376920-c3e02401-b17f-4acc-86d6-b78836fde922.png)

I've also tried:
* Using the `plex_tv_show_by_date` preset with `season_by_year__episode_by_month_day` 
* Using the `plex_tv_show_by_date` preset with `_season_by_year` and with and without `episode_number` and `episode_number_padded`

# config.yaml

```
configuration:
  working_directory: "/config/.ytdl-sub-downloads"

presets:
  tv_show:
    preset:
      - "plex_tv_show_by_date"
      - "_season_by_year"
    overrides:
      tv_show_directory: "/tv_kids"  # replace with path to tv show directory
      episode_title: "{title}"
      episode_number: "{upload_month}{upload_day_padded}{upload_date_index_padded}"
      episode_number_padded: "{upload_month_padded}{upload_day_padded}{upload_date_index_padded}"
    output_options:
      maintain_download_archive: True
    ytdl_options:
      break_on_existing: True
```

# subscriptions.yaml

```
er:
  preset:
    - "tv_show"

  overrides:
    tv_show_name: "ERing"
    url: "https://www.youtube.com/playlist?list=PLX6lyBnpvNQ3KTC-b7gO_lyivJ8osqId6"
```

**Comment by catduckgnaf** [comment]
I think you have to many things, Try with just

```
configuration:
  working_directory: "/config/.ytdl-sub-downloads"

presets:
  tv_show:
    preset:
      - "plex_tv_show_by_date"
    overrides:
      tv_show_directory: "/tv_kids"  # replace with path to tv show directory
    output_options:
      maintain_download_archive: True
    ytdl_options:
      break_on_existing: True
```

**Comment by timbroder** [comment]
@catduckgnaf Thanks, I tried that. When I ran that I got this, which is why I started adding things:


```
[ytdl-sub] Validation error in minecraft_universe_top_ten.output_options.file_name: Format variable 'season_number_padded' does not exist. Available variables: channel, channel_id, channel_sanitized, creator, creator_sanitized, description, download_index, download_index_padded6, episode_date_standardized, episode_date_standardized_sanitized, episode_file_name, episode_file_name_sanitized, episode_file_path, episode_file_path_sanitized, episode_plot, episode_plot_sanitized, episode_title, episode_title_sanitized, episode_year, episode_year_sanitized, epoch, epoch_date, epoch_hour, ext, extractor, file_title, file_title_sanitized, file_uid, file_uid_sanitized, info_json_ext, playlist_count, playlist_description, playlist_index, playlist_index_padded, playlist_index_padded6, playlist_index_reversed, playlist_index_reversed_padded, playlist_index_reversed_padded6, playlist_max_upload_year, playlist_max_upload_year_truncated, playlist_title, playlist_title_sanitized, playlist_uid, playlist_uploader, playlist_uploader_id, playlist_uploader_sanitized, playlist_uploader_url, playlist_webpage_url, season_poster_file_name, season_poster_file_name_sanitized, season_title, season_title_sanitized, source_count, source_description, source_index, source_index_padded, source_title, source_title_sanitized, source_uid, source_uploader, source_uploader_id, source_uploader_url, source_webpage_url, thumbnail_ext, title, title_sanitized, title_sanitized_plex, tv_show_directory, tv_show_directory_sanitized, tv_show_fanart_file_name, tv_show_fanart_file_name_sanitized, tv_show_genre, tv_show_genre_sanitized, tv_show_name, tv_show_name_sanitized, tv_show_poster_file_name, tv_show_poster_file_name_sanitized, uid, uid_sanitized, uid_sanitized_plex, upload_date, upload_date_index, upload_date_index_padded, upload_date_index_reversed, upload_date_index_reversed_padded, upload_date_standardized, upload_day, upload_day_of_year, upload_day_of_year_padded, upload_day_of_year_reversed, upload_day_of_year_reversed_padded, upload_day_padded, upload_day_reversed, upload_day_reversed_padded, upload_month, upload_month_padded, upload_month_reversed, upload_month_reversed_padded, upload_year, upload_year_truncated, upload_year_truncated_reversed, uploader, uploader_id, uploader_url, url, url10, url10_sanitized, url11, url11_sanitized, url12, url12_sanitized, url13, url13_sanitized, url14, url14_sanitized, url15, url15_sanitized, url16, url16_sanitized, url17, url17_sanitized, url18, url18_sanitized, url19, url19_sanitized, url2, url20, url20_sanitized, url2_sanitized, url3, url3_sanitized, url4, url4_sanitized, url5, url5_sanitized, url6, url6_sanitized, url7, url7_sanitized, url8, url8_sanitized, url9, url9_sanitized, url_sanitized, webpage_url
```

**Comment by catduckgnaf** [comment]
You should not have the word "padded" anywhere. Also make sure your output folder is correct. Please double check and compare. You should "need" nothing, but the one plex preset.

**Comment by timbroder** [comment]
Additional info:

```
ytdl-sub -v
ytdl-sub 2023.04.20+d5d9978
```

Installed via docker, and I am running my command, `ytdl-sub sub` from within the `/config` dir

```
  ytdl-sub:
    image: ghcr.io/jmbannon/ytdl-sub:ubuntu-latest
    container_name: ytdl-sub
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - DOCKER_MODS=linuxserver/mods:universal-cron
    volumes:
      - /mnt/ytdlsub/config:/config
      - /mnt/nas/media2/Video/tv_kids/:/tv_kids  # optional
    devices:
      - /dev/dri:/dev/dri  # CPU passthrough
    restart: unless-stopped
```

**Comment by catduckgnaf** [comment]
See the image I got, with the code below. in a test run. Also as much as I love demon souls, probably shouldn't have it under "Children TV" :)

![image](https://user-images.githubusercontent.com/129601174/234396154-a6f343f0-eab2-423b-aaef-fe047b1a0338.png)


```
configuration:
  working_directory: '/tmp/ytdl-sub-downloads'

presets:

  tv_show:
    preset:

      - "plex_tv_show_by_date"  # replace with desired player type

      # Choose one of the following season/episode formats:
      # - "season_by_year__episode_by_month_day"
      # - "season_by_year_month__episode_by_day"
      # - "season_by_year__episode_by_month_day_reversed"
      # - "season_by_year__episode_by_download_index"

      - "season_by_year__episode_by_download_index"  # replace with desired season/episode format
      - "include_info_json"
      - "enable_archive"


    overrides:
      tv_show_directory: "/childrentv_shows"  


####################################################################################################

  # Preset to only download and keep recent videos
  only_recent_videos:

    # Only download videos within the download_range
    date_range:
      after: "today-{download_range}"

    # Stops fetching metadata if the video is out of range (saves time + bandwidth)
    ytdl_options:
      break_on_reject: True

    # Deletes any videos older than download_range. WARNING: do not use
    # "season_by_year__episode_by_download_index" if you plan to delete older videos
    output_options:
      keep_files_after: "today-{download_range}"

    # Set the duration of download_range, defaults to 2 months
    overrides:
      download_range: "2months"

####################################################################################################

  # Preset to download subtitles (either by file or embedded)
  add_subtitles:
    subtitles:
      # Embed subtitles into the video
      embed_subtitles: True
      # And/or download them as a file. Uncomment to download as file:
      # subtitles_name: "{episode_file_path}.{lang}.{subtitles_ext}"
      # subtitles_type: "srt"

      languages: "en"  # supports list of multiple languages
      allow_auto_generated_subtitles: True  # allow auto subtitles

####################################################################################################

  # Preset to cut sponsor segments from videos
  sponsorblock:
    # If you download using cron, it is wise to add a delay before downloading ad-filled content to
    # give folks time to submit sponsor segments. Uncomment to wait 2 days before download a video.
    # date_range:
    #  before: "today-2days"

    chapters:
      # Remove all of these sponsorblock categories
      sponsorblock_categories:
        - "intro"
        - "outro"
        - "selfpromo"
        - "preview"
        - "interaction"
        - "sponsor"
        - "music_offtopic"
      remove_sponsorblock_categories: "all"
      force_key_frames: False

####################################################################################################

  # Preset for the hoarders who want to also save the info.json file
  include_info_json:
    output_options:
      info_json_name: "{episode_file_path}.{info_json_ext}"

####################################################################################################

  # Preset to maintan download archive
  enable_archive:
   output_options:
      maintain_download_archive: True 

 ####################################################################################################


```
