### ISSUE TITLE
Youtube Music config?

### ISSUE THREAD

**Issue by bpoulliot** [jmbannon/ytdl-sub#608]
Definitely a feature request and I have a few lined up after getting several server issues out of the way and finding some stability, but I am in the middle of a move, so will hold off on the deluge. This one is maybe more simple than I'm finding, but I'm unable to figure out how to grab enough information from a Youtube music artist channel (e.g., https://music.youtube.com/channel/UCPEA0kfpI53U9vmqnc9lJ-A) to separate content into albums. This doesn't appear to be information passed down in metadata:
```
iles created:
----------------------------------------
/tmp/ytdl-sub-view
  HhrByzlRhmI.jpg
  HhrByzlRhmI.webm
    Source Variables:
      channel: CAKE
      channel_id: UCPEA0kfpI53U9vmqnc9lJ-A
      channel_sanitized: CAKE
      creator: CAKE
      creator_sanitized: CAKE
      description: Provided to YouTube by Volcano/Legacy <newline>  <newline> Satan Is My Motor ...
      download_index: 1
      download_index_padded6: 000001
      epoch: 1684016241
      epoch_date: 20230513
      epoch_hour: 22
      ext: webm
      extractor: youtube
      info_json_ext: info.json
      playlist_count: 235
      playlist_description:
      playlist_index: 2
      playlist_index_padded: 02
      playlist_index_padded6: 000002
      playlist_index_reversed: 234
      playlist_index_reversed_padded: 234
      playlist_index_reversed_padded6: 000234
      playlist_max_upload_year: 2023
      playlist_max_upload_year_truncated: 23
      playlist_title: Uploads from Cake - Topic
      playlist_title_sanitized: Uploads from Cake - Topic
      playlist_uid: UUPEA0kfpI53U9vmqnc9lJ-A
      playlist_uploader: CAKE
      playlist_uploader_id: UCPEA0kfpI53U9vmqnc9lJ-A
      playlist_uploader_sanitized: CAKE
      playlist_uploader_url: https://www.youtube.com/@thebandcakeofficial
      playlist_webpage_url: https://www.youtube.com/playlist?list=UUPEA0kfpI53U9vmqnc9lJ-A
      source_count: 1
      source_description:
      source_index: 1
      source_index_padded: 01
      source_title: Uploads from Cake - Topic
      source_title_sanitized: Uploads from Cake - Topic
      source_uid: UUPEA0kfpI53U9vmqnc9lJ-A
      source_uploader: CAKE
      source_uploader_id: UCPEA0kfpI53U9vmqnc9lJ-A
      source_uploader_url: https://www.youtube.com/playlist?list=UUPEA0kfpI53U9vmqnc9lJ-A
      source_webpage_url: https://www.youtube.com/playlist?list=UUPEA0kfpI53U9vmqnc9lJ-A
      thumbnail_ext: jpg
      title: Satan Is My Motor
      title_sanitized: Satan Is My Motor
      title_sanitized_plex: Satan Is My Motor
      uid: HhrByzlRhmI
      uid_sanitized: HhrByzlRhmI
      uid_sanitized_plex: HhrByzlRhmI
      upload_date: 20230309
      upload_date_index: 1
      upload_date_index_padded: 01
      upload_date_index_reversed: 99
      upload_date_index_reversed_padded: 99
      upload_date_standardized: 2023-03-09
      upload_day: 9
      upload_day_of_year: 68
      upload_day_of_year_padded: 068
      upload_day_of_year_reversed: 298
      upload_day_of_year_reversed_padded: 298
      upload_day_padded: 09
      upload_day_reversed: 23
      upload_day_reversed_padded: 23
      upload_month: 3
      upload_month_padded: 03
      upload_month_reversed: 10
      upload_month_reversed_padded: 10
      upload_year: 2023
      upload_year_truncated: 23
      upload_year_truncated_reversed: 77
      uploader: Cake - Topic
      uploader_id: UCPEA0kfpI53U9vmqnc9lJ-A
      uploader_url: http://www.youtube.com/channel/UCPEA0kfpI53U9vmqnc9lJ-A
      webpage_url: https://www.youtube.com/watch?v=HhrByzlRhmI
```
This is all seen as one large album which is unhelpful for organizing and results in lots of duplicates (or seemingly duplicates, though some may be different versions or masters). I cannot figure out for the life of me how I might be able to descend into the playlists and grab that information from a subscription at the channel level...any thoughts?
