### ISSUE TITLE
Kodi only lists 3 episodes out of 103

### ISSUE THREAD

**Issue by grover77** [jmbannon/ytdl-sub#609]
config.yaml:
```
Limiting_Factor:
  # Inherit our `tv_show` preset we made above
  preset:
    - "tv_show"
  
  # Set override variables to set the channel URL and the
  # name we want to give the TV show.
  overrides:
    tv_show_name: "Limiting_Factor"
    url: "https://www.youtube.com/@thelimitingfactor"
```
In config.yaml I have `- "kodi_tv_show_by_date"`, I commented out jellyfin and plex.

```
➜  Limiting_Factor ls -l * | grep webm | wc -l
     101
➜  Limiting_Factor ls -l * | grep mkv | wc -l 
       2
```
All 103 episodes have `-thumb.jpg`, `.info.json`, `.nfo`, and `.webm` or `.mkv` files. Only three of these episodes show up in Kodi under tv services after indexing. If I go into file manager and browse I can play any of the 103 episodes.

I'm running via docker-compose. I used:
```
docker exec -it ytdl-sub /bin/bash
cd config/
ytdl-sub sub subscriptions.yaml
```

ytdl-sub output (after it download all episodes:
```
[ytdl-sub] Beginning subscription download for Limiting_Factor
[ytdl-sub:downloader] Beginning downloads for https://www.youtube.com/@thelimitingfactor
[ytdl-sub] No files changed for Limiting_Factor
[ytdl-sub] Download Summary:
Limiting_Factor         0 0 0     103 success
```
Kodi is build 20.1.0
