### ISSUE TITLE
[Question] Channel URL does not show all videos on page - therefore ytdl-sub does not download all channel videos

### ISSUE THREAD

**Issue by JohnEridium** [jmbannon/ytdl-sub#619]
Hi

I am downloading quite a few channels and may have stumbled over another "feature" of youtube.
For example, the channel "CraftComputing" has 639 videos, but when you actually count the videos on "https://www.youtube.com/@CraftComputing/videos", you only get 410. That is because the webpage only lists all 639 videos when you manually click on the "newest" button. 

is there some specific URL path/magic/etc. I can enter into my subscriptions file, that actually grabs all videos of a channel? This change on YouTube's side seems to be relatively recent because I have not encountered this before and could not find any issues with this here, on the yt-dlp repo or on r/DataHoarder. (config and subscription excerpt appended)
[demo-config.txt](https://github.com/jmbannon/ytdl-sub/files/11523282/demo-config.txt)
[subscription-excerpt.txt](https://github.com/jmbannon/ytdl-sub/files/11523285/subscription-excerpt.txt)

Any tips would be greatly appreciated.

Two more examples:
https://www.youtube.com/@williamosman/videos - 164 videos all in all, 100 downloaded
https://www.youtube.com/@lukemiani/videos - 670 videos all in all, 654 downloaded

**Comment by jmbannon** [comment]
This was a change in yt-dlp, it doesn't download live streams or shorts by default anymore. You can add those as additional URLs. See the example here where it uses `url2`: https://ytdl-sub.readthedocs.io/en/latest/presets.html#usage

**Comment by jmbannon** [comment]
You could also make a preset that populates.url, url2 and url2 with the videos/shorts/live stream pages, then have a single override for the 'base_url'. Would save you some lines :)

**Comment by JohnEridium** [comment]
I don’t think this is the issue here, another example is this channel:
https://www.youtube.com/@PorkchopMedia/videos

Over two thousand videos, but ytdl-sub only downloaded 107 videos and these were all released before shorts even existed.

**Comment by jmbannon** [comment]
Reopening, I think I misread the counts. Do you have a debug log by chance? If not try running with --log-level debug and I can take a look

**Comment by jmbannon** [comment]
What I would try first is:
- disable the reverse download option you have in output options
- disable break_on_existing

My guess is you're hitting a video that you have downloaded before from having 'download reverse' set to True, then interrupted. The next download invocation would hit it and break from break_on_existing.

It will do another full metadata download but should hopefully grab all the missing videos. Once you do, set break_on_existing back to true

**Comment by JohnEridium** [comment]
I removed the „break on existing“ part or rather set that to false and that seems to work for now

When there are some more completely downloaded channels I’ll close this issue

**Comment by jmbannon** [comment]
Awesome. And to correct myself above, leave download_reverse as True since that's the default

**Comment by JohnEridium** [comment]
Small update: i let my config/sub setup run for a few days and for some reason, it would only download a few videos from large channels at a time. Just now i separated two large channels into their own subscription file and that seems to work better now. Unfortunately i don't have logs from the weird runs because logs caused the script to crash at the very beginning, but if i keep getting stuck i'll gather those.

Thanks again for your support and the work you put into this project :D 

I'll keep this updated, but this may take a while :upside_down_face:

**Comment by jmbannon** [comment]
Use this prebuilt preset on all your initial channel downloads: https://ytdl-sub.readthedocs.io/en/latest/presets.html#chunk-initial-download

It will only download max_downloads worth of metadata and videos on each run. Once you get a majority of the vids, remove it from the subscription

**Comment by jmbannon** [comment]
For making ram usage more sane, there's not much we can do since a large portion of the usage comes from yt-dlp

**Comment by jmbannon** [comment]
Hmmm, can you post your config and subscriptions file? RAM shouldn't be this bad with that

**Comment by JohnEridium** [comment]
Yes, both are linked in my first comment 

Mabye deleting the few videos I already have plus the Download archive could help? Maybe ytdl is interpreting the channels no longer as „initial download“ since there are already files present

**Comment by jmbannon** [comment]
Have this be your config (though I highly recommend using the prebuilt presets):
```
configuration:
    working_directory: "/path/to/ytdl-sub-working-area"

presets:
    archive_channel:
        #preset:
            #- "jellyfin_tv_show_by_date"
            #- "season_by_year__episode_by_download_index"
            #- "best_video_quality"
        chapters:
            embed_chapters: True
            allow_chapters_from_comments: False
        download:
            download_strategy: "url"
            url: "{url}"
            playlist_thumbnails:
                - name: "{tv_show_name}/poster.jpg"
                  uid: "avatar_uncropped"
                - name: "{tv_show_name}/backdrop.jpg"
                  uid: "banner_uncropped"
        output_options:
            maintain_download_archive: True
            output_directory: "/data/USER/video/youtube-new/channels/"
            file_name: "{tv_show_name}/Season {upload_year}/S{upload_year}E{download_index} {title_sanitized}.{ext}"
            thumbnail_name: "{tv_show_name}/Season {upload_year}/S{upload_year}E{download_index} {title_sanitized}.{thumbnail_ext}"
            info_json_name: "{tv_show_name}/Season {upload_year}/S{upload_year}E{download_index} {title_sanitized}.{info_json_ext}"
        ytdl_options:
            format: "bestvideo[ext=mp4]+bestaudio[ext=m4a]"
            sleep_interval_subtitles: 5
            ignoreerrors: True
            break_on_existing: True
            cookiefile: "yt-cookies.txt"
            extractor_args:
                    youtube:
                      lang:
                        - "en"
        subtitles:
            embed_subtitles: True
            languages: ['all', '-live_chat']
            subtitles_type: "ass"
        video_tags:
            tags:
              title: "{title}"
              date: "{upload_date}"
              description: "{description}"

    japanese-music:
        preset:
            - "archive_channel"
        overrides:
            output_directory: "/data/USER/video/youtube-new/japanese-music/"
        output_options:
            output_directory: "{output_directory}"

    archive_playlist:
        preset:
            - "archive_channel"
        download:
            download_strategy: "url"
            url: "https://www.youtube.com/CHANNEL_ID"
            playlist_thumbnails:
                - name: "poster.jpg"
                  uid: "avatar_uncropped"
                - name: "backdrop.jpg"
                  uid: "banner_uncropped"
            source_thumbnails:
                - name: "poster.jpg"
                  uid: "avatar_uncropped"
                - name: "backdrop.jpg"
                  uid: "banner_uncropped"
```

Then a subscription be
```
LukeMiani:
    preset:
      - "archive_channel"
      - "chunk_initial_download"
    overrides:
        tv_show_name: "Luke Miani"
        tv_show_directory: "/data/USER/video/youtube-new/channels/Luke Miani"
        url: "https://www.youtube.com/@lukemiani"
```
Then remove `chunk_initial_download` once it's fully downloaded
