### ISSUE TITLE
Add plugin to capture string from the title via regex

### ISSUE THREAD

**Issue by jmbannon** [jmbannon/ytdl-sub#62]
```
my_preset:
  regex_capture:
    title:
      fail_if_not_captured: True  # or False, if all captures fail, fallback to original value of title
      capture:  # List of regex captures to try
      - "(.+) - (.+) [\[\(].*"
      - "(.+) - (.+)"
```
This would regex capture "Artist" and "Cool Song" from "Artist - Cool Song (Official Video)" into new source variables `title_capture_1` and `title_capture_2`
