### ISSUE TITLE
Change/further clarification for documentation example for match filter

### ISSUE THREAD

**Issue by Behem07h** [jmbannon/ytdl-sub#621]
https://ytdl-sub.readthedocs.io/en/latest/config.html?highlight=match%20filter#ytdl_sub.plugins.match_filters.MatchFiltersOptions
In the docs, it shows the following as being an example of using match filter with multiple entries:
```
presets:
  my_example_preset:
    match_filters:
      filters:
        - "original_url!*=/shorts/"
        - "!is_live"
```

it then goes on to say:
"The filters themselves. If used multiple times, the filter matches if at least one of the conditions are met."

Now if we take the latter statement to be true, this means that the example that the documentation provides will match the filter and thus download the video if the video is either not a short or not live. This essentially means the provided example is useless, as a short is never live and a livestream is never a short, and thus one of the two filters will always match. 
I believe this is either misleading phrasing, or either the example or explanation must be incorrect.
