### ISSUE TITLE
Unable to download channel as audio

### ISSUE THREAD

**Issue by CanisHelix** [jmbannon/ytdl-sub#629]
I'm trying to download a whole channel with playlists as Albums. But receive the following error:

`ytdl_sub.utils.exceptions.FileNotDownloadedException: Failed to find the extracted audio file`

The command I'm using is: `/usr/local/bin/ytdl-sub --config music_audio_config.yaml sub music_audio_subscriptions.yaml`

**config.yaml**
```yaml
configuration:
  working_directory: .ytdl-sub-downloads
  umask: '002'
presets:
  base:
    output_options:
      output_directory: '{music_directory}'
      file_name: '{track_full_path}'
      thumbnail_name: '{album_cover_path}'
      maintain_download_archive: true
    ytdl_options:
      break_on_existing: true
    audio_extract:
      codec: aac
      quality: 320
    music_tags:
      tags:
        artist: '{track_artist}'
        artists: '{track_artist}'
        albumartist: '{track_artist}'
        albumartists: '{track_artist}'
        title: '{track_title}'
        album: '{track_album}'
        track: '{track_number}'
        tracktotal: '{track_total}'
        year: '{track_year}'
        genre: '{track_genre}'
    overrides:
      track_title: '{title}'
      track_album: '{title}'
      track_artist: '{channel}'
      track_number: '1'
      track_number_padded: '01'
      track_total: '1'
      track_year: '{upload_year}'
      track_genre: Unset
      track_file_name: '{track_number_padded} - {track_title_sanitized}.{ext}'
      album_file_name: 'folder.{thumbnail_ext}'
      music_directory: /music
      artist_dir: '{track_artist_sanitized}'
      album_dir: '[{track_year}] {track_album_sanitized}'
      track_full_path: '{artist_dir}/{album_dir}/{track_file_name}'
      album_cover_path: '{artist_dir}/{album_dir}/{album_file_name}'
  single:
    preset: base
    download:
      download_strategy: url
      url: '{url}'
  albums_from_playlists:
    preset: single
    overrides:
      track_album: '{playlist_title}'
      track_number: '{playlist_index}'
      track_number_padded: '{playlist_index_padded}'
      track_total: '{playlist_count}'
      track_year: '{playlist_max_upload_year}'
  albums_from_chapters:
    preset: single
    chapters:
      embed_chapters: true
      allow_chapters_from_comments: true
    split_by_chapters:
      when_no_chapters: pass
    overrides:
      track_title: '{chapter_title}'
      track_album: '{title}'
      track_number: '{chapter_index}'
      track_number_padded: '{chapter_index_padded}'
      track_total: '{chapter_count}'
  soundcloud_discography:
    preset: base
    download:
      download_strategy: multi_url
      urls:
        - url: '{sc_artist_url}/tracks'
          variables:
            sc_track_album: '{title}'
            sc_track_number: '1'
            sc_track_number_padded: '01'
            sc_track_total: '1'
            sc_track_year: '{upload_year}'
        - url: '{sc_artist_url}/albums'
          variables:
            sc_track_album: '{playlist_title}'
            sc_track_number: '{playlist_index}'
            sc_track_number_padded: '{playlist_index_padded}'
            sc_track_total: '{playlist_count}'
            sc_track_year: '{playlist_max_upload_year}'
    overrides:
      track_album: '{sc_track_album}'
      track_number: '{sc_track_number}'
      track_number_padded: '{sc_track_number_padded}'
      track_total: '{sc_track_total}'
      track_year: '{sc_track_year}'
```

**subscriptions.yaml**
```yaml
music_of_40k:
  preset: albums_from_playlists
  regex:
    from:
      title:
        match:
          - ^(.*) | .*
        capture_group_names:
          - captured_track_title
        capture_group_defaults:
          - '{title}'
  overrides:
    url: 'https://www.youtube.com/@Musicof40K'
    track_artist: Music of 40K
    track_album: '{playlist_title}'
    track_title: '{captured_track_title}'
    track_genre: Ambient

```

[ytdl-sub.qqsem5ra.txt](https://github.com/jmbannon/ytdl-sub/files/11742727/ytdl-sub.qqsem5ra.txt)

**Comment by CanisHelix** [comment]
On a slightly different note, `track_album` in a `--dry-run` is coming through as "Music of 40K - Videos" instead of the expected playlist_title.

**Comment by CanisHelix** [comment]
Tried with just a single playlist instead of the whole channel, same error. (Much smaller log file for you to check)
[ytdl-sub.vtf1lj9v.txt](https://github.com/jmbannon/ytdl-sub/files/11744796/ytdl-sub.vtf1lj9v.txt)

config.yml
```yaml
# Each file will be properly tagged regardless of file extension (suppers flac, ogg, mp3, etc)
# and should show up nicely in music players that take advantage of tags.
configuration:
  working_directory: '.ytdl-sub-downloads'
  umask: "002"

presets:

  # The `base` preset that represents how all files will be structured after downloading.
  # Every other preset afterwards will inherit this preset.
  base:
    # Store all music under our music_directory (to be set as an override variable).
    # Store each resulting file with its full track path, and treat thumbnails as the album covers.
    #
    # Maintain a download archive. This will produce a hidden file in your music directory
    # containing an archive of all audio previously downloaded. This makes it so we do not
    # re-download files we already have.
    output_options:
      output_directory: "{music_directory}"
      file_name: "{track_full_path}"
      thumbnail_name: "{album_cover_path}"
      maintain_download_archive: True

    # Set break_on_existing to True. This will stop fetching any more metadata once we
    # hit a video/audio that we already have downloaded.
    ytdl_options:
      break_on_existing: True
      max_downloads: 30

    # Extract any audio from files using this codec and quality.
    audio_extract:
      codec: "aac"
      quality: 320

    # Set these music tags on every resulting audio file.
    # It is recommended to keep most of this as-is, and use override
    # variables to set them to be what you want.
    music_tags:
      tags:
        artist: "{track_artist}"
        artists: "{track_artist}"
        albumartist: "{track_artist}"
        albumartists: "{track_artist}"
        title: "{track_title}"
        album: "{track_album}"
        track: "{track_number}"
        tracktotal: "{track_total}"
        year: "{track_year}"
        genre: "{track_genre}"

    # For every configurable field, make it an override variable,
    # so we can carefully tune different use-cases by only modifying override variables.
    overrides:
      # Track Overrides. By default, set overrides to make each song its own album
      track_title: "{title}"
      track_album: "{title}"
      track_artist: "{channel}"
      track_number: "1"
      track_number_padded: "01"
      track_total: "1"
      track_year: "{upload_year}"
      track_genre: "Unset"
      # Filename Overrides
      track_file_name: "{track_number_padded} - {track_title_sanitized}.{ext}"
      album_file_name: "folder.{thumbnail_ext}"
      # Directory Name Overrides
      music_directory: "/music"
      artist_dir: "{track_artist_sanitized}"
      album_dir: "{track_album_sanitized}"
      # Full Filepath Overrides
      track_full_path: "{artist_dir}/{album_dir}/{track_file_name}"
      album_cover_path: "{artist_dir}/{album_dir}/{album_file_name}"

####################################################################################################

  # Make the 'single` preset accept a single URL using the override variable 'url'
  # Each audio file will reside in its own album.
  single:
    # Inherit from `base`
    preset: "base"

    download:
      download_strategy: "url"
      url: "{url}"

####################################################################################################

  # Make the 'albums_from_playlists' preset format audio files to reside under albums, where
  # each album is a playlist. If a file downloaded using this preset is not part of a playlist,
  # it will default to how it'd look as a `single`.
  albums_from_playlists:
    # Inherit from single
    preset: "single"

    # Override various track properties using playlist variables.
    overrides:
      track_album: "{playlist_title}"
      track_number: "{playlist_index}"
      track_number_padded: "{playlist_index_padded}"
      track_total: "{playlist_count}"
      track_year: "{playlist_max_upload_year}"

####################################################################################################

  # Make the 'albums_from_playlists' preset format audio files to reside under albums, where
  # each album is a playlist. If a file downloaded using this preset is not part of a playlist,
  # it will default to how it'd look as a `single`.
  music_of_40k:
    # Inherit from single
    preset: "albums_from_playlists"

    # Override various track properties using playlist variables.
    overrides:
      track_artist: "Music of 40K"
      track_album: "{playlist_title}"
      track_title: "{captured_track_title}"
      track_number: "{playlist_index}"
      track_number_padded: "{playlist_index_padded}"
      track_total: "{playlist_count}"
      track_year: "{playlist_max_upload_year}"
      track_genre: "Ambient"
```

sub.yaml
```yaml
music_of_40k_0:
  # Inherit albums from playlists
  preset: "music_of_40k"

  # Perform regex on many fields (title, description, chapter title) to extract as much
  # metadata as possible
  regex:
    from:
      title:
        match:
          - "^(.*) \\| .*"  # Captures 'title' from 'title | Album'
        capture_group_names:
          - "captured_track_title"
        capture_group_defaults:
          - "{title}"

  # Explicitly set the URL.
  # Override various track properties using the regex variables we extracted.
  overrides:
    url: "https://www.youtube.com/playlist?list=PLyLLeKcxw24WrT81MScJAx1_l6KOzmplV"
```
