### ISSUE TITLE
Add youtube.download_strategy: "split_video"

### ISSUE THREAD

**Issue by jmbannon** [jmbannon/ytdl-sub#63]
```
my_preset:
  youtube:
    download_strategy: "split_video"
    video_id: <id of video>
    split_file: "path/to/split_file.txt"
```

For a video like this https://www.youtube.com/watch?v=Tf1DEI2lEe0 , it would be great to download the audio, and split it up into separate songs based on the description's timestamps:

```
0:00 DOOM Eternal
4:48 Hell on Earth
9:29 Deag Nilox - First Priest Death
10:14 Barging In
12:32 Demonic Corruption
16:23 Prayer of the Diminished
17:51 King Novik
...
```

Probably cannot always rely on videos having chapters, or descriptions having these timestamps (often found in comments). Copy-pasting it to a file one-time with an expected format like above would suffice as an MVP
