### ISSUE TITLE
Add youtube.download_strategy: "merge_playlist"

### ISSUE THREAD

**Issue by jmbannon** [jmbannon/ytdl-sub#64]
For a concert like this https://www.youtube.com/playlist?list=PLyUVnCw_kLV0J2OjvADXZL-NrSghlEgDg
that is split up into multiple videos, it'd be nice to merge it into a single video to not break ambiance when watching it.

Should add a new download strategy that looks like:
```
my_preset:
  youtube:
    download_strategy: "merge_playlist"
    playlist_id: <id of playlist>
```
