### ISSUE TITLE
regex exclude causes strange behavior in other regex matches

### ISSUE THREAD

**Issue by Behem07h** [jmbannon/ytdl-sub#648]
```
regex:
            skip_if_match_fails: True #only skips if match fails & no defaults
            from:
                title:
                    exclude:
                    - '(?<![^\W])Teaser|Preview|Releasing|Trailer(?![^\W])/i' #match (and thus exclude) anything containing these keywords.
                source_webpage_url:
                    match:
                    - '(.*)' #match everything
                    capture_group_names:
                    - "captured_1"
                    capture_group_defaults:
                    - "This should never be the file path"
output_options:
            output_directory: "/music"
            file_name: "{captured_1_sanitized}/{title_sanitized}.{ext}"
```
                    
The config above should skip videos containing the words teaser, preview, releasing or trailer. if the video doesnt contain any of those words, the file should save into a subfolder matching it's source_webpage_url. However for some reason the file instead saves into "/music/This should never be the file path/{title_sanitized}.{ext}". Commenting away the title regex amends this and the file path becomes as expected.
