### ISSUE TITLE
Add soundcloud.download_strategy: "album"

### ISSUE THREAD

**Issue by jmbannon** [jmbannon/ytdl-sub#65]
```
my_preset:
  soundcloud:
    download_strategy: "album"
    album_link: https://soundcloud.com/username/sets/album_name
```
