### ISSUE TITLE
Create aliases for the `dl` command within the configuration

### ISSUE THREAD

**Issue by jmbannon** [jmbannon/ytdl-sub#66]
It would be nice for the config to offer something like
```
configuration:
  dl_aliases:
    mv: "--preset yt_music_video"
    v: "--youtube.video_url"
    p: "--youtube.playlist_url"
    artist: "--overrides.artist"
```
to convert this long command
```
ytdl-sub dl --preset yt_music_video --youtube.video_id https://youtube.com/... --overrides.artist "Tom Petty"
```
to this
```
ytdl-sub dl --mv --v https://youtube.com/... --artist 'Tom Petty'
```
