### ISSUE TITLE
Live stream VODs within date range from channel with old active live stream

### ISSUE THREAD

**Issue by krafs** [jmbannon/ytdl-sub#665]
I am trying to download all live stream VODs from [Linus Tech Tips](https://www.youtube.com/@LinusTechTips/streams) from the last two weeks, but an old, always-active live stream gatekeeps them.

Basically:
LTT has a continuous live stream that started July 6th.
Live streams always appear at the top of the channel's Live playlist, regardless of start date.
`ytdl-sub` downloads the metadata of the live stream, rejects it, because its start date is outside the two-week date range, and breaks.
But there are plenty of live stream VODs that are within the two-week date range, but they come after the live stream in the playlist.

Here is my setup, all located and executed from one and the same folder:

`config.yaml`
```yaml
configuration:
  working_directory: '/tmp/ytdl-sub'
presets: {}
```
`subscriptions.yaml`
```yaml
ltt:

  preset:
    - 'kodi_tv_show_by_date'
    - 'season_by_year__episode_by_month_day'
    
  match_filters:
    filters:
      - '!is_live'

  ytdl_options:
    break_on_reject: true
      
  date_range:
    after: 'today-2weeks'
    
  overrides:
    tv_show_name: 'LTT'
    tv_show_directory: '/config'
    url: 'https://www.youtube.com/@LinusTechTips/streams'
```
`docker-compose.yaml`
```yaml
services:
  ytdl-sub:
    image: ghcr.io/jmbannon/ytdl-sub:latest
    volumes:
      - ./:/config
    command: ytdl-sub --config=/config/config.yaml --log-level debug sub /config/subscriptions.yaml
```

I am trying to have `ytdl-sub` ignore the live stream using `match_filters`, but `ytdl-sub` is still inspecting the date range of the video and breaking if outside the range, so it doesn't have the effect I'd hoped.

Thoughts:
- Are date range checks and rejections supposed to run even if a match filter fails?
- Is there a way to have the playlist sorted by date before going through the videos? Since active live streams always are promoted to the start of the playlist, regardless of start date, maybe there is a way to sort it properly so the live stream gets its "real" index based on start date? Then `ytdl-sub` should work as normal.

**Comment by jmbannon** [comment]
It's tricky because both `match_filters` and `date_range` share:

```
 ytdl_options:
    break_on_reject: true
```
Ideally they should have their own breaks - it's a yt-dlp limitation.

There is way to get around this issue though. What you can do is add the following:
```
  match_filters:
    filters:
      - '!is_live'
      
  ytdl_options:
    break_on_reject: false
    max_downloads: 100
```

This will
1. Ensure you do not download live things (`'!is_live'`)
2. Not break immediately (`break_on_reject: false`)
3. Only pull a max of 100 metadata items (`max_downloads: 100`)
  a. If it's already downloaded, it won't be redownloaded because the TV show presets use a download archive
  
Try that and report back if it works :)
