### ISSUE TITLE
Bizarre error when trying to grab highlights - Override variable 'url' does not exist.

### ISSUE THREAD

**Issue by Yankees4life** [jmbannon/ytdl-sub#674]
Not too sure whats causing this. Heres my config and sub yaml files

Here is the error

```
 ytdl-sub sub C:\Users\Jean\Documents\Projects\ytdl-sub\tv_show_subscriptions.yaml --config C:\Users\Jean\Documents\Projects\ytdl-sub\tv_show_config.yaml
 [ytdl-sub] Working directory lock not supported in Windows. Ensure only one instance of ytdl-sub runs at once using working directory C:\Users\Jean\Documents\Projects\ytdl-sub\ytdl-sub-downloads
 [ytdl-sub] Validation error in Sports_hl.download.1.url: Override variable 'url' does not exist. For this field, ensure your override variable does not contain any source variables - it is a requirement that this be a static string. Available override variables: collection_season_1_name, collection_season_1_name_sanitized, collection_season_1_url, collection_season_1_url_sanitized, collection_season_2_name, collection_season_2_name_sanitized, collection_season_2_url, collection_season_2_url_sanitized, collection_season_3_name, collection_season_3_name_sanitized, collection_season_3_url, collection_season_3_url_sanitized, collection_season_4_name, collection_season_4_name_sanitized, collection_season_4_url, collection_season_4_url_sanitized, collection_season_5_name, collection_season_5_name_sanitized, collection_season_5_url, collection_season_5_url_sanitized, download_range, download_range_sanitized, episode_content_rating, episode_content_rating_sanitized, episode_date_standardized, episode_date_standardized_sanitized, episode_file_name, episode_file_name_sanitized, episode_file_path, episode_file_path_sanitized, episode_number, episode_number_padded, episode_number_padded_sanitized, episode_number_sanitized, episode_plot, episode_plot_sanitized, episode_title, episode_title_sanitized, episode_year, episode_year_sanitized, file_title, file_title_sanitized, file_uid, file_uid_sanitized, season_number, season_number_padded, season_number_padded_sanitized, season_number_sanitized, season_poster_file_name, season_poster_file_name_sanitized, season_title, season_title_sanitized, subscription_name, subscription_name_sanitized, subscription_name_sanitized_sanitized, tv_show_content_rating, tv_show_content_rating_sanitized, tv_show_directory, tv_show_directory_sanitized, tv_show_fanart_file_name, tv_show_fanart_file_name_sanitized, tv_show_genre, tv_show_genre_sanitized, tv_show_name, tv_show_name_sanitized, tv_show_poster_file_name, tv_show_poster_file_name_sanitized, url10, url10_sanitized, url11, url11_sanitized, url12, url12_sanitized, url13, url13_sanitized, url14, url14_sanitized, url15, url15_sanitized, url16, url16_sanitized, url17, url17_sanitized, url18, url18_sanitized, url19, url19_sanitized, url2, url20, url20_sanitized, url2_sanitized, url3, url3_sanitized, url4, url4_sanitized, url5, url5_sanitized, url6, url6_sanitized, url7, url7_sanitized, url8, url8_sanitized, url9, url9_sanitized
```
```

# This config uses prebuilt presets included with ytdl-sub to download and format
# channels from YouTube or other sites supported by yt-dlp into a TV show for
# your favorite player. The directory format will look something like
#
#   /tv_shows
#       /Season 2021
#           s2021.e0317 - Pattys Day Video-thumb.jpg
#           s2021.e0317 - Pattys Day Video.mp4
#           s2021.e0317 - Pattys Day Video.nfo
#       /Season 2022
#           s2022.e1225 - Merry Christmas-thumb.jpg
#           s2022.e1225 - Merry Christmas.mp4
#           s2022.e1225 - Merry Christmas.nfo
#       poster.jpg
#       fanart.jpg
#       tvshow.nfo
#
# The idea is to use dates as numerics to represent season and episode numbers.
configuration:
  working_directory: "C:\\Users\\Jean\\Documents\\Projects\\ytdl-sub\\ytdl-sub-downloads"
  ffmpeg_path: "C:\\ProgramData\\chocolatey\\lib\\ffmpeg\\tools\\ffmpeg\\bin\\ffmpeg.exe"
  ffprobe_path: "C:\\ProgramData\\chocolatey\\lib\\ffmpeg\\tools\\ffmpeg\\bin\\ffprobe.exe"

presets:

  # Your main TV show preset - all your tv show subscriptions will use this.
  tv_show:
    preset:
      # Choose one of the following player types:
      # - "kodi_tv_show_by_date"
      # - "jellyfin_tv_show_by_date"
      # - "plex_tv_show_by_date"

      - "jellyfin_tv_show_by_date"  # replace with desired player type

      # Choose one of the following season/episode formats:
      # - "season_by_year__episode_by_month_day"
      # - "season_by_year_month__episode_by_day"
      # - "season_by_year__episode_by_month_day_reversed"
      # - "season_by_year__episode_by_download_index"

      - "season_by_year__episode_by_month_day"  # replace with desired season/episode format

      # Include any of the presets listed below in your 'main preset' if you want
      # it applied to every TV show. Or, use them on the individual subscriptions.
      # - "only_recent_videos"
      - "add_subtitles"
      - "sponsorblock"
      - "include_info_json"
      - "nfos"
      - "mkv"

    # To download age-restricted videos, you will need to uncomment and set your cookie
    # file here as a ytdl parameter. For more info, see
    # https://ytdl-sub.readthedocs.io/en/latest/faq.html#download-age-restricted-youtube-videos
    #
    ytdl_options:
      cookiefile: "C:\\Users\\Jean\\Videos\\5123cookies.txt"  # replace with actual cookie file path

    overrides:
      tv_show_directory: "D:\\youtube\\"  # replace with path to tv show directory
      # Fields in the prebuilt preset that can be changed:
      #
      # episode_title: "{upload_date_standardized} - {title}"
      # episode_plot: "{webpage_url}"  # source variable for the video description is {description}

####################################################################################################

  # Preset to only download and keep recent videos
  only_recent_videos:

    # Only download videos within the download_range
    date_range:
      after: "today-{download_range}"

    # Stops fetching metadata if the video is out of range (saves time + bandwidth)
    ytdl_options:
      break_on_reject: True

    # Deletes any videos older than download_range. WARNING: do not use
    # "season_by_year__episode_by_download_index" if you plan to delete older videos
    output_options:
      keep_files_after: "today-{download_range}"

    # Set the duration of download_range, defaults to 2 months
    overrides:
      download_range: "2months"

####################################################################################################

  # Preset to download subtitles (either by file or embedded)
  add_subtitles:
    subtitles:
      # Embed subtitles into the video
      embed_subtitles: True
      # And/or download them as a file. Uncomment to download as file:
      # subtitles_name: "{episode_file_path}.{lang}.{subtitles_ext}"
      # subtitles_type: "srt"

      languages: "en"  # supports list of multiple languages
      allow_auto_generated_subtitles: True  # allow auto subtitles

####################################################################################################

  # Preset to cut sponsor segments from videos
  sponsorblock:
    # If you download using cron, it is wise to add a delay before downloading ad-filled content to
    # give folks time to submit sponsor segments. Uncomment to wait 2 days before download a video.
    # date_range:
    #  before: "today-2days"

    chapters:
      # Remove all of these sponsorblock categories
      sponsorblock_categories:
        - "all"
      remove_sponsorblock_categories: "all"
      force_key_frames: False

####################################################################################################

  # Preset for the hoarders who want to also save the info.json file
  include_info_json:
    output_options:
      info_json_name: "{episode_file_path}.{info_json_ext}"

  nfos:
    nfo_tags:
      # required
      nfo_name: "{title_sanitized}.nfo"
      nfo_root: "episodedetails"
      tags:
        title: "{title}"
        season: "{upload_year}"
        episode: "{upload_month}{upload_day_padded}"
      # optional
      kodi_safe: False
  mkv:
    file_convert:
      convert_to: "mkv"
      convert_with: "ffmpeg"
      ffmpeg_post_process_args: >
        -bitexact
        -vcodec copy
        -acodec copy
        -scodec copy
```      
```

# Define any number subscriptions in a single file, or use multiple
# files to organize (i.e by genre)
Sports_hl:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Soccer Highlights 2023"
    collection_season_1_name: "Copa Sudamericana 2023"
    collection_season_1_url: "https://www.youtube.com/playlist?list=PL5dXR9bHuKvl0Hzn1dKDpbgH3LrshYfoX"
    # Optional
    collection_season_2_name: "Copa Libertadores 2023"
    collection_season_2_url: "https://www.youtube.com/playlist?list=PL5dXR9bHuKvn7t0mqyaAGddCcgCR7o-I4"
    collection_season_3_name: "MLS"
    collection_season_3_url: "https://www.youtube.com/playlist?list=PLcj4z4KsbIoVPGtu3C-dRs4Ry-2pSWgAl"
    collection_season_4_name: "Leagues Cup"
    collection_season_4_url: "https://www.youtube.com/playlist?list=PLcj4z4KsbIoX2WDFYWBL-PGeV3IBrYDA5"
    collection_season_5_name: "Liga MX"
    collection_season_5_url: "https://www.youtube.com/playlist?list=PL5MdN4O9NWTVeSk2eEaxMpTBN9KwtRzmm"
```

**Comment by jmbannon** [comment]
You are using the presets:
```
      - "jellyfin_tv_show_by_date"  # replace with desired player type
      - "season_by_year__episode_by_month_day"  # replace with desired season/episode format
```
When your sub is in fact a 'collection, which needs the following presets:
```
- jellyfin_tv_show_collection
- season_by_collection__episode_by_year_month_day
```

I would make a new preset similar to `tv_show`, but with those presets above + your other ones and call it `tv_show_collection`

**Comment by jmbannon** [comment]
https://ytdl-sub.readthedocs.io/en/latest/presets.html#tv-show-collection

**Comment by Yankees4life** [comment]
Ok, did that now I got a new error
```
ytdl-sub sub C:\Users\Jean\Documents\Projects\ytdl-sub\tv_show_subscriptions.yaml --config C:\Users\Jean\Documents\Projects\ytdl-sub\tv_show_config.yaml
[ytdl-sub] Working directory lock not supported in Windows. Ensure only one instance of ytdl-sub runs at once using working directory C:\Users\Jean\Documents\Projects\ytdl-sub\ytdl-sub-downloads
[ytdl-sub] Validation error in Sports_hl: download is missing when it should be present.
```

**Comment by jmbannon** [comment]
I think one of your presets is wrong, can you post your new config

**Comment by Yankees4life** [comment]
```
# This config uses prebuilt presets included with ytdl-sub to download and format
# channels from YouTube or other sites supported by yt-dlp into a TV show for
# your favorite player. The directory format will look something like
#
#   /tv_shows
#       /Season 2021
#           s2021.e0317 - Pattys Day Video-thumb.jpg
#           s2021.e0317 - Pattys Day Video.mp4
#           s2021.e0317 - Pattys Day Video.nfo
#       /Season 2022
#           s2022.e1225 - Merry Christmas-thumb.jpg
#           s2022.e1225 - Merry Christmas.mp4
#           s2022.e1225 - Merry Christmas.nfo
#       poster.jpg
#       fanart.jpg
#       tvshow.nfo
#
# The idea is to use dates as numerics to represent season and episode numbers.
configuration:
  working_directory: "C:\\Users\\Jean\\Documents\\Projects\\ytdl-sub\\ytdl-sub-downloads"
  ffmpeg_path: "C:\\ProgramData\\chocolatey\\lib\\ffmpeg\\tools\\ffmpeg\\bin\\ffmpeg.exe"
  ffprobe_path: "C:\\ProgramData\\chocolatey\\lib\\ffmpeg\\tools\\ffmpeg\\bin\\ffprobe.exe"

presets:
  tv_show:
    preset:
      # Choose one of the following player types:
      # - "kodi_tv_show_by_date"
      # - "jellyfin_tv_show_by_date"
      # - "plex_tv_show_by_date"

      - "jellyfin_tv_show_by_date"  # replace with desired player type

      # Choose one of the following season/episode formats:
      # - "season_by_year__episode_by_month_day"
      # - "season_by_year_month__episode_by_day"
      # - "season_by_year__episode_by_month_day_reversed"
      # - "season_by_year__episode_by_download_index"

      - "season_by_year__episode_by_month_day"  # replace with desired season/episode format

      # Include any of the presets listed below in your 'main preset' if you want
      # it applied to every TV show. Or, use them on the individual subscriptions.
      # - "only_recent_videos"
      - "add_subtitles"
      - "sponsorblock"
      - "include_info_json"
      - "nfos"
      - "mkv"

    # To download age-restricted videos, you will need to uncomment and set your cookie
    # file here as a ytdl parameter. For more info, see
    # https://ytdl-sub.readthedocs.io/en/latest/faq.html#download-age-restricted-youtube-videos
    #
    ytdl_options:
      cookiefile: "C:\\Users\\Jean\\Videos\\5123cookies.txt"  # replace with actual cookie file path

    overrides:
      tv_show_directory: "D:\\youtube\\"  # replace with path to tv show directory
      # Fields in the prebuilt preset that can be changed:
      #
      # episode_title: "{upload_date_standardized} - {title}"
      # episode_plot: "{webpage_url}"  # source variable for the video description is {description}

####################################################################################################
  tv_show_collection:
    preset:
      # Choose one of the following player types:
      # - "kodi_tv_show_by_date"
      # - "jellyfin_tv_show_by_date"
      # - "plex_tv_show_by_date"

      - "jellyfin_tv_show_collection"  # replace with desired player type

      # Choose one of the following season/episode formats:
      # - "season_by_year__episode_by_month_day"
      # - "season_by_year_month__episode_by_day"
      # - "season_by_year__episode_by_month_day_reversed"
      # - "season_by_year__episode_by_download_index"

      - "season_by_collection__episode_by_year_month_day"  # replace with desired season/episode format

      # Include any of the presets listed below in your 'main preset' if you want
      # it applied to every TV show. Or, use them on the individual subscriptions.
      # - "only_recent_videos"
      - "add_subtitles"
      - "sponsorblock"
      - "include_info_json"
      - "nfos"
      - "mkv"

    # To download age-restricted videos, you will need to uncomment and set your cookie
    # file here as a ytdl parameter. For more info, see
    # https://ytdl-sub.readthedocs.io/en/latest/faq.html#download-age-restricted-youtube-videos
    #
    ytdl_options:
      cookiefile: "C:\\Users\\Jean\\Videos\\5123cookies.txt"  # replace with actual cookie file path

    overrides:
      tv_show_directory: "D:\\youtube\\"  # replace with path to tv show directory

  # Your main TV show preset - all your tv show subscriptions will use this.

  # Preset to only download and keep recent videos
  only_recent_videos:

    # Only download videos within the download_range
    date_range:
      after: "today-{download_range}"

    # Stops fetching metadata if the video is out of range (saves time + bandwidth)
    ytdl_options:
      break_on_reject: True

    # Deletes any videos older than download_range. WARNING: do not use
    # "season_by_year__episode_by_download_index" if you plan to delete older videos
    output_options:
      keep_files_after: "today-{download_range}"

    # Set the duration of download_range, defaults to 2 months
    overrides:
      download_range: "2months"

####################################################################################################

  # Preset to download subtitles (either by file or embedded)
  add_subtitles:
    subtitles:
      # Embed subtitles into the video
      embed_subtitles: True
      # And/or download them as a file. Uncomment to download as file:
      # subtitles_name: "{episode_file_path}.{lang}.{subtitles_ext}"
      # subtitles_type: "srt"

      languages: "en"  # supports list of multiple languages
      allow_auto_generated_subtitles: True  # allow auto subtitles

####################################################################################################

  # Preset to cut sponsor segments from videos
  sponsorblock:
    # If you download using cron, it is wise to add a delay before downloading ad-filled content to
    # give folks time to submit sponsor segments. Uncomment to wait 2 days before download a video.
    # date_range:
    #  before: "today-2days"

    chapters:
      # Remove all of these sponsorblock categories
      sponsorblock_categories:
        - "all"
      remove_sponsorblock_categories: "all"
      force_key_frames: False

####################################################################################################

  # Preset for the hoarders who want to also save the info.json file
  include_info_json:
    output_options:
      info_json_name: "{episode_file_path}.{info_json_ext}"

  nfos:
    nfo_tags:
      # required
      nfo_name: "{title_sanitized}.nfo"
      nfo_root: "episodedetails"
      tags:
        title: "{title}"
        season: "{upload_year}"
        episode: "{upload_month}{upload_day_padded}"
      # optional
      kodi_safe: False
  mkv:
    file_convert:
      convert_to: "mkv"
      convert_with: "ffmpeg"
      ffmpeg_post_process_args: >
        -bitexact
        -vcodec copy
        -acodec copy
        -scodec copy      
```

```
# Define any number subscriptions in a single file, or use multiple
# files to organize (i.e by genre)
Sports_hl:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show_collection"
    - "only_recent_videos"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Soccer Highlights 2023"
    collection_season_1_url: "https://www.youtube.com/playlist?list=PL5dXR9bHuKvl0Hzn1dKDpbgH3LrshYfoX"    
    collection_season_1_name: "Copa Sudamericana 2023"
    # Optional
    collection_season_2_url: "https://www.youtube.com/playlist?list=PL5dXR9bHuKvn7t0mqyaAGddCcgCR7o-I4"    
    collection_season_2_name: "Copa Libertadores 2023"
    collection_season_3_url: "https://www.youtube.com/playlist?list=PLcj4z4KsbIoVPGtu3C-dRs4Ry-2pSWgAl"    
    collection_season_3_name: "MLS"
    collection_season_4_url: "https://www.youtube.com/playlist?list=PLcj4z4KsbIoX2WDFYWBL-PGeV3IBrYDA5"    
    collection_season_4_name: "Leagues Cup"
    collection_season_5_url: "https://www.youtube.com/playlist?list=PL5MdN4O9NWTVeSk2eEaxMpTBN9KwtRzmm"    
    collection_season_5_name: "Liga MX"

```
