### ISSUE TITLE
Exclude artist from title

### ISSUE THREAD

**Issue by anjerukare** [jmbannon/ytdl-sub#692]
Hi, I want to download music from some YouTube playlist. Music titles have different formats there.

Here are some of them (titles and channel names):
- "Broken Hearts" from "pisca music"
- "Men I Trust - Show Me How (sped up/pitched)" from "Waffl3 P01"
- "билборды - острые лезвия" from "билборды"

The last one contains artist in the title – it's what I'm trying to exclude.

In one of the example configs I saw this approach:
```yml
# ...
regex:
  from:
    title:
      match:
        - "^Emily Hopkins - (.*)"  # Captures 'title' from 'Emily Hopkins - title'
      capture_group_names:
        - "captured_track_title"
      capture_group_defaults:
        - "{title}"
# ...
```

But artist here is hardcoded to regex, and I want it to be universal.

I tried to use source variable `channel` in regex like this:
```yml
# ...
regex:
  from:
    title:
      match:
        - "^{channel} - (.*)"
      capture_group_names:
        - "captured_track_title"
      capture_group_defaults:
        - "{title}"
# ...
```

But source variables don't work in regex.

**How to exclude artist from title, no matter what artist is specified in it?**
