### ISSUE TITLE
Podcast example config

### ISSUE THREAD

**Issue by jmbannon** [jmbannon/ytdl-sub#698]
Podcasts should use m4a format (which is m4b under the hood) and adhere to the tags/structure defined in audiobookshelf:

https://www.audiobookshelf.org/docs#book-directory-structure
https://www.audiobookshelf.org/docs#book-audio-metadata

**Comment by peteh** [comment]
I second this, I'm trying to get the right config for audiobookshelf but I'm not really succeeding

I think the format is not that important, but the structure of the folders is. 

```
/Podcasts
  /The Daily
    2024-01-01 Episode Title.m4a
    2024-01-02 Episode Title.m4a
```

This is how far I got, but the folder structure is not ok. 

```yml
# subscriptions.yaml:
# Everything in here can be downloaded using the command:
#   ytdl-sub sub subscriptions.yaml

# __preset__ is a place to define global overrides for all subscriptions
__preset__:
  overrides:
    # Root folder of all ytdl-sub TV Shows
    tv_show_directory: "/tv_shows"
    
    # Root folder of all ytdl-sub Music
    music_directory: "/downloads"
    
    # For 'Only Recent' preset, only keep vids within this range and limit
    only_recent_date_range: "5days"
    only_recent_max_files: 30
    
  # Pass any arg directly to yt-dlp's Python API
  #ytdl_options:
    #cookiefile: "/config/ytdl-sub-configs/cookie.txt"

###################################################################
# TV Show Presets. Can replace Plex with Plex/Jellyfin/Emby/Kodi

YouTube Releases | Only Recent:
  = UNKNOWN:
    "Ungeskriptet": "https://www.youtube.com/watch?v=R2I4G51RaGM&list=PLODtG-GWUvGN1cOXptKs2J6mievt22Vk3"

```
