### ISSUE TITLE
ytdl-sub breaks when trying to download a video on wl playlist

### ISSUE THREAD

**Issue by Yankees4life** [jmbannon/ytdl-sub#704]
Not too sure whats happening here. I'm trying to grab videos from my WL and it pops up with this weird error
https://pastebin.com/pGnnYHxQ

My configs
```
# This config uses prebuilt presets included with ytdl-sub to download and format
# channels from YouTube or other sites supported by yt-dlp into a TV show for
# your favorite player. The directory format will look something like
#
#   /tv_shows
#       /Season 2021
#           s2021.e0317 - Pattys Day Video-thumb.jpg
#           s2021.e0317 - Pattys Day Video.mp4
#           s2021.e0317 - Pattys Day Video.nfo
#       /Season 2022
#           s2022.e1225 - Merry Christmas-thumb.jpg
#           s2022.e1225 - Merry Christmas.mp4
#           s2022.e1225 - Merry Christmas.nfo
#       poster.jpg
#       fanart.jpg
#       tvshow.nfo
#
# The idea is to use dates as numerics to represent season and episode numbers.
configuration:
  working_directory: "C:\\Users\\Jean\\Documents\\Projects\\ytdl-sub\\ytdl-sub-downloads"
  ffmpeg_path: "C:\\ProgramData\\chocolatey\\lib\\ffmpeg\\tools\\ffmpeg\\bin\\ffmpeg.exe"
  ffprobe_path: "C:\\ProgramData\\chocolatey\\lib\\ffmpeg\\tools\\ffmpeg\\bin\\ffprobe.exe"

presets:
  tv_show:
    preset:
      # Choose one of the following player types:
      # - "kodi_tv_show_by_date"
      # - "jellyfin_tv_show_by_date"
      # - "plex_tv_show_by_date"

      - "jellyfin_tv_show_by_date"  # replace with desired player type

      # Choose one of the following season/episode formats:
      # - "season_by_year__episode_by_month_day"
      # - "season_by_year_month__episode_by_day"
      # - "season_by_year__episode_by_month_day_reversed"
      # - "season_by_year__episode_by_download_index"

      - "season_by_year__episode_by_month_day"  # replace with desired season/episode format

      # Include any of the presets listed below in your 'main preset' if you want
      # it applied to every TV show. Or, use them on the individual subscriptions.
      # - "only_recent_videos"
      - "add_subtitles"
      - "sponsorblock"
      - "include_info_json"
      - "mkv"
      - "chunk_initial_download"

    # To download age-restricted videos, you will need to uncomment and set your cookie
    # file here as a ytdl parameter. For more info, see
    # https://ytdl-sub.readthedocs.io/en/latest/faq.html#download-age-restricted-youtube-videos
    #
    ytdl_options:
      cookiefile: "C:\\Users\\Jean\\Videos\\5123cookies.txt"  # replace with actual cookie file path
      max_downloads: 50

    overrides:
      tv_show_directory: "D:\\youtube\\"  # replace with path to tv show directory
      # Fields in the prebuilt preset that can be changed:
      #
      # episode_title: "{upload_date_standardized} - {title}"
      # episode_plot: "{webpage_url}"  # source variable for the video description is {description}

####################################################################################################
  tv_show_collection:
    preset:
      # Choose one of the following player types:
      # - "kodi_tv_show_by_date"
      # - "jellyfin_tv_show_by_date"
      # - "plex_tv_show_by_date"

      - "jellyfin_tv_show_collection"  # replace with desired player type

      # Choose one of the following season/episode formats:
      # - "season_by_year__episode_by_month_day"
      # - "season_by_year_month__episode_by_day"
      # - "season_by_year__episode_by_month_day_reversed"
      # - "season_by_year__episode_by_download_index"

      - "season_by_collection__episode_by_year_month_day"  # replace with desired season/episode format

      # Include any of the presets listed below in your 'main preset' if you want
      # it applied to every TV show. Or, use them on the individual subscriptions.
      # - "only_recent_videos"
      - "add_subtitles"
      - "sponsorblock"
      - "include_info_json"
      - "mkv"

    # To download age-restricted videos, you will need to uncomment and set your cookie
    # file here as a ytdl parameter. For more info, see
    # https://ytdl-sub.readthedocs.io/en/latest/faq.html#download-age-restricted-youtube-videos
    #
    ytdl_options:
      cookiefile: "C:\\Users\\Jean\\Videos\\5123cookies.txt"  # replace with actual cookie file path

    overrides:
      tv_show_directory: "D:\\youtube\\"  # replace with path to tv show directory

  # Your main TV show preset - all your tv show subscriptions will use this.

  # Preset to only download and keep recent videos
  only_recent_videos:

    # Only download videos within the download_range
    date_range:
      after: "today-{download_range}"

    # Stops fetching metadata if the video is out of range (saves time + bandwidth)
    ytdl_options:
      break_on_reject: True

    # Deletes any videos older than download_range. WARNING: do not use
    # "season_by_year__episode_by_download_index" if you plan to delete older videos
    output_options:
      keep_files_after: "today-{download_range}"

    # Set the duration of download_range, defaults to 2 months
    overrides:
      download_range: "2months"

####################################################################################################

  # Preset to download subtitles (either by file or embedded)
  add_subtitles:
    subtitles:
      # Embed subtitles into the video
      embed_subtitles: True
      # And/or download them as a file. Uncomment to download as file:
      # subtitles_name: "{episode_file_path}.{lang}.{subtitles_ext}"
      # subtitles_type: "srt"

      languages: "en"  # supports list of multiple languages
      allow_auto_generated_subtitles: True  # allow auto subtitles

####################################################################################################

  # Preset to cut sponsor segments from videos
  sponsorblock:
    # If you download using cron, it is wise to add a delay before downloading ad-filled content to
    # give folks time to submit sponsor segments. Uncomment to wait 2 days before download a video.
    # date_range:
    #  before: "today-2days"

    chapters:
      # Remove all of these sponsorblock categories
      sponsorblock_categories:
        - "all"
      remove_sponsorblock_categories: "all"
      force_key_frames: False

####################################################################################################

  # Preset for the hoarders who want to also save the info.json file
  include_info_json:
    output_options:
      info_json_name: "{episode_file_path}.{info_json_ext}"

  mkv:
    file_convert:
      convert_to: "mkv"
      convert_with: "ffmpeg"
      ffmpeg_post_process_args: >
        -bitexact
        -vcodec copy
        -acodec copy
        -scodec copy      `
```

```
# Define any number subscriptions in a single file, or use multiple
# files to organize (i.e by genre)
wl:
  # Inherit our `tv_show` AND `only_recent_videos` preset
  # Bottom-most presets take precedence.
  preset:
    - "tv_show"
  # Set override variables for this subscription. Modify the
  # `download_range` to only download and keep 2 weeks' worth
  # of videos.
  overrides:
    tv_show_name: "Watch Later"
    url: "https://www.youtube.com/playlist?list=WL"
billburr:
  # Inherit our `tv_show` AND `only_recent_videos` preset
  # Bottom-most presets take precedence.
  preset:
    - "tv_show"
    - "only_recent_videos"
  
  # Set override variables for this subscription. Modify the
  # `download_range` to only download and keep 2 weeks' worth
  # of videos.
  overrides:
    tv_show_name: "Bill Burr"
    url: "https://www.youtube.com/channel/UCAp990eMLzmei84WNR4ptgA"
    download_range: "4days"
mlb:
  # Inherit our `tv_show` AND `only_recent_videos` preset
  # Bottom-most presets take precedence.
  preset:
    - "tv_show"
    - "only_recent_videos"
  
  # Set override variables for this subscription. Modify the
  # `download_range` to only download and keep 2 weeks' worth
  # of videos.
  overrides:
    tv_show_name: "MLB"
    url: "https://www.youtube.com/playlist?list=PLL-lmlkrmJanbpITN3ydTISkYto7lbF_N"
    download_range: "1day"         
Sports_hl:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show_collection"
    - "only_recent_videos"
    - "collection_season_1"
    - "collection_season_2"
    - "collection_season_3"
    - "collection_season_4"
    - "collection_season_5"
    - "collection_season_6"
    - "collection_season_7"
    - "collection_season_8"
    - "collection_season_9"
    - "collection_season_10"
    - "collection_season_11"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "Soccer Highlights 2023"
    collection_season_1_url: "https://www.youtube.com/playlist?list=PL5dXR9bHuKvl0Hzn1dKDpbgH3LrshYfoX"    
    collection_season_1_name: "Copa Sudamericana 2023"
    # Optional
    collection_season_2_url: "https://www.youtube.com/playlist?list=PL5dXR9bHuKvn7t0mqyaAGddCcgCR7o-I4"    
    collection_season_2_name: "Copa Libertadores 2023"
    collection_season_3_url: "https://www.youtube.com/playlist?list=PLcj4z4KsbIoVPGtu3C-dRs4Ry-2pSWgAl"    
    collection_season_3_name: "MLS"
    collection_season_4_url: "https://www.youtube.com/playlist?list=PLKj1QUtwqLN86S2boRc_NUN_IO4PL8Js7"    
    collection_season_4_name: "La Liga"
    collection_season_5_url: "https://www.youtube.com/playlist?list=PL5MdN4O9NWTVeSk2eEaxMpTBN9KwtRzmm"    
    collection_season_5_name: "Liga MX"
    collection_season_6_url: "https://www.youtube.com/playlist?list=PLXEMPXZ3PY1jXCeoUgFpKZ_sO-xI67qFb"    
    collection_season_6_name: "EPL"
    collection_season_7_url: "https://www.youtube.com/bundesliga"    
    collection_season_7_name: "Bundesliga"
    collection_season_8_url: "https://www.youtube.com/playlist?list=PL5dXR9bHuKvlBtAYG6axBEQ-dYXjbuPB4"    
    collection_season_8_name: "Ligue 1"
    collection_season_9_url: "https://www.youtube.com/seriea"    
    collection_season_9_name: "Serie A"
    collection_season_10_url: "https://www.youtube.com/playlist?list=PLkwBiY2Dq-oYudAQQWU3ene4op723wpxg"    
    collection_season_10_name: "Europa League"    
    collection_season_11_url: "https://www.youtube.com/playlist?list=PLkwBiY2Dq-oZNXjt-CUGlYwBHT3DsnKMq"    
    collection_season_11_name: "Champions League"    
    download_range: "7days"
    
```
