### ISSUE TITLE
season_by_collection__episode_by_year_month_day_reversed seems broke, give me error about season_number_padded not existing

### ISSUE THREAD

**Issue by EvanCarroll** [jmbannon/ytdl-sub#708]
When I use,

```yaml
  newsnew:
    overrides:
      tv_show_genre: "news"
    date_range:
      after: "today-{download_range}"
    ytdl_options:
      break_on_reject: True
    output_options:
      keep_files_after: "today-{download_range}"
    overrides:
      download_range: "1month"
      tv_show_directory: "/tv-shows"
      tv_show_genre: "news"
    preset:
      - "jellyfin_tv_show_by_date"
      - "season_by_collection__episode_by_year_month_day_reversed"
      - max_1080p
```

On,

```yaml
breaking_points:
  preset:
    - "newsnew"
  overrides:
    url: https://www.youtube.com/@breakingpoints
    tv_show_name: Breaking Points
 ```

I get,

> [ytdl-sub] Validation error in breaking_points.output_options.file_name: Format variable 'season_number_padded' does not exist. Available variables: channel, channel_id, channel_sanitized, creator, creator_sanitized, description, download_index, download_index_padded6, download_range, download_range_sanitized, episode_content_rating, episode_content_rating_sanitized, episode_date_standardized, episode_date_standardized_sanitized, episode_file_name, episode_file_name_sanitized, episode_file_path, episode_file_path_sanitized, episode_number, episode_number_padded, episode_number_padded_sanitized, episode_number_sanitized, episode_plot, episode_plot_sanitized, episode_title, episode_title_sanitized, episode_year, episode_year_sanitized, epoch, epoch_date, epoch_hour, ext, extractor, file_title, file_title_sanitized, file_uid, file_uid_sanitized, info_json_ext, playlist_count, playlist_description, playlist_index, playlist_index_padded, playlist_index_padded6, playlist_index_reversed, playlist_index_reversed_padded, playlist_index_reversed_padded6, playlist_max_upload_year, playlist_max_upload_year_truncated, playlist_title, playlist_title_sanitized, playlist_uid, playlist_uploader, playlist_uploader_id, playlist_uploader_sanitized, playlist_uploader_url, playlist_webpage_url, release_date, release_date_standardized, release_day, release_day_of_year, release_day_of_year_padded, release_day_of_year_reversed, release_day_of_year_reversed_padded, release_day_padded, release_day_reversed, release_day_reversed_padded, release_month, release_month_padded, release_month_reversed, release_month_reversed_padded, release_year, release_year_truncated, release_year_truncated_reversed, season_poster_file_name, season_poster_file_name_sanitized, season_title, season_title_sanitized, source_count, source_description, source_index, source_index_padded, source_title, source_title_sanitized, source_uid, source_uploader, source_uploader_id, source_uploader_url, source_webpage_url, subscription_name, subscription_name_sanitized, subscription_name_sanitized_sanitized, thumbnail_ext, title, title_sanitized, title_sanitized_plex, tv_show_content_rating, tv_show_content_rating_sanitized, tv_show_directory, tv_show_directory_sanitized, tv_show_fanart_file_name, tv_show_fanart_file_name_sanitized, tv_show_genre, tv_show_genre_sanitized, tv_show_name, tv_show_name_sanitized, tv_show_poster_file_name, tv_show_poster_file_name_sanitized, uid, uid_sanitized, uid_sanitized_plex, upload_date, upload_date_index, upload_date_index_padded, upload_date_index_reversed, upload_date_index_reversed_padded, upload_date_standardized, upload_day, upload_day_of_year, upload_day_of_year_padded, upload_day_of_year_reversed, upload_day_of_year_reversed_padded, upload_day_padded, upload_day_reversed, upload_day_reversed_padded, upload_month, upload_month_padded, upload_month_reversed, upload_month_reversed_padded, upload_year, upload_year_truncated, upload_year_truncated_reversed, uploader, uploader_id, uploader_url, url, url10, url10_sanitized, url11, url11_sanitized, url12, url12_sanitized, url13, url13_sanitized, url14, url14_sanitized, url15, url15_sanitized, url16, url16_sanitized, url17, url17_sanitized, url18, url18_sanitized, url19, url19_sanitized, url2, url20, url20_sanitized, url2_sanitized, url3, url3_sanitized, url4, url4_sanitized, url5, url5_sanitized, url6, url6_sanitized, url7, url7_sanitized, url8, url8_sanitized, url9, url9_sanitized, url_sanitized, webpage_url

However, when I switch to the `season_by_year__episode_by_month_day_reversed` rather than `season_by_collection__episode_by_year_month_day_reversed` everything just works.

How is `season_number_padded` not set? Is that preset just broken? I'm wanting to try it to see how it's rendered. It's documented here, https://ytdl-sub.readthedocs.io/en/latest/presets.html?highlight=playlist#tv-show-collection
