### ISSUE TITLE
ffmpeg file conversion tries to use tmp file after it's been merged/deleted.

### ISSUE THREAD

**Issue by rjbutler** [jmbannon/ytdl-sub#721]
It may be I have something wrong in my config, but I'm trying to use ffmpeg with hardware acceleration.  The debug log shows that Merger runs (is that yt-dlp doing the merge?) and then deletes the tmp file.  The ffmpeg command line then tries to convert the delete file instead of the merged file.
```
[ytdl-sub:yt-dlp] [Merger] Merging formats into "/tmp/ytdl-sub-downloads/show/G7eP5mylDXc.mp4"
[ytdl-sub:yt-dlp] Deleting original file /tmp/ytdl-sub-downloads/show/G7eP5mylDXc.f616.mp4 (pass -k to keep)
[ytdl-sub:yt-dlp] Deleting original file /tmp/ytdl-sub-downloads/show/G7eP5mylDXc.f251.webm (pass -k to keep)
[ytdl-sub:yt-dlp] [SubtitlesConvertor] Converting subtitles
[ytdl-sub:yt-dlp] Deleting original file /tmp/ytdl-sub-downloads/show/G7eP5mylDXc.en.vtt (pass -k to keep)
[ytdl-sub:yt-dlp] [Metadata] Adding metadata to "/tmp/ytdl-sub-downloads/show/G7eP5mylDXc.mp4"
[ytdl-sub:yt-dlp] [ModifyChapters] SponsorBlock information is unavailable
[ytdl-sub:yt-dlp] [Metadata] Adding metadata to "/tmp/ytdl-sub-downloads/show/G7eP5mylDXc.mp4"
[ytdl-sub:ffmpeg] Running /usr/bin/ffmpeg -y -bitexact -i /tmp/ytdl-sub-downloads/show/G7eP5mylDXc.webp /tmp/ytdl-sub-downloads/show/G7eP5mylDXc.jpg
[ytdl-sub:ffmpeg] Running /usr/bin/ffmpeg -y -bitexact -i /tmp/tmpqhwa_72y /tmp/tmpqhwa_72y.out.jpg
[ytdl-sub:ffmpeg] Running /usr/bin/ffmpeg -y -bitexact -i /tmp/tmp1fbpectl /tmp/tmp1fbpectl.out.jpg
[ytdl-sub:ffmpeg] Running /usr/bin/ffmpeg -i /tmp/ytdl-sub-downloads/show/G7eP5mylDXc.mp4 -vcodec h264_qsv -bitexact -acodec copy -scodec mov_text -hwaccel:auto /tmp/ytdl-sub-downloads/show/G7eP5mylDXc.tmp.mp4
[ytdl-sub] ffmpeg_post_process_args -i /tmp/ytdl-sub-downloads/show/G7eP5mylDXc.mp4 -vcodec h264_qsv -bitexact -acodec copy -scodec mov_text -hwaccel:auto /tmp/ytdl-sub-downloads/show/G7eP5mylDXc.tmp.mp4 result in an error
```

file_convert.py has this code which only applies if yt-dlp is used for the conversion:

```
        # FFMpeg input video file should already be converted
        if self.plugin_options.convert_with == "yt-dlp":
            input_video_file_path = converted_video_file_path
```
I searched the docs but I didn't see anything relevant

relevent config:
```
    preset:
      - "sponsorblock"
      - "add_subtitles"
      - "best_video_quality"
      - "plex_tv_show_by_date"
      - "season_by_year__episode_by_month_day"  # replace with desired season/episode format
      - "only_recent_videos"

      - "include_info_json"
    ytdl_options:
      cookiefile: "/config/cookies.txt"  # replace with actual cookie file path
      mark_watched: true
      break_on_existing: True  # Stop downloads if it already exists
    file_convert:
      convert_to: "mp4"
      convert_with: "ffmpeg"
      ffmpeg_post_process_args: -vcodec h264_qsv -bitexact -acodec copy -scodec mov_text -hwaccel:auto
```

Thanks for any suggestion
