### ISSUE TITLE
[Feature Request] Simplify cron setup

### ISSUE THREAD

**Issue by darthtechworker** [jmbannon/ytdl-sub#732]
building up on #730 & #731 

It would be great if we could define the cron tab from the config.yaml file itself.

Looks like many folks struggled with setting this up based on past git issues and discord chats. Since this product is all about having presets, let us embrace that philosophy for setting this as well.

```
configuration:
  working_directory: '.ytdl-sub-downloads'
  persist_logs:
    logs_directory: "/config/logs"
  frequency: <every1hour | every15min | every 2day | */15 * * * *>
```

Where `every15min` etc., resolves to it's cron counterpart.
