### ISSUE TITLE
Add youtube.download_strategy "multi_channels_from_playlist"

### ISSUE THREAD

**Issue by jmbannon** [jmbannon/ytdl-sub#75]
```
example_preset:
  youtube:
    download_strategy: "multi_channels"
    multi:
      "First channel": https://youtube.com/...
      "Second channel": https://.....
  ...
```
should be equivalent to
```
example_preset:
  youtube:
    download_strategy: "multi_channels_from_playlist"
    playlist: https://youtube.com/...
  ...
```
where each unique channel in the playlist is an additional channel entry
