### ISSUE TITLE
Fetch playlist uploader's avatar/banner thumbnail for poster/fanart

### ISSUE THREAD

**Issue by Rahmerh** [jmbannon/ytdl-sub#756]
I've renamed this issue to reflect a new issue I'm having. I've read through the prebuilt presets a bit and now have a configuration which solves my last issue. Although now I'm facing a new one:

When I only download 1 or multiple playlists from a channel, I noticed that it won't download the channel's banner or profile picture. I'd like those to enhance the view in my jellyfin instance.

Currently the download section of my config looks like this: 

```
download:
      - url: "{url}"
        playlist_thumbnails:
          - name: "{season_name}/{season_name}-poster.jpg"
            uid: "latest_entry"
        source_thumbnails:
          - name: "poster.jpg"
            uid: "avatar_uncropped"
          - name: "banner.jpg"
            uid: "banner_uncropped"
```

But after it finishes downloading the playlist (According to the code, then this function is called right?) nothing happens. Is this known? And is there a way to work around this?
