### ISSUE TITLE
Using ytdl option playlistreverse doesn't scan the playlist in reverse

### ISSUE THREAD

**Issue by cbunn81** [jmbannon/ytdl-sub#759]
I noticed that recently a playlist I use as a ytdl-sub subscription has reversed their order to be from oldest to newest. I've tried setting the config to scan in reversed order, but it still scans the first (oldest) video in the playlist and breaks on existing.

Here is the relevant section from the `config.yaml`:
```yaml
presets:
  # Your main TV show preset - all your tv show subscriptions will use this.
  tv_show:
    preset:
      - "kodi_tv_show_by_date"
      - "season_by_year__episode_by_month_day" 
      - "add_subtitles"

    # Set resolution/quality options for yt-dlp
    # Don't download greater than 1080p, and prefer MP4
    ytdl_options:
      format: "bv*[height<=1080][ext=mp4]+ba[ext=m4a]/b[height<=1080][ext=mp4] / bv*+ba/b"
      ignoreerrors: True
      # Recommended to avoid perma-throttling from YouTube:
      max_downloads: 4

    overrides:
      tv_show_directory: "/mnt/tv/" 
      episode_file_name: "{tv_show_name} - S{season_number_padded}E{episode_number_padded} - {file_title}"
      episode_title: "{title}"

  reversed:
    ytdl_options:
      playlistreverse: True
```

Here is the relevant section from the `subscription.yaml`:
```yaml
insider_how_real_is_it:
  preset:
    - "tv_show"
    - "reversed"
  overrides:
    tv_show_name: "Insider - How Real Is It"
    url: "https://www.youtube.com/playlist?list=PLKfWL8IXgKBuonEBHu-lhO28bCinSqNv4"

```

And here is an example log file for the above subscription showing that it attemps the first (oldest) video and breaks on existing:
```
[ytdl-sub] Beginning subscription download for insider_how_real_is_it
[ytdl-sub] Subscription full yaml:
presets:
  insider_how_real_is_it:
    chapters:
      embed_chapters: true
    download:
    - playlist_thumbnails:
      - name: '{tv_show_poster_file_name}'
        uid: avatar_uncropped
      - name: '{tv_show_fanart_file_name}'
        uid: banner_uncropped
      url: '{url}'
    - url: '{url2}'
    - url: '{url3}'
    - url: '{url4}'
    - url: '{url5}'
    - url: '{url6}'
    - url: '{url7}'
    - url: '{url8}'
    - url: '{url9}'
    - url: '{url10}'
    - url: '{url11}'
    - url: '{url12}'
    - url: '{url13}'
    - url: '{url14}'
    - url: '{url15}'
    - url: '{url16}'
    - url: '{url17}'
    - url: '{url18}'
    - url: '{url19}'
    - url: '{url20}'
    nfo_tags:
      kodi_safe: true
      nfo_name: '{episode_file_path}.nfo'
      nfo_root: episodedetails
      tags:
        aired: '{episode_date_standardized}'
        episode: '{episode_number}'
        genre:
        - '{tv_show_genre}'
        mpaa: '{episode_content_rating}'
        plot: '{episode_plot}'
        season: '{season_number}'
        title: '{episode_title}'
        year: '{episode_year}'
    output_directory_nfo_tags:
      kodi_safe: true
      nfo_name: tvshow.nfo
      nfo_root: tvshow
      tags:
        genre:
        - '{tv_show_genre}'
        mpaa: '{tv_show_content_rating}'
        title: '{tv_show_name}'
    output_options:
      file_name: '{episode_file_path}.{ext}'
      info_json_name: '{episode_file_path}.{info_json_ext}'
      maintain_download_archive: true
      output_directory: '{tv_show_directory}/{tv_show_name_sanitized}'
      thumbnail_name: '{episode_file_path}-thumb.jpg'
    overrides:
      episode_content_rating: '{tv_show_content_rating}'
      episode_date_standardized: '{upload_date_standardized}'
      episode_file_name: '{tv_show_name} - S{season_number_padded}E{episode_number_padded}
        - {file_title}'
      episode_file_path: Season {season_number_padded}/{episode_file_name}
      episode_number: '{upload_month}{upload_day_padded}{upload_date_index_padded}'
      episode_number_padded: '{upload_month_padded}{upload_day_padded}{upload_date_index_padded}'
      episode_plot: '{webpage_url}


        {description}'
      episode_title: '{title}'
      episode_year: '{upload_year}'
      file_title: '{title_sanitized}'
      file_uid: '{uid_sanitized}'
      season_number: '{upload_year}'
      season_number_padded: '{season_number}'
      season_poster_file_name: season{season_number_padded}-poster.jpg
      season_title: '{season_number_padded}'
      tv_show_content_rating: TV-14
      tv_show_directory: /mnt/tv/
      tv_show_fanart_file_name: fanart.jpg
      tv_show_genre: ytdl-sub
      tv_show_name: Insider - How Real Is It
      tv_show_poster_file_name: poster.jpg
      url: https://www.youtube.com/playlist?list=PLKfWL8IXgKBuonEBHu-lhO28bCinSqNv4
      url10: ''
      url11: ''
      url12: ''
      url13: ''
      url14: ''
      url15: ''
      url16: ''
      url17: ''
      url18: ''
      url19: ''
      url2: ''
      url20: ''
      url3: ''
      url4: ''
      url5: ''
      url6: ''
      url7: ''
      url8: ''
      url9: ''
    preset:
    - _base
    - _base
    - _episode_base
    - _episode_video_tags
    - _episode_nfo_tags
    - _kodi_base
    - _jellyfin_tv_show
    - _kodi_tv_show
    - _tv_show_by_date
    - _season_by_year
    - kodi_tv_show_by_date
    - season_by_year__episode_by_month_day
    - add_subtitles
    - tv_show
    - reversed
    subtitles:
      embed_subtitles: true
      languages: en
    video_tags:
      contentRating: '{episode_content_rating}'
      date: '{episode_date_standardized}'
      episode_id: '{episode_number}'
      genre: '{tv_show_genre}'
      show: '{tv_show_name}'
      synopsis: '{episode_plot}'
      title: '{episode_title}'
      year: '{episode_year}'
    ytdl_options:
      break_on_existing: true
      format: bv*[height<=1080][ext=mp4]+ba[ext=m4a]/b[height<=1080][ext=mp4] / bv*+ba/b
      ignoreerrors: true
      max_downloads: 4
      playlistreverse: true

[ytdl-sub:ytdl-options] Setting match-filters:
 - !is_live & !is_upcoming & !post_live
[ytdl-sub:ytdl-options] Setting breaking-match-filters: []
[ytdl-sub:yt-dlp-downloader] ytdl_options: {'ignoreerrors': True, 'outtmpl': '/tmp/ytdl-sub-downloads/insider_how_real_is_it/%(id)s.%(ext)s', 'writethumbnail': False, 'ffmpeg_location': '/usr/local/bin/ffmpeg', 'download_archive': '/tmp/ytdl-sub-downloads/insider_how_real_is_it/.ytdl-sub-insider_how_real_is_it-download-archive.json', 'match_filter': <function match_filter_func.<locals>._match_func at 0x86c8e6c00>, 'break_on_existing': True, 'format': 'bv*[height<=1080][ext=mp4]+ba[ext=m4a]/b[height<=1080][ext=mp4] / bv*+ba/b', 'max_downloads': 4, 'playlistreverse': True, 'skip_download': True, 'writeinfojson': True}
[ytdl-sub:yt-dlp] [youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLKfWL8IXgKBuonEBHu-lhO28bCinSqNv4
[ytdl-sub:yt-dlp] [youtube:tab] PLKfWL8IXgKBuonEBHu-lhO28bCinSqNv4: Downloading webpage
[ytdl-sub:yt-dlp] WARNING: [youtube:tab] YouTube said: INFO - Unavailable videos are hidden
[ytdl-sub:yt-dlp] [youtube:tab] PLKfWL8IXgKBuonEBHu-lhO28bCinSqNv4: Redownloading playlist API JSON with unavailable videos
[ytdl-sub:yt-dlp] [download] Downloading playlist: How Real Is It?
[ytdl-sub:yt-dlp] [info] Writing playlist metadata as JSON to: /tmp/ytdl-sub-downloads/insider_how_real_is_it/PLKfWL8IXgKBuonEBHu-lhO28bCinSqNv4.info.json
[ytdl-sub:yt-dlp] [youtube:tab] Playlist How Real Is It?: Downloading 1 items of 130
[ytdl-sub:yt-dlp] [download] TfBgb0NZLGw: Explosives Expert Rates Unrealistic Movie Explosions | How Real Is It? has already been recorded in the archive
[ytdl-sub:yt-dlp-downloader] ExistingVideoReached, stopping additional downloads. (Can be disable by setting `ytdl_options.break_on_existing` to False).
[ytdl-sub:downloader] Beginning downloads for https://www.youtube.com/playlist?list=PLKfWL8IXgKBuonEBHu-lhO28bCinSqNv4
```
