### ISSUE TITLE
Add `unique_indexer` plugin to create indices for unique values

### ISSUE THREAD

**Issue by jmbannon** [jmbannon/ytdl-sub#767]
This plugin will create/load a file that contains a counter for every unique value it comes across. i.e.

```
unique_indexer:
  filename: ".season_counter.json"
  to_index:
    playlist_index: "{playlist_uid}"
  starting_index: 1
```

Will produce the variable `playlist_index`.

Now imagine you download many playlists from a documentary channel, and want each playlist to be a season. Playlists returned by yt-dlp do not have any notion of an index or deterministic order. This plugin will fix that by eagerly assigning an index for each playlist uid it comes across.

The file will look something like:

```
{
  "playlist_index": {
    "asf3asPLAYLIST_UIDsdf_A": 1,
    "asf3asPLAYLIST_UIDsdf_B": 2,
  }
}
```
Each entry will do a lookup to see if an index exists. If not, increment and create a new index.

**Comment by jmbannon** [comment]
Came up with this design:

```
hashmap_lookup:
  playlist_uid:
    lookup_filename: ".season_lookup.json"
    lookup_value_variable_name: "playlist_season"
    skip_if_exists: False
    lookup_value: "{playlist_name}"
    nested_hashmap_lookup:
      uid:
        lookup_filename: ".season_lookup_{playlist_uid}.json"
        lookup_value_variable: "playlist_season_episode"
        skip_if_exists: True  # disallow_duplicate_videos
        lookup_value: "{uid}"
```

Produces...

playlist_uid: `if lookup exists (playlist_uid), use the lookup value`
- playlist_season
- playlist_season_sanitized
- playlist_season_index
- playlist_season_index_padded
- playlist_season_index_padded6

nested uid: `if lookup exists (playlist_uid + uid), skip`
- playlist_season_episode
- playlist_season_episode_sanitized
- playlist_season_episode_index
- playlist_season_episode_index_padded
- playlist_season_episode_index_padded6

```
# season_lookup.json in yaml format
123abc: "The Playlist Name from YouTube"
456xyz: "The Other Playlist Name
```

```
# season_lookup_123abc.json in yaml format
video_123abc: "Video From 123abc"
```
