### ISSUE TITLE
Add documentation for ytdl-sub-gui image

### ISSUE THREAD

**Issue by DavidHenryThoreau** [jmbannon/ytdl-sub#781]
Do you plan to add a web-gui (I don't find anything in `ytdl-sub --help`) ?

**Comment by jmbannon** [comment]
Hi @DavidHenryThoreau , a docker image containing a "gui" does exist today. Haven't got to documenting it yet, but it's basically ytdl-sub on top of LSIO's code-server image (https://docs.linuxserver.io/images/docker-code-server)

This provides a text editor and terminal in browser to modify configs and run ytdl-sub.
Going to re-purpose this issue to add proper documentation

**Comment by DavidHenryThoreau** [comment]
Really nice, do you have a `docker-compose.yaml` ?

**Comment by jmbannon** [comment]
That's what I need to document :wink: 
here is my personal one
```
  ytdl-sub-gui:
    image: ghcr.io/jmbannon/ytdl-sub-gui:latest
    container_name: ytdl-sub-gui
    environment:
      - PUID=${YTDL_SUB_PUID}
      - PGID=${SERVARR_PGID}
      - TZ=America/Los_Angeles
    volumes:
      - ${APP_PATH}/ytdl-sub-gui/config:/config
      - ${NAS_PATH}/Music/MusicVideos:/music_videos
      - ${NAS_PATH}/Youtube:/youtube
      - ${NAS_PATH}/Music/TaggedManual:/music
    ports:
      - 8443:8443
    restart: unless-stopped

```
