### ISSUE TITLE
Title Change Causing Video to Be Downloaded Twice

### ISSUE THREAD

**Issue by mattmcquinn** [jmbannon/ytdl-sub#795]
Hi,

I seem to be running into an issue where some videos will have their title changed after `ytdl-sub` has downloaded the video, and the next time `ytdl-sub` runs the video is being redownloaded.

Is this a known issue or is there any change I can make to my config to fix this?

Thanks in advance

```
configuration:
  working_directory: '.ytdl-sub-downloads'

presets:

  # Your main TV show preset - all your tv show subscriptions will use this.
  "TV Show Full Archive":
    preset:
      - "plex_tv_show_by_date"
      - "season_by_year__episode_by_month_day"
      - "sponsorblock"
      - "max_1080p"

    # Stops fetching metadata if the video is out of range (saves time + bandwidth)
    ytdl_options:
      break_on_reject: True

    output_options:
      maintain_download_archive: True

    overrides:
      tv_show_directory: "/tv_shows"

####################################################################################################

  # A secondary TV Show preset that only keeps recent videos
  "TV Show Only Recent":

    # Inherit the `TV Show Full Archive` preset
    preset:
      - "TV Show Full Archive"

    # Only download videos within the download_range
    date_range:
      after: "today-{download_range}"

    # Deletes any videos older than download_range.
    output_options:
      keep_files_after: "today-{download_range}"

    overrides:
      download_range: "1week"

####################################################################################################
  # Preset to cut sponsor segments from videos
  sponsorblock:
    chapters:
      # Remove all of these sponsorblock categories
      sponsorblock_categories:
        - "intro"
        - "outro"
        - "selfpromo"
        - "preview"
        - "interaction"
        - "sponsor"
        - "music_offtopic"
      remove_sponsorblock_categories: "all"
      force_key_frames: False

```
