### ISSUE TITLE
Date range for Soundcloud subscription?

### ISSUE THREAD

**Issue by smshapiro85** [jmbannon/ytdl-sub#801]
Hello! I am trying out my first subscription for a soundcloud channel, but it doesn't seem like the date_range is being respected. When I fire up the command to download, it begins to download the entire channels meta data, which is around 1,700 tracks. My goal is to only download tracks from the previous 2 weeks.

Here is my config.yml:

```
configuration:
  working_directory: ".ytdl-sub-working-directory"

presets:
  2weeks:
    date_range:
      before: "now"
      after: "today-2weeks"
```

And here is my subscription.yml

```
SoundCloud Discography:
  preset: "2weeks"
  = Trance:
    "Above & Beyond": "https://soundcloud.com/aboveandbeyond"
```

Is this the correct way to include the preset with a soundcloud channel? I couldn't find any examples with soundcloud specifically. Any help would be greatly appreciated. Thank you!
