### ISSUE TITLE
Getting permission error when running config/run-cron

### ISSUE THREAD

**Issue by smshapiro85** [jmbannon/ytdl-sub#803]
Hello! I fully realize this is an issue with my limited knowledge of docker, but I am hoping to get some help with the cron setup as I am not able to get the test command working when logged in as "abc" user.

Here is my docker-compose file that I have running in portainer, running on a synology NAS:

```
services:
  ytdl-sub:
    image: ghcr.io/jmbannon/ytdl-sub-gui:latest
    container_name: ytdl-sub
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Los_Angeles
      - DOCKER_MODS=linuxserver/mods:universal-cron
    volumes:
      - /volume1/docker/ytdl-sub:/config
      - /volume1/Music/ytdl-sub:/music  # optional
    ports:
      - 9010:8443
    restart: unless-stopped
```

After following the instructions listed on the knowledge base here: https://github.com/jmbannon/ytdl-sub/wiki/7.-Automate-Downloading-New-Content-Using-Your-Configs

I log back into the container console as user "abc" but get this permissions error:

<img width="1289" alt="image" src="https://github.com/jmbannon/ytdl-sub/assets/41717535/76e2b31e-3c53-47a5-9bc3-ce281b967c2e">

I also confirmed the IDs of the abc user:

<img width="502" alt="image" src="https://github.com/jmbannon/ytdl-sub/assets/41717535/ee170944-f00a-4e22-a123-5fed835c046a">

Running the `/config/run_cron` command as root worked successfully.

Any help would be greatly appreciated!
