### ISSUE TITLE
`Music Videos with Extras` prebuilt preset

### ISSUE THREAD

**Issue by jmbannon** [jmbannon/ytdl-sub#806]
Requires regex'ing override variables prior to any downloading/processing
```
"Jellfyin Music Videos with Extras":
  = Pop:
    "Michael Jackson":
      - "Music Videos | https://www.youtube.com/playlist?list=OLAK5uy_mnY03zP6abNWH929q2XhGzWD_2uKJ_n8E"
      - "Concerts | Live at Wembley (1988) | https://www.youtube.com/watch?v=9shByOh8fVE"
      - "Interviews | ABC (1979) | https://www.youtube.com/watch?v=fTTl4Vaow5Y"
```

Can be done today using multi-url
```
"Jellfyin Music Videos with Extras":
  = Pop:
    "Michael Jackson":
      download:
        - url: "https://www.youtube.com/playlist?list=OLAK5uy_mnY03zP6abNWH929q2XhGzWD_2uKJ_n8E"
          variables:
            type: "Music Videos"
        - url: "https://www.youtube.com/watch?v=9shByOh8fVE"
          variables:
            type: "Concerts"
            custom_title: "Live at Wembley (1988)"
        - url: "https://www.youtube.com/watch?v=fTTl4Vaow5Y"
          variables:
            type: "Interviews"
            custom_title: "ABC (1979)"
```

Or many overrides
```
"Jellfyin Music Videos with Extras":
  = Pop:
    "~Michael Jackson":
      m1: "Music Videos"
      u1: "https://www.youtube.com/playlist?list=OLAK5uy_mnY03zP6abNWH929q2XhGzWD_2uKJ_n8E"
      m2: "Concerts | Live at Wembley (1988)"
      u2: "https://www.youtube.com/watch?v=9shByOh8fVE"
      m3: "Interviews | ABC (1979)"
      u3: "https://www.youtube.com/watch?v=fTTl4Vaow5Y"
```

Or as a list (but requires every-other to be a URL)
```
"Jellfyin Music Videos with Extras":
  = Pop:
    "Michael Jackson":
      - "Music Videos"
      - "https://www.youtube.com/playlist?list=OLAK5uy_mnY03zP6abNWH929q2XhGzWD_2uKJ_n8E"
      - "Concerts | Live at Wembley (1988)"
      - "https://www.youtube.com/watch?v=9shByOh8fVE"
      - "Interviews | ABC (1979)"
      - "https://www.youtube.com/watch?v=fTTl4Vaow5Y"
```

**Comment by jmbannon** [comment]
https://github.com/jmbannon/ytdl-sub/pull/808

**Comment by android-808** [comment]
Apologies if I missed anything in recent commits (I am currently updating my config/subs file to simplify it to the recent changes (ie I no longer needed to have my tag info as it is now present in the base preset).

Seeing as you mention video titles here, one thing I noticed is that sites don't stick to a common naming convention.  You have:

- Channel as Artist Name, Artist Name Official or Record Label.
- Video name as just Video Name or a variant of Artist - Video Name or Artist - Video Name (Official ...)

The first issue is easy to get around by using the subscription name.  The second is more awkward as I don't want to have to add the titles every single time to fix the inconsistancies.  Prior to adding my tag info, Jellyfin would lump all videos in the artist folder into one item, with the video selectable as if you were selecting the audio language to use on a movie.

The second issue with them is a bit more involved.  Before the recent update I was using something based on the following sample for Artist Name - Video Name style conventions.  Is it worth supporting something similar to TV Show Only Recent in the examples and having something that extends the basic music video preset to add support for the different conventions?
```
    video_tags:
        artist: "{processed_artist}"
        title: "{processed_title}"
        album: "Music Videos"
        year: "{upload_year}"
 
    regex:
      from:
        title:
          match:
           - "(.*) - (.*)"
          capture_group_names:
          - "processed_artist"
          - "processed_title"
          capture_group_defaults:
          - "{artist}"
          - "{title}"
```

**Comment by jmbannon** [comment]
Ironically I had this same debate with myself when writing these presets, here is my personal regex:
```
    regex:
      from:
        title:
          match:
            - "(.*) - (.*) \\[O" # artist - song [Official ...
            - "(.*) - (.*) \\(O" # artist - song (Official ...
            - "(.*) - \"(.*)\" \\[O" # artist - "song" [Official ...
            - "(.*) - \"(.*)\" \\(O" # artist - "song" (Official ...
            - "(.*): (.*) \\[O" # artist: song [Official ...
            - "(.*): (.*) \\(O" # artist: song (Official ...
            - "(.*) - \"(.*)\".*" # artist - "song"
            - "(.*) - '(.*)'.*" # artist - 'song'
            - "(.*) - (.*).*" # artist - song
         ```
         
         My conclusion is that there's no perfect regex. Even the one you have above isn't foolproof. This song for example has `Title - Artist` (https://www.youtube.com/watch?v=w_DKWlrA24k). With that said, the presets hardcoding the artist using subscription_name and using the raw video title seems like a good base for the prebuilt preset
