### ISSUE TITLE
FileNotDownloadedException when downloading from a channel

### ISSUE THREAD

**Issue by Kwbmm** [jmbannon/ytdl-sub#811]
Getting a `FileNotDownloadedException` when attempting to download the last week videos of a channel.
[out.log](https://github.com/jmbannon/ytdl-sub/files/13290860/out.log)

**config.yml**:
```yml
configuration:
  working_directory: '/home/ronald/Download'

presets:  
  tv_show_paths:
    overrides:
      tv_show_directory: "/home/ronald/Plex/Youtube"

  base:
    preset:
      - "Jellyfin TV Show by Date"  # Set intended player
      - "max_1080p"    # prebuilt preset to get 1080 videos max
      - "tv_show_paths"

    # Embed chapters into video files
    chapters:
      embed_chapters: True

  add_subs:
    # Embed English subtitles into video files (supports more)
    subtitles:
      embed_subtitles: True
      languages:
        - "en"
      allow_auto_generated_subtitles: True

  no_shorts:
    match_filters:
      filters:
        - "original_url!*=/shorts/"

  sponsorblock:
    chapters:
      sponsorblock_categories:
        - "selfpromo"
        - "interaction"
        - "sponsor"
      remove_sponsorblock_categories: "all"
      force_key_frames: False

  last_week_videos:
    date_range:
      after: "now-1week"
    output_options:
      keep_files_after: "now-1week"
```

**subscription.yml**
```yml
breaking_italy:
  preset:
    - "base"
    - "no_shorts"
    - "last_week_videos"
  download:
    url: "https://www.youtube.com/@breakingitaly/videos"
```

Any idea of what's wrong?
