### ISSUE TITLE
Prebuilt preset that uses YouTube music metadata for Artist, Track Title, etc

### ISSUE THREAD

**Issue by sweiggster51** [jmbannon/ytdl-sub#824]
I have new music.yaml and music_subscription.yaml files. I try to run with the prebuilt_presets and examples yaml files (changing the directories to match my own) but I am getting this error "[ytdl-sub] Validation error in music.yaml: preset name 'Bandcamp' conflicts with a prebuilt preset" when running this command "abc@a5bfba1b4c09:~/ytdl-sub-configs$ ytdl-sub --dry-run --config music.yaml sub music_subscriptions.yaml"

music.yaml (https://pastebin.com/W96qumQG)
music_subscriptions.yaml (https://pastebin.com/QrXFThWH)

I want to have a Youtube Playlist that when I add a song to it, ytdl-sub will look at the playlist, see there is a new song, download, and then put it in the correct folder with the correct file structure (/volume1/data/media/music/{artist}/{{album}/{TrackNumber}-{TrackName}.{ext}) (this is just the file structure that plex prefers) I'm hoping that ytdl-sub can pull the correct info from a playlist that spans multiple genres, artists, albums, etc and put it in the appropriate folders

**Comment by jmbannon** [comment]
It should look something like:
```
presets:
  "Custom Bandcamp"
    overrides:
      music_directory: "/volume1/data/media/music"
      album_dir: "{track_album_sanitized}"
      track_file_name: "{track_number_padded}-{track_title_sanitized}.{ext}"
```

Changing those values will be recognized in the variable:
```
 track_full_path: "{artist_dir}/{album_dir}/{track_file_name}"
```
and write the paths how you want. Then in your subscription, have it look like the README but change `Bandcamp` to your custom preset `Custom Bandcamp`

**Comment by sweiggster51** [comment]
Log File: https://pastebin.com/Z7A3Ra98
music.yaml: https://pastebin.com/FmSGhNFG
music_subscriptions.yaml: https://pastebin.com/GYpznpK7

Thanks for helping me putter through this

**Comment by jmbannon** [comment]
`  = {track_genre_sanitized}:` is wrong, you need to set to the value that you want set on genre, i.e. `= Jazz`. What you have I believe is causing the recursion error

**Comment by jmbannon** [comment]
Genre is tied to the subscription, there is no way to individually set genre on videos within the playlist unless you do some clever regexing using the `regex` plugin

**Comment by jmbannon** [comment]
As for the error: `PermissionError: [Errno 13] Permission denied: '/volume1'`

**Comment by jmbannon** [comment]
The PUID/PGID you are using can't write to that mounted directory

**Comment by sweiggster51** [comment]
I am now getting this error:

[ytdl-sub] A permission error occurred:
[Errno 13] Permission denied: '/tmp/_volume1_docker_ytdl-sub_working-directory'
The user running ytdl-sub must have permission to this file/directory.

I changed the PUID/PGID to the dockerlimited user but also tried it with my admin account and neither had permission to the file/directory.

**Comment by sweiggster51** [comment]
Okay I think I am kind of making progress. I changed my directories from having a / at the start "/volume1/docker/..." to "volume1/docker/..." and that seemed to fix the permission errors. Now, however, every single working-directory I put in the config outputs to "/ytdl-sub/ytdl-sub-configs/working-directory" or any subset within the ytdl-sub-configs folder. It is also outputting the outputting directory within that same folder

**Comment by sweiggster51** [comment]
(I am using Synology NAS btw if that helps)

**Comment by sweiggster51** [comment]
I at least got the output directory to change just by referencing "/music" in my subscriptions and config yaml files as that is what I binded during my setup. However, it is not taking the individual tracks and making folders for the artist/album. Again please correct me if this is not possible with ytdl-sub.

I have a YouTube Playlist called "All Music". Right now it has two songs in it, T.N.T. by ACDC and Stricken by Disturbed. Ytdl-sub successfully downloads the two songs, but places them in "/music/All Music/All Music [2018]" as opposed to pulling metadata from the videos/song titles, etc. and then placing them in "/music/Disturbed/Ten Thousand Fists/Stricken" and "/music/AC-DC/High Voltage/TNT" or however the track would be named.

music.yaml https://pastebin.com/pvBGS2Sa
music_subscriptions.yaml https://pastebin.com/Tz4RU0bv

**Comment by jmbannon** [comment]
Sorry for the delayed response @sweiggster51 . The current music preset implementations do not look at song metadata, just the title for track name and the subscription name for the artist.

To pull from a playlist that contains a mix of artists, you will need a custom config + presets. It should be possible to do with the recent additions to ytdl-sub, but not trivial.

Going to morph this GH issue into a feature request to create a prebuilt preset that tries to pull from YT's formal music metadata

**Comment by jo-chemla** [comment]
Watching this, as the files downloaded via ytdl-sub for my current subscription do miss some Youtube Music metadata (overwriting genre with the yaml defined one, setting artist name to the playlist name etc). These two yt-dlp issue threads (linked in a similar issue) might be of interest: https://github.com/yt-dlp/yt-dlp/issues/622 and https://github.com/yt-dlp/yt-dlp/issues/4217

```yml
YouTube Releases:
    = Music: 
      "Youtube-Music-Likes-LL-cookies": # dynamic but requires up-to-date cookies.txt which can be downloaded from a cookies plugin on ffox, chrome etc
        overrides: 
          subscription_value: "https://www.youtube.com/playlist?list=LL"
        filter_include:
          - >-
            { %ne( %map_get( entry_metadata, %string("artist"), null ), null ) }
```
