### ISSUE TITLE
How to create files as own user on host system?

### ISSUE THREAD

**Issue by clemwo** [jmbannon/ytdl-sub#868]
Hi, I have ytdl-sub running via docker compose:

```
services:
  ytdl-sub:
    image: ghcr.io/jmbannon/ytdl-sub:latest
    container_name: ytdl-sub
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mods:universal-cron
    volumes:
      - ${DOCKER_CONFIG_DIR}/ytdl-sub:/config
      - /mnt/storage1/data:/data
    restart: unless-stopped
```

Now all the folders and files that get created dont have my own user account with PUID and PGID 1000 as owner but some user with ID 100999.

How can I make ytdl-sub create files so that I can access them as my own user account after creation?
