### ISSUE TITLE
Download music only items - exclude videos, don't extract audio

### ISSUE THREAD

**Issue by jo-chemla** [jmbannon/ytdl-sub#891]
Hi there, 

ytdl-sub is a great utility, thanks a lot for that! Quick question: I can download my liked videos by using the `cookies.txt` cookie-file and playlist url `https://www.youtube.com/playlist?list=LL`. I'm wondering if it is possible to download only music/songs since my likes-playlist contains both music-only and videos. 

I'm not looking for a way to extract audio from all videos, but rather a way to exclude videos and download only items which are audio only. This might be a pure yt-dlp question so I cross-posted it here: https://github.com/yt-dlp/yt-dlp/issues/8969. 

```yml
__preset__:
  ytdl_options:
    # max_downloads: 10  # Desired number to download per invocation
    cookiefile: "/config/youtube-cookies/cookies.txt"
    break_on_existing: False 

YouTube Releases:
    = Music: 
      "Youtube-Music-Likes": 
        overrides: 
          subscription_value: "https://www.youtube.com/playlist?list=LL"
```

**Comment by jmbannon** [comment]
There is no simple way out of the box. You could try adding a filter/regex to see if it's audio via inspecting the title or description. Maintaining a separate playlist is probably the best workaround

**Comment by jmbannon** [comment]
Still happy to help, closing since this isn't an issue/feature request

**Comment by jo-chemla** [comment]
Thanks. Started watching this issue thread here https://github.com/yt-dlp/yt-dlp/issues/622 which is probably the best place to get a filter between standard-youtube vs youtube-music file source. Plus, from here https://github.com/yt-dlp/yt-dlp/issues/4217 it seems that the `--embed-metadata` tag adds `artist, title, album` metadata, which might be absent from video files metadata, so this could be a discriminator a posteriori between music (pure audio) vs video.

**Comment by jmbannon** [comment]
Good idea @jo-chemla , you could add the following to a preset:

```
filter_include:
  - "{ %ne( %map_get( entry_metadata, "artist", null ), null ) }"
```
which means 'only include if entry_metadata (i.e. the info.json) artist field is not equal (ne) to null

**Comment by jo-chemla** [comment]
Great idea, trying that. Atm I get this error (running the run_cron script on my docker container, had to use new-line to "escape" the quotes)
```
ytdl_sub.script.utils.exceptions.FunctionRuntimeException: Runtime error occurred when executing the function %map_get: 'in <string>' requires string as left operand, not String
```

```yml
    = Music: 
      "Youtube-Music-Likes": 
        overrides: 
          subscription_value: "https://www.youtube.com/playlist?list=LL"
        filter_include:
          - >-
            { %ne( %map_get( entry_metadata, "artist", null ), null ) }
```
