### ISSUE TITLE
Detected multiple top-level parents crash (& duplication?)

### ISSUE THREAD

**Issue by parkr** [jmbannon/ytdl-sub#908]
Hey, the last few days I've been running into issues with ytdl-sub in Docker. Reproducible for image tagged `2024.01.15` and `2024.01.19.post1` (I haven't tried in between). Here's my subscription:

```yaml
# Download JC music videos for higher-res enjoyment.
# Goal: download latest videos, not playlists or anything like that.
jacob_collier:                                                                 
  preset:                                                                      
  - "music_video"                                                              
  - "only_recent_videos"                                                       
  - "best_video_quality"                                                       
  overrides:                                                                   
    url: "https://www.youtube.com/@jacobcollier"                               
    artist: "Jacob Collier"                                                    
    download_range: "2years" 
```

Here's my error (`Detected multiple top-level parents` from a VEVO playlist?):

```
...
[ytdl-sub:yt-dlp] [download] Downloading item 40 of 136
[ytdl-sub:yt-dlp] [youtube] Extracting URL: https://www.youtube.com/watch?v=V5T-9RPW4pg
[ytdl-sub:yt-dlp] [youtube] V5T-9RPW4pg: Downloading webpage
[ytdl-sub:downloader] Downloading metadata for Jacob Collier - The Sun Is In Your Eyes (Live at Dubai Expo)
[ytdl-sub:yt-dlp] [youtube] V5T-9RPW4pg: Downloading ios player API JSON
[ytdl-sub:yt-dlp] [youtube] V5T-9RPW4pg: Downloading android player API JSON
[ytdl-sub:yt-dlp] [youtube] V5T-9RPW4pg: Downloading m3u8 information
[ytdl-sub:yt-dlp] [download] Jacob Collier plays White Christmas on Harpejji does not pass filter (upload_date >= 20220120), skipping ..
[ytdl-sub:yt-dlp-downloader] RejectedVideoReached, stopping additional downloads (Can be disable by setting `date_range.breaking` to False).
[ytdl-sub:yt-dlp-downloader] Attempting to get parent metadata from URL https://www.youtube.com/@jacobcolliervevo7376
[ytdl-sub:yt-dlp-downloader] ytdl_options: {'ignoreerrors': True, 'outtmpl': '.ytdl-sub-downloads/jacob_collier/%(id)S.%(ext)s', 'writethumbnail': False, 'ffmpeg_location': '/usr/bin/ffmpeg', 'download_archive': '.ytdl-sub-downloads/jacob_collier/.ytdl-sub-jacob_collier-download-archive.json', 'match_filter': <function match_filter_func.<locals>._match_func at 0xffffa330e0c0>, 'format': 'bestvideo+bestaudio/best', 'break_on_existing': True, 'break_on_reject': True, 'merge_output_format': 'mp4', 'skip_download': True, 'writeinfojson': True, 'extract_flat': 'discard', 'playlist_items': '0:0'}
[ytdl-sub:yt-dlp] [youtube:tab] Extracting URL: https://www.youtube.com/@jacobcolliervevo7376
[ytdl-sub:yt-dlp] [youtube:tab] @jacobcolliervevo7376: Downloading webpage
[ytdl-sub:yt-dlp] [youtube:tab] Downloading all uploads of the channel. To download only the videos in a specific tab, pass the tab's URL
[ytdl-sub:yt-dlp] [youtube:tab] @jacobcolliervevo7376/streams: Downloading webpage
[ytdl-sub:yt-dlp] [youtube:tab] Downloading as multiple playlists, separated by tabs. To download as a single playlist instead, pass https://www.youtube.com/playlist?list=UUtvwz4sbS7mbIShLbBlGc7Q
[ytdl-sub:yt-dlp] [download] Downloading playlist: JacobCollierVEVO
[ytdl-sub:yt-dlp] [info] Writing playlist metadata as JSON to: .ytdl-sub-downloads/jacob_collier/@jacobcolliervevo7376.info.json
[ytdl-sub:yt-dlp] [youtube:tab] Playlist JacobCollierVEVO: Downloading 0 items of 2
[ytdl-sub:yt-dlp] [info] Writing updated playlist metadata as JSON to: .ytdl-sub-downloads/jacob_collier/@jacobcolliervevo7376.info.json
[ytdl-sub:yt-dlp] [download] Finished downloading playlist: JacobCollierVEVO
[ytdl-sub:yt-dlp-downloader] Adding parent metadata with ids [@jacobcolliervevo7376, @jacobcolliervevo7376]
[ytdl-sub] The following error occurred for the subscription jacob_collier:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 375, in exception_handling
    yield
  File "/usr/lib/python3.11/site-packages/ytdl_sub/cli/entrypoint.py", line 126, in _download_subscriptions_from_yaml_files
    subscription.download(dry_run=dry_run)
  File "/usr/lib/python3.11/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 362, in download
    return self._process_subscription(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 302, in _process_subscription
    for entry in downloader.download_metadata():
  File "/usr/lib/python3.11/site-packages/ytdl_sub/downloaders/url/downloader.py", line 450, in download_metadata
    parents, orphan_entries = self._download_url_metadata(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/downloaders/url/downloader.py", line 406, in _download_url_metadata
    parents = EntryParent.from_entry_dicts(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/entries/entry_parent.py", line 211, in from_entry_dicts
    if (root_parent := cls._get_disconnected_root_parent(url, parents)) is not None:
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/entries/entry_parent.py", line 183, in _get_disconnected_root_parent
    raise ValueError(
ValueError: Detected multiple top-level parents. Please file an issue on GitHub with the URLs used to produce this error
````

Prior context: #322 suggests removing `.ytdl-sub` working directory which is ephemeral for me (in docker). I removed the `.ytdl-sub-jacob_collier-download-archive.json` which prompted the downloads you see above.
