### ISSUE TITLE
Updating to latest makes some subscriptions fail

### ISSUE THREAD

**Issue by krafs** [jmbannon/ytdl-sub#910]
I bumped my version of ytdl-sub to the latest version, and two of my subscriptions started failing. I don't know if the errors have the same cause, but I'm including both of them here.

Attaching my `config.yaml` and `subscriptions.yaml` here:
<details>
  <summary><i>config.yaml</i></summary>

```yml
configuration:
  persist_logs:
    logs_directory: /config/logs
    keep_successful_logs: false
  working_directory: /tmp/ytdl-sub-downloads

presets:
  tv_show:
    preset:
      - kodi_tv_show_by_date
      - season_by_year__episode_by_month_day
      - best_video_quality

    match_filters:
      filters:
        - '!is_live'

    date_range:
      after: "today-{download_range}"

    ytdl_options:
      check_formats: true
      break_on_reject: true

    output_options:
      keep_files_after: "today-{download_range}"

    overrides:
      tv_show_directory: /tv_shows
      tv_show_name: "{subscription_name}"
      episode_title: "{title}"
      download_range: 6weeks
      url: "https://www.youtube.com/@{channel_slug}"
```
</details>
<details>
  <summary><i>subscriptions.yaml</i></summary>

```yml
__preset__:
  preset: 'tv_show'

"Dotnet Community Standup":
  regex:
    from:
      title:
        match: "Community Standup"
  overrides:
    channel_slug: dotnet/streams

"WAN Show":
  regex:
    from:
      title:
        match: 'WAN Show'
  ytdl_options:
    break_on_reject: false
    max_downloads: 5
  output_options:
    keep_files_after: 'today-2weeks'
  overrides:
    download_range: '1years'
    channel_slug: LinusTechTips/streams
```
</details>

Here's the two error logs:
[2024-01-21-110141.dotnet_community_standup.error.log](https://github.com/jmbannon/ytdl-sub/files/14000963/2024-01-21-110141.dotnet_community_standup.error.log)
[2024-01-21-111326.wan_show.error.log](https://github.com/jmbannon/ytdl-sub/files/14000964/2024-01-21-111326.wan_show.error.log)

**Comment by jmbannon** [comment]
@krafs Seems like a ytdl-sub issue, can you send me which python version you're using? `python --version` should do the trick

**Comment by krafs** [comment]
I should probably have mentioned, but I am using the Docker image **ghcr.io/jmbannon/ytdl-sub**, with docker-compose:
```yml
services:
  ytdl-sub:
    image: ghcr.io/jmbannon/ytdl-sub:latest
    container_name: ytdl-sub
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - DOCKER_MODS=linuxserver/mods:universal-cron
    volumes:
      - ./ytdl-sub:/config
      - ./videos/youtube/shows:/tv_shows
    restart: unless-stopped
```
My running container reports Python **3.11.6**.
