### ISSUE TITLE
Question: Index of cumulative URLs passed in to download?

### ISSUE THREAD

**Issue by jacroe** [jmbannon/ytdl-sub#930]
(I apologize if this has been documented, but I couldn't find it if it was.)

In certain situations, a content provider would have a series that is clearly a series but doesn't provide a playlist themselves. For example:

```yaml
cdawgva_lethal_company:
  preset:
    - "tv_show"
    - "ten_days_before"
    - "sponsorblock_sponsors"
  download:
    - "https://youtube.com/watch?v=ef-avG3DTOQ"
    - "https://youtube.com/watch?v=EmC9tgtfYJk"
  overrides:
    tv_show_name: "CDawgVA - Lethal Company"
```

However, I would still like to store it using incremental filenames. E.g. "CDawgVA - Lethal Company - S01E01 - I Tried Trusting VTubers For Once....mkv" and "CDawgVA - Lethal Company - S01E02 - I Ruined His Life By Getting Him Addicted To This Game.mkv".

Is there a way to use the listed download order in the filename? i.e. `EmC...` is listed so it's "episode" would be `2`. As a bonus, if there was a playlist included at the end, the first video in the playlist would have its `episode` be `3`. 

In the scenario described in the yaml sample, both `playlist_index_padded` and `source_index_padded` returned `01`.
