### ISSUE TITLE
easily download from multiple urls

### ISSUE THREAD

**Issue by PlexSheep** [jmbannon/ytdl-sub#931]
I want to download multiple specific playlists for a channel. In the past, something like this kinda worked, but I can't reproduce it now:

```yaml
YouTube Releases:
   = J-Pop:
      "Ado":
        download:
          - "https://www.youtube.com/@Ado1024/releases"
          - "https://www.youtube.com/playlist?list=PLaxauk3chSWjJUBirUlCQH9fOgvfiNjcc"
          - "https://www.youtube.com/playlist?list=PLaxauk3chSWizBh8KxPj83Ue03qy0A_Xv"
```

This is at best hacky and hard to find, probably does not even work. It would be really nice if we could just do:

```yaml
YouTube Releases:
   = J-Pop:
      "Ado":
        - "https://www.youtube.com/@Ado1024/releases"
        - "https://www.youtube.com/playlist?list=PLaxauk3chSWjJUBirUlCQH9fOgvfiNjcc"
        - "https://www.youtube.com/playlist?list=PLaxauk3chSWizBh8KxPj83Ue03qy0A_Xv"
```

And be done with it.
