### ISSUE TITLE
Issue with content rating and plex

### ISSUE THREAD

**Issue by jhofker** [jmbannon/ytdl-sub#935]
I'm not sure that content rating is getting set properly in the metadata in order for Plex to read it. But! I also haven't confirmed that beyond what you see here, as I can't find specific definitions for the metadata that Plex is expecting :-)

What am I doing wrong? I'm expecting that the TV-Y rating set in the yml would show up on the show and the individual episodes in my library, which would then allow me to make that content available to users who have content restrictions on their accounts.

Subscription yml:
```yml
# Overrides to the prebuilt presets
__preset__:
  overrides:
    tv_show_directory: "/tv_shows" # Root folder of all ytdl-sub TV Shows

    # For 'Only Recent' preset, only keep vids within this range and limit
    only_recent_date_range: "2months"
    only_recent_max_files: 30

# Choose the player you intend to use by setting the top-level key to be either:
#   - Plex TV Show by Date:
#   - Jellyfin TV Show by Date:
#   - Kodi TV Show by Date:
Plex TV Show by Date:
  # Sets genre tag to "Documentaries"
  # = Documentaries:
  #   "NOVA PBS": "https://www.youtube.com/@novapbs"
  #   "National Geographic": "https://www.youtube.com/@NatGeo"
  #   "Cosmos - What If": "https://www.youtube.com/playlist?list=PLZdXRHYAVxTJno6oFF9nLGuwXNGYHmE8U"

  # Sets genre tag to "Kids", "TV-Y" for content rating
  = Kids | = TV-Y:
    "Andrea Nelson Art": "https://www.youtube.com/@Andrea-Nelson-Art"
```

```bash
cat s2023.e082801\ -\ How\ to\ paint\ a\ simple\ beach\ in\ watercolor\!.info.json | grep TV-
    "episode_content_rating": "TV-Y",
    "episode_content_rating_sanitized": "TV-Y",
    "subscription_indent_2": "TV-Y",
    "subscription_indent_2_sanitized": "TV-Y",
    "tv_show_content_rating": "TV-Y",
    "tv_show_content_rating_default": "TV-14",
    "tv_show_content_rating_default_sanitized": "TV-14",
    "tv_show_content_rating_sanitized": "TV-Y",
```

Show:
<img width="505" alt="image" src="https://github.com/jmbannon/ytdl-sub/assets/812787/8deca690-8925-496d-9e61-f2b323721933">

Episode:
<img width="574" alt="image" src="https://github.com/jmbannon/ytdl-sub/assets/812787/ee6ad621-f6b1-4a75-9b48-9df1960d3873">
