### ISSUE TITLE
Does not download from Twitch

### ISSUE THREAD

**Issue by nothing2obvi** [jmbannon/ytdl-sub#944]
Hello. I have everything working for YouTube but it seems to just skip over Twitch.

```
Cron started, running ytdl-sub...
[ytdl-sub] Validating subscriptions...
[ytdl-sub] Beginning subscription download for channel1
[ytdl-sub:downloader] Beginning downloads for “https://www.twitch.tv/channel1/videos”
[ytdl-sub] Beginning subscription download for channel2
[ytdl-sub:downloader] Beginning downloads for “https://www.twitch.tv/channel2/videos”
```

Those are the only things in the logs and then it moves on to my other subscriptions.

Here are the relevant parts from `config.yaml`

```
configuration:
  working_directory: ‘/ytdl-sub/temp’

presets:
  Files:
    embed_thumbnail: True
    file_convert:
      convert_to: "mkv"
    format: "(bv*[height<=1080]+bestaudio/best[height<=1080])"
    output_options:
      output_directory: "{output_directory}"
      file_name: "{upload_year}.{upload_month_padded}.{upload_day_padded}_{channel}_{title_sanitized}.{ext}"
      maintain_download_archive: True
    ytdl_options:
      # Ignore any download related errors and continue
      ignoreerrors: True
      # Stop downloading additional metadata/videos if it exists in download archive
      break_on_existing: True
      # Path to YouTube cookies file to download 18+ restricted content
      cookiefile: "/config/cookie.txt"
      # Download and use English title/description/etc YouTube metadata
      extractor_args:
        youtube:
          lang:
            - "en"
  Files - Plus Twitch:
    output_options:
      info_json_name: "{upload_year}.{upload_month_padded}.{upload_day_padded}_{channel}_{title_sanitized}.{info_json_ext}"
      keep_files_after: now-1month
  Twitch:
    preset:
      - "Files"
      - "Files - Plus Twitch"
      - "Jellyfin TV Show by Date"
    overrides:
      tv_show_directory: "/twitch"
    output_options:
      maintain_download_archive: True
      keep_files_after: "now-1month"
```

Here are the relevant parts from `subscriptions.yaml`.

```
# subscriptions.yaml:
# Everything in here can be downloaded using the command:
#   ytdl-sub sub subscriptions.yaml

# __preset__ is a place to define global overrides for all subscriptions
__preset__:
  overrides:
    # Root folder of all ytdl-sub TV Shows
    tv_show_directory: “/ytdl-sub/tv-shows”

    # Root folder of all ytdl-sub Music
    music_directory: "/music"

    # Root folder of all ytdl-sub Music Videos
    music_video_directory: "/music-videos"

    # For 'Only Recent' preset, only keep vids within this range and limit
    only_recent_date_range: “2months”
    only_recent_max_files: 60

  # Pass any arg directly to yt-dlp's Python API
  ytdl_options:
    cookiefile: "/config/cookie.txt"


Twitch:
  # Sets genre tag to “Twitch”
  = Twitch:
    channel1: “https://www.twitch.tv/channel1/videos”
    channel2: “https://www.twitch.tv/channel2/videos”
```
