### ISSUE TITLE
Trouble with subtitles

### ISSUE THREAD

**Issue by jsuelwald** [jmbannon/ytdl-sub#964]
Subtitles aren't downloaded. What am I doing wrong? (Yeah, the videos downloaded do have subtitles for at least one of the configured languages

> ytdl-sub -c config.yaml sub media.yaml

--- config.yaml ---
```
presets:
  base:
    # Embed chapters into video files
    chapters:
      embed_chapters: True

    # Embed English subtitles into video files (supports more)
    subtitles:
      #subtitles_name: "{title_sanitized}.{lang}.{subtitles_ext}"
      #subtitles_type: "srt"
      embed_subtitles: True
      languages:
        - "en"  # supports multiple languages
        - "de"
      allow_auto_generated_subtitles: True

```

--- media.yaml ---
```
__preset__:
  overrides:
    tv_show_directory: "/mnt/dl/yt"  # Root folder of all ytdl-sub TV Shows

    # For 'Only Recent' preset, only keep vids within this range and limit
    only_recent_date_range: "7days"
    only_recent_max_files: 300

Jellyfin TV Show by Date:
  = Documentaries | Only Recent:
    "Code Bullet": "https://www.youtube.com/@CodeBullet"
```
