### ISSUE TITLE
Only downloading past few videos

### ISSUE THREAD

**Issue by Phill360** [jmbannon/ytdl-sub#980]
Hi All,

I'm trying download a channel called Brick Legends but when I try to do the download its only downloading the past few episodes .

Thanks in advance

The subcription is 
```
BrickLegends:
  preset:
    - "tv_show"
    - "ninjago"

  overrides:
    tv_show_name: "Brick Legends"
    url: "https://www.youtube.com/channel/UCrgvBwSSu-qw0qEknHrjsMw"
    tv_show_genre: "Kids" 
```

The preset config is 
``` 
  tv_show:
    preset:
      - "plex_tv_show_by_date"


      # Choose one of the following season/episode formats:
      - "season_by_year__episode_by_month_day"
      - "season_by_year__episode_by_month_day" # replace with desired season/episode format

      - "add_subtitles"
      - "sponsorblock"
      - "include_info_json"
    
ninjago:
    date_range:
    output_options:
      keep_files_after: "now-1year"
      maintain_download_archive: True
```
